TRUNCATE TABLE REPORTFIELDGROUP_REPORTDATASUBSOURCE;
TRUNCATE TABLE REPORTFIELD_REPORTFIELDGROUP;
TRUNCATE TABLE REPORTFIELD;
TRUNCATE TABLE REPORTFIELDGROUP_REPORTDATASUBSOURCE;
TRUNCATE TABLE REPORTFIELDGROUP;
TRUNCATE TABLE REPORTDATASUBSOURCE;
TRUNCATE TABLE REPORTDATASOURCE;
