

-- *********************************************************************************************************************
--
-- Picklists View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_PICKLISTS;
CREATE VIEW VW_PICKLISTS
AS
	SELECT
		SPLITCAMELCASEDSTRING(PICKLIST_NAME) AS PICKLIST_PICKLIST_NAME,
		PICKLIST.ENTITY_TYPE AS PICKLIST_ENTITY_TYPE,
		PICKLIST.MULTISELECT AS PICKLIST_MULTISELECT,
		PICKLIST.SITE_NAME AS PICKLIST_SITE_NAME,

		PICKLIST_ITEM.ITEM_NAME AS PICKLIST_ITEM_ITEM_NAME,
		PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE AS PICKLIST_ITEM_DEFAULT_DISPLAY_VALUE,
		PICKLIST_ITEM.ITEM_ORDER AS PICKLIST_ITEM_ITEM_ORDER,
		PICKLIST_ITEM.INACTIVE AS PICKLIST_ITEM_INACTIVE
	FROM PICKLIST
	LEFT JOIN PICKLIST_ITEM ON PICKLIST.PICKLIST_ID = PICKLIST_ITEM.PICKLIST_ID
;

-- *********************************************************************************************************************
--
-- Constituents View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS;
CREATE VIEW VW_CONSTITUENTS
AS
	SELECT
		CONSTITUENT.CONSTITUENT_ID AS CONSTITUENT_CONSTITUENT_ID,
		CONSTITUENT_ROLES_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT.CONSTITUENT_TYPE AS CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT.CREATE_DATE AS CONSTITUENT_CREATE_DATE,
		CONSTITUENT.FIRST_NAME AS CONSTITUENT_FIRST_NAME,
		DONOR_PROFILES_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT.LAST_NAME AS CONSTITUENT_LAST_NAME,
		CONSTITUENT.LEGAL_NAME AS CONSTITUENT_LEGAL_NAME,
		CONSTITUENT.LOGIN_ID AS CONSTITUENT_LOGIN_ID,
		CONSTITUENT.MARITAL_STATUS AS CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT.MIDDLE_NAME AS CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT.NCAIS_CODE AS CONSTITUENT_NCAIS_CODE,
		CONSTITUENT.ORGANIZATION_NAME AS CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT.PREFERRED_PHONE_TYPE AS CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT.RECOGNITION_NAME AS CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT.SUFFIX AS CONSTITUENT_SUFFIX,
		CONSTITUENT.TITLE AS CONSTITUENT_TITLE,
		CONSTITUENT.UPDATE_DATE AS CONSTITUENT_UPDATE_DATE,
		CONSTITUENT.SITE_NAME AS CONSTITUENT_SITE_NAME
	FROM CONSTITUENT
	-- Profile Types
	LEFT JOIN CUSTOM_FIELD AS CONSTITUENT_ROLES ON CONSTITUENT_ROLES.ENTITY_TYPE = 'person' AND CONSTITUENT_ROLES.ENTITY_ID = CONSTITUENT.CONSTITUENT_ID AND CONSTITUENT_ROLES.FIELD_NAME =
    CASE WHEN CONSTITUENT_TYPE = 'individual' THEN 'constituentIndividualRoles' WHEN CONSTITUENT_TYPE = 'organization' THEN 'constituentOrganizationRoles' ELSE '' END
	LEFT JOIN PICKLIST AS CONSTITUENT_ROLES_PICKLIST ON CONSTITUENT_ROLES_PICKLIST.PICKLIST_NAME_ID =
		CASE WHEN CONSTITUENT_TYPE = 'individual' THEN 'customFieldMap[constituentIndividualRoles]' WHEN CONSTITUENT_TYPE = 'organization' THEN 'customFieldMap[constituentOrganizationRoles]' ELSE '' END
	LEFT JOIN PICKLIST_ITEM AS CONSTITUENT_ROLES_PICKLISTITEMS ON CONSTITUENT_ROLES_PICKLISTITEMS.PICKLIST_ID = CONSTITUENT_ROLES_PICKLIST.PICKLIST_ID AND CONSTITUENT_ROLES_PICKLISTITEMS.ITEM_NAME = CONSTITUENT_ROLES.FIELD_VALUE
	-- Donor Profiles
	LEFT JOIN CUSTOM_FIELD AS DONOR_PROFILES ON DONOR_PROFILES.ENTITY_TYPE = 'person' AND DONOR_PROFILES.ENTITY_ID = CONSTITUENT.CONSTITUENT_ID AND DONOR_PROFILES.FIELD_NAME = 'donorProfiles'
	LEFT JOIN PICKLIST AS DONOR_PROFILES_PICKLIST ON DONOR_PROFILES_PICKLIST.PICKLIST_NAME_ID = 'customFieldMap[donorProfiles]'
	LEFT JOIN PICKLIST_ITEM AS DONOR_PROFILES_PICKLISTITEMS ON DONOR_PROFILES_PICKLISTITEMS.PICKLIST_ID = DONOR_PROFILES_PICKLIST.PICKLIST_ID AND DONOR_PROFILES_PICKLISTITEMS.ITEM_NAME = DONOR_PROFILES.FIELD_VALUE
;


-- *********************************************************************************************************************
--
-- Constituents & Addresses View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_ADDRESSES;
CREATE VIEW VW_CONSTITUENTS_ADDRESSES
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		-- Address Information
		ADDRESS.ADDRESS_ID AS ADDRESS_ADDRESS_ID,
		ADDRESS_TYPE_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS ADDRESS_ADDRESS_TYPE,
		ADDRESS.ACTIVATION_STATUS AS ADDRESS_ACTIVATION_STATUS,
		ADDRESS.EFFECTIVE_DATE AS ADDRESS_EFFECTIVE_DATE,
		ADDRESS.ADDRESS_LINE_1 AS ADDRESS_ADDRESS_LINE_1,
		ADDRESS.ADDRESS_LINE_2 AS ADDRESS_ADDRESS_LINE_2,
		ADDRESS.ADDRESS_LINE_3 AS ADDRESS_ADDRESS_LINE_3,
		ADDRESS.CITY AS ADDRESS_CITY,
		ADDRESS.STATE_PROVINCE AS ADDRESS_STATE_PROVINCE,
		ADDRESS.COUNTRY AS ADDRESS_COUNTRY,
		ADDRESS.POSTAL_CODE AS ADDRESS_POSTAL_CODE,
		ADDRESS.RECEIVE_CORRESPONDENCE AS ADDRESS_RECEIVE_CORRESPONDENCE,
		ADDRESS.COMMENT AS ADDRESS_COMMENT,
		ADDRESS.SEASONAL_END_DATE AS ADDRESS_SEASONAL_END_DATE,
		ADDRESS.SEASONAL_START_DATE AS ADDRESS_SEASONAL_START_DATE,
		ADDRESS.TEMPORARY_END_DATE AS ADDRESS_TEMPORARY_END_DATE,
		ADDRESS.TEMPORARY_START_DATE AS ADDRESS_TEMPORARY_START_DATE,
		ADDRESS.CREATE_DATE AS ADDRESS_CREATE_DATE,
		ADDRESS.UPDATE_DATE AS ADDRESS_UPDATE_DATE,
		ADDRESS.INACTIVE AS ADDRESS_INACTIVE
	FROM VW_CONSTITUENTS
	LEFT JOIN ADDRESS ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD ADDRESS_TYPE ON ADDRESS_TYPE.ENTITY_TYPE = 'address' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = 'addressType'
	LEFT JOIN PICKLIST AS ADDRESS_TYPE_PICKLIST ON ADDRESS_TYPE_PICKLIST.PICKLIST_NAME_ID = 'customFieldMap[addressType]'
	LEFT JOIN PICKLIST_ITEM AS ADDRESS_TYPE_PICKLISTITEMS ON ADDRESS_TYPE_PICKLISTITEMS.PICKLIST_ID = ADDRESS_TYPE_PICKLIST.PICKLIST_ID AND ADDRESS_TYPE_PICKLISTITEMS.ITEM_NAME = ADDRESS_TYPE.FIELD_VALUE
;


-- *********************************************************************************************************************
--
-- Constituents & Email Addresses View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_EMAILS;
CREATE VIEW VW_CONSTITUENTS_EMAILS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		-- Email Information
		EMAIL.EMAIL_ID AS EMAIL_EMAIL_ID,
		EMAIL_TYPES_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS EMAIL_EMAIL_TYPE,
		EMAIL.ACTIVATION_STATUS AS EMAIL_ACTIVATION_STATUS,
		EMAIL.EFFECTIVE_DATE AS EMAIL_EFFECTIVE_DATE,
		EMAIL.SEASONAL_START_DATE AS EMAIL_SEASONAL_START_DATE,
		EMAIL.SEASONAL_END_DATE AS EMAIL_SEASONAL_END_DATE,
		EMAIL.TEMPORARY_START_DATE AS EMAIL_TEMPORARY_START_DATE,
		EMAIL.TEMPORARY_END_DATE AS EMAIL_TEMPORARY_END_DATE,
		EMAIL.EMAIL_ADDRESS AS EMAIL_EMAIL_ADDRESS,
		EMAIL.EMAIL_DISPLAY AS EMAIL_EMAIL_DISPLAY,
		EMAIL.RECEIVE_CORRESPONDENCE AS EMAIL_RECEIVE_CORRESPONDENCE,
		EMAIL.COMMENT AS EMAIL_COMMENT,
		EMAIL.CREATE_DATE AS EMAIL_CREATE_DATE,
		EMAIL.UPDATE_DATE AS EMAIL_UPDATE_DATE,
		EMAIL.INACTIVE AS EMAIL_INACTIVE
	FROM VW_CONSTITUENTS
	LEFT JOIN EMAIL ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD AS EMAIL_TYPES ON EMAIL_TYPES.ENTITY_TYPE = 'email' AND EMAIL_TYPES.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPES.FIELD_NAME = 'emailType'
	LEFT JOIN PICKLIST AS EMAIL_TYPES_PICKLIST ON EMAIL_TYPES_PICKLIST.PICKLIST_NAME_ID = 'customFieldMap[emailType]'
	LEFT JOIN PICKLIST_ITEM AS EMAIL_TYPES_PICKLISTITEMS ON EMAIL_TYPES_PICKLISTITEMS.PICKLIST_ID = EMAIL_TYPES_PICKLIST.PICKLIST_ID AND EMAIL_TYPES_PICKLISTITEMS.ITEM_NAME = EMAIL_TYPES.FIELD_VALUE
;


-- *********************************************************************************************************************
--
-- Constituents & Phone Numbers View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_PHONENUMBERS;
CREATE VIEW VW_CONSTITUENTS_PHONENUMBERS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		-- Phone Number Information
		PHONE.PHONE_ID AS PHONE_PHONE_ID,
		PHONE_TYPES_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS PHONE_PHONE_TYPE,
		PHONE.ACTIVATION_STATUS AS PHONE_ACTIVATION_STATUS,
		PHONE.EFFECTIVE_DATE AS PHONE_EFFECTIVE_DATE,
		PHONE.SEASONAL_START_DATE AS PHONE_SEASONAL_START_DATE,
		PHONE.SEASONAL_END_DATE AS PHONE_SEASONAL_END_DATE,
		PHONE.TEMPORARY_START_DATE AS PHONE_TEMPORARY_START_DATE,
		PHONE.TEMPORARY_END_DATE AS PHONE_TEMPORARY_END_DATE,
		PHONE.NUMBER AS PHONE_NUMBER,
		PHONE.PROVIDER AS PHONE_PROVIDER,
		PHONE.SMS AS PHONE_SMS,
		PHONE.RECEIVE_CORRESPONDENCE AS PHONE_RECEIVE_CORRESPONDENCE,
		PHONE.COMMENT AS PHONE_COMMENT,
		PHONE.CREATE_DATE AS PHONE_CREATE_DATE,
		PHONE.UPDATE_DATE AS PHONE_UPDATE_DATE,
		PHONE.INACTIVE AS PHONE_INACTIVE
	FROM VW_CONSTITUENTS
	LEFT JOIN PHONE ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD AS PHONE_TYPES ON PHONE_TYPES.ENTITY_TYPE = 'phone' AND PHONE_TYPES.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPES.FIELD_NAME = 'phoneType'
	LEFT JOIN PICKLIST AS PHONE_TYPES_PICKLIST ON PHONE_TYPES_PICKLIST.PICKLIST_NAME_ID = 'customFieldMap[phoneType]'
	LEFT JOIN PICKLIST_ITEM AS PHONE_TYPES_PICKLISTITEMS ON PHONE_TYPES_PICKLISTITEMS.PICKLIST_ID = PHONE_TYPES_PICKLIST.PICKLIST_ID AND PHONE_TYPES_PICKLISTITEMS.ITEM_NAME = PHONE_TYPES.FIELD_VALUE
;



-- *********************************************************************************************************************
--
-- Constituent & Relationships View
--
-- *********************************************************************************************************************


DROP VIEW IF EXISTS VW_CONSTITUENTS_RELATIONSHIPS;
CREATE VIEW VW_CONSTITUENTS_RELATIONSHIPS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,
		CONSTITUENT_EMPLOYERS.FIELD_VALUE AS CONSTITUENT_EMPLOYER,
		CONSTITUENT_HOUSEHOLD_MEMBERS.FIELD_VALUE AS CONSTITUENT_HOUSEHOLD_MEMBER,
		CONSTITUENT_PARENTS.FIELD_VALUE AS CONSTITUENT_PARENT,
		CONSTITUENT_CHILDREN.FIELD_VALUE AS CONSTITUENT_CHILD,
		CONSTITUENT_SIBLINGS.FIELD_VALUE AS CONSTITUENT_SIBLING,
		CONSTITUENT_FRIENDS.FIELD_VALUE AS CONSTITUENT_FRIEND,
		CONSTITUENT_EMPLOYEES.FIELD_VALUE AS CONSTITUENT_EMPLOYEE,
		CONSTITUENT_SUBSIDIARYLIST.FIELD_VALUE AS CONSTITUENT_SUBSIDIARY,
		CONSTITUENT_PRIMARYCONTACTS.FIELD_VALUE AS CONSTITUENT_PRIMARYCONTACT,
		CONSTITUENT_BILLINGCONTACTS.FIELD_VALUE AS CONSTITUENT_BILLINGCONTACT,
		CONSTITUENT_SALESCONTACTS.FIELD_VALUE AS CONSTITUENT_SALESCONTACT,
		CONSTITUENT_PUBLICRELATIONSCONTACTS.FIELD_VALUE AS CONSTITUENT_PUBLICRELATIONSCONTACT
	FROM VW_CONSTITUENTS
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_EMPLOYERS ON CONSTITUENT_EMPLOYERS.ENTITY_TYPE = 'person' AND CONSTITUENT_EMPLOYERS.FIELD_NAME = 'individual.organizations' AND CONSTITUENT_EMPLOYERS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_HOUSEHOLD_MEMBERS ON CONSTITUENT_HOUSEHOLD_MEMBERS.ENTITY_TYPE = 'person' AND CONSTITUENT_HOUSEHOLD_MEMBERS.FIELD_NAME = 'headOfHousehold.householdMembers' AND CONSTITUENT_HOUSEHOLD_MEMBERS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_PARENTS ON CONSTITUENT_PARENTS.ENTITY_TYPE = 'person' AND CONSTITUENT_PARENTS.FIELD_NAME = 'individual.parents' AND CONSTITUENT_PARENTS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_CHILDREN ON CONSTITUENT_CHILDREN.ENTITY_TYPE = 'person' AND CONSTITUENT_CHILDREN.FIELD_NAME = 'individual.children' AND CONSTITUENT_CHILDREN.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_SIBLINGS ON CONSTITUENT_SIBLINGS.ENTITY_TYPE = 'person' AND CONSTITUENT_SIBLINGS.FIELD_NAME = 'individual.siblings' AND CONSTITUENT_SIBLINGS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_FRIENDS ON CONSTITUENT_FRIENDS.ENTITY_TYPE = 'person' AND CONSTITUENT_FRIENDS.FIELD_NAME = 'individual.friends' AND CONSTITUENT_FRIENDS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_EMPLOYEES ON CONSTITUENT_EMPLOYEES.ENTITY_TYPE = 'person' AND CONSTITUENT_EMPLOYEES.FIELD_NAME = 'organization.employees' AND CONSTITUENT_EMPLOYEES.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_SUBSIDIARYLIST ON CONSTITUENT_SUBSIDIARYLIST.ENTITY_TYPE = 'person' AND CONSTITUENT_SUBSIDIARYLIST.FIELD_NAME = 'organization.subsidiaryList' AND CONSTITUENT_SUBSIDIARYLIST.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_PRIMARYCONTACTS ON CONSTITUENT_PRIMARYCONTACTS.ENTITY_TYPE = 'person' AND CONSTITUENT_PRIMARYCONTACTS.FIELD_NAME = 'organization.primaryContacts' AND CONSTITUENT_PRIMARYCONTACTS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_BILLINGCONTACTS ON CONSTITUENT_BILLINGCONTACTS.ENTITY_TYPE = 'person' AND CONSTITUENT_BILLINGCONTACTS.FIELD_NAME = 'organization.billingContacts' AND CONSTITUENT_BILLINGCONTACTS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_SALESCONTACTS ON CONSTITUENT_SALESCONTACTS.ENTITY_TYPE = 'person' AND CONSTITUENT_SALESCONTACTS.FIELD_NAME = 'organization.salesContacts' AND CONSTITUENT_SALESCONTACTS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
	LEFT JOIN CUSTOM_FIELD CONSTITUENT_PUBLICRELATIONSCONTACTS ON CONSTITUENT_PUBLICRELATIONSCONTACTS.ENTITY_TYPE = 'person' AND CONSTITUENT_PUBLICRELATIONSCONTACTS.FIELD_NAME = 'organization.publicRelationsContacts' AND CONSTITUENT_PUBLICRELATIONSCONTACTS.ENTITY_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
;


-- *********************************************************************************************************************
--
-- Gifts View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_GIFTS;
CREATE VIEW VW_GIFTS
AS
	SELECT
		GIFT.CONSTITUENT_ID AS GIFT_CONSTITUENT_ID,
		GIFT.GIFT_ID AS GIFT_GIFT_ID,
		GIFT.AMOUNT AS GIFT_AMOUNT,
		GIFT.CURRENCY_CODE AS GIFT_CURRENCY_CODE,
		GIFT.DONATION_DATE AS GIFT_DONATION_DATE,
		GIFT.POSTMARK_DATE AS GIFT_POSTMARK_DATE,
		GIFT.COMMENTS AS GIFT_COMMENTS,
		GIFT.TRANSACTION_DATE AS GIFT_TRANSACTIONDATE,

		-- Payment Information
		PAYMENT_SOURCE.PAYMENT_PROFILE AS GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		GIFT.PAYMENT_TYPE AS GIFT_PAYMENT_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_TYPE AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_HOLDER_NAME AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		CONCAT(MONTH(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION), '/', YEAR(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION)) AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		PAYMENT_SOURCE.ACH_HOLDER_NAME AS GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		CONCAT('****', RIGHT(PAYMENT_SOURCE.ACH_ROUTING_NUMBER, 4)) AS GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		GIFT.CHECK_NUMBER AS GIFT_CHECK_NUMBER,
		AUTH_CODE AS GIFT_AUTH_CODE,
			-- Payment Address
		GIFT_PAYMENT_ADDRESS.ADDRESS_LINE_1 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		GIFT_PAYMENT_ADDRESS.ADDRESS_LINE_2 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		GIFT_PAYMENT_ADDRESS.ADDRESS_LINE_3 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		GIFT_PAYMENT_ADDRESS.CITY AS GIFT_PAYMENT_ADDRESS_CITY,
		GIFT_PAYMENT_ADDRESS.STATE_PROVINCE AS GIFT_PAYMENT_ADDRESS_STATE_PROVINCE,
		GIFT_PAYMENT_ADDRESS.POSTAL_CODE AS GIFT_PAYMENT_ADDRESS_POSTAL_CODE,
		GIFT_PAYMENT_ADDRESS.COUNTRY AS GIFT_PAYMENT_ADDRESS_COUNTRY,
			-- Payment Phone
		GIFT_PAYMENT_PHONE.NUMBER AS GIFT_PAYMENT_PHONE_NUMBER
	FROM GIFT
	LEFT JOIN PAYMENT_SOURCE ON GIFT.PAYMENT_SOURCE_ID = PAYMENT_SOURCE.PAYMENT_SOURCE_ID
	LEFT JOIN ADDRESS GIFT_PAYMENT_ADDRESS ON GIFT.ADDRESS_ID = GIFT_PAYMENT_ADDRESS.ADDRESS_ID
	LEFT JOIN PHONE GIFT_PAYMENT_PHONE ON GIFT.PHONE_ID = GIFT_PAYMENT_PHONE.PHONE_ID

;


-- *********************************************************************************************************************
--
-- Gifts & Gift Distributions View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_GIFTS_DISTRIBUTIONS;
CREATE VIEW VW_GIFTS_DISTRIBUTIONS
AS
	SELECT
		GIFT.CONSTITUENT_ID AS GIFT_CONSTITUENT_ID,
		GIFT.GIFT_ID AS GIFT_GIFT_ID,
		GIFT.AMOUNT AS GIFT_AMOUNT,
		GIFT.CURRENCY_CODE AS GIFT_CURRENCY_CODE,
		GIFT.DONATION_DATE AS GIFT_DONATION_DATE,
		GIFT.POSTMARK_DATE AS GIFT_POSTMARK_DATE,
		GIFT.COMMENTS AS GIFT_COMMENTS,
		GIFT.TRANSACTION_DATE AS GIFT_TRANSACTIONDATE,

		-- Payment Information
		PAYMENT_SOURCE.PAYMENT_PROFILE AS GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		GIFT.PAYMENT_TYPE AS GIFT_PAYMENT_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_TYPE AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_HOLDER_NAME AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		CONCAT(MONTH(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION), '/', YEAR(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION)) AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		PAYMENT_SOURCE.ACH_HOLDER_NAME AS GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		CONCAT('****', RIGHT(PAYMENT_SOURCE.ACH_ROUTING_NUMBER, 4)) AS GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		GIFT.CHECK_NUMBER AS GIFT_CHECK_NUMBER,
		AUTH_CODE AS GIFT_AUTH_CODE,
			-- Payment Address
		GIFT_PAYMENT_ADDRESS.ADDRESS_LINE_1 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		GIFT_PAYMENT_ADDRESS.ADDRESS_LINE_2 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		GIFT_PAYMENT_ADDRESS.ADDRESS_LINE_3 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		GIFT_PAYMENT_ADDRESS.CITY AS GIFT_PAYMENT_ADDRESS_CITY,
		GIFT_PAYMENT_ADDRESS.STATE_PROVINCE AS GIFT_PAYMENT_ADDRESS_STATE_PROVINCE,
		GIFT_PAYMENT_ADDRESS.POSTAL_CODE AS GIFT_PAYMENT_ADDRESS_POSTAL_CODE,
		GIFT_PAYMENT_ADDRESS.COUNTRY AS GIFT_PAYMENT_ADDRESS_COUNTRY,
			-- Payment Phone
		GIFT_PAYMENT_PHONE.NUMBER AS GIFT_PAYMENT_PHONE_NUMBER,

		-- Gift Distribution Line Information
		DISTRO_LINE.DISTRO_LINE_ID AS DISTRO_LINE_DISTRO_LINE_ID,
		DISTRO_LINE.AMOUNT AS DISTRO_LINE_AMOUNT,
		DISTRO_LINE.PERCENTAGE AS DISTRO_LINE_PERCENTAGE,
		DISTRO_LINE.PROJECT_CODE AS DISTRO_LINE_PROJECT_CODE,
		PROJECTCODE_PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE AS DISTRO_LINE_PROJECT_CODE_DESCRIPTION,
		DISTRO_LINE.MOTIVATION_CODE AS DISTRO_LINE_MOTIVATION_CODE,
		MOTIVATIONCODE_PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE AS DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION
	FROM GIFT
	LEFT JOIN PAYMENT_SOURCE ON GIFT.PAYMENT_SOURCE_ID = PAYMENT_SOURCE.PAYMENT_SOURCE_ID
	LEFT JOIN ADDRESS GIFT_PAYMENT_ADDRESS ON GIFT.ADDRESS_ID = GIFT_PAYMENT_ADDRESS.ADDRESS_ID
	LEFT JOIN PHONE GIFT_PAYMENT_PHONE ON GIFT.PHONE_ID = GIFT_PAYMENT_PHONE.PHONE_ID
	LEFT JOIN DISTRO_LINE ON GIFT.GIFT_ID = DISTRO_LINE.GIFT_ID
	LEFT JOIN CONSTITUENT ON CONSTITUENT.CONSTITUENT_ID = GIFT.CONSTITUENT_ID
	LEFT JOIN PICKLIST PROJECTCODE_PICKLIST ON PROJECTCODE_PICKLIST.PICKLIST_NAME = 'projectCode'
	LEFT JOIN PICKLIST_ITEM PROJECTCODE_PICKLIST_ITEM ON PROJECTCODE_PICKLIST.PICKLIST_ID = PROJECTCODE_PICKLIST_ITEM.PICKLIST_ID AND PROJECTCODE_PICKLIST_ITEM.ITEM_NAME = DISTRO_LINE.PROJECT_CODE
	LEFT JOIN PICKLIST MOTIVATIONCODE_PICKLIST ON MOTIVATIONCODE_PICKLIST.PICKLIST_NAME = 'motivationCode'
	LEFT JOIN PICKLIST_ITEM MOTIVATIONCODE_PICKLIST_ITEM ON MOTIVATIONCODE_PICKLIST.PICKLIST_ID = MOTIVATIONCODE_PICKLIST_ITEM.PICKLIST_ID AND MOTIVATIONCODE_PICKLIST_ITEM.ITEM_NAME = DISTRO_LINE.MOTIVATION_CODE
;


-- *********************************************************************************************************************
--
-- Payment History View & Field Definitions
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_PAYMENTHISTORY;
CREATE VIEW VW_PAYMENTHISTORY
AS
	SELECT
		PAYMENT_HISTORY.PAYMENT_HISTORY_ID AS PAYMENT_HISTORY_PAYMENT_HISTORY_ID,
		PAYMENT_HISTORY.CONSTITUENT_ID AS PAYMENT_HISTORY_CONSTITUENT_ID,
		PAYMENT_HISTORY.GIFT_ID AS PAYMENT_HISTORY_GIFT_ID,
		PAYMENT_HISTORY.TRANSACTION_DATE AS PAYMENT_HISTORY_TRANSACTION_DATE,
		PAYMENT_HISTORY.PAYMENT_TYPE AS PAYMENT_HISTORY_PAYMENT_TYPE,
		PAYMENT_HISTORY.AMOUNT AS PAYMENT_HISTORY_AMOUNT,
		PAYMENT_HISTORY.CURRENCY_CODE AS PAYMENT_HISTORY_CURRENCY_CODE,
		PAYMENT_HISTORY.PAYMENT_DESC AS PAYMENT_HISTORY_PAYMENT_DESC,
		CASE PAYMENT_HISTORY.PAYMENT_HISTORY_TYPE WHEN 0 THEN 'Unspecified' WHEN 1 THEN 'Gift' WHEN 2 THEN 'Membership' WHEN 3 THEN 'Order' END AS PAYMENT_HISTORY_PAYMENT_HISTORY_TYPE
	FROM PAYMENT_HISTORY
;


-- *********************************************************************************************************************
--
-- Payment Methods View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_PAYMENTMETHODS;
CREATE VIEW VW_PAYMENTMETHODS
AS
	SELECT
		PAYMENT_SOURCE.PAYMENT_SOURCE_ID AS PAYMENT_SOURCE_PAYMENT_SOURCE_ID,
		PAYMENT_SOURCE.CONSTITUENT_ID AS PAYMENT_SOURCE_CONSTITUENT_ID,
		PAYMENT_SOURCE.PAYMENT_PROFILE AS PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		PAYMENT_SOURCE.PAYMENT_TYPE AS PAYMENT_SOURCE_PAYMENT_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_HOLDER_NAME AS PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		PAYMENT_SOURCE.CREDIT_CARD_TYPE AS PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		CONCAT(MONTH(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION), '/', YEAR(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION)) AS PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION AS PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		PAYMENT_SOURCE.ACH_HOLDER_NAME AS PAYMENT_SOURCE_ACH_HOLDER_NAME,
		CONCAT('****', RIGHT(PAYMENT_SOURCE.ACH_ROUTING_NUMBER, 4)) AS PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
			-- Payment Address
		PAYMENTMETHOD_ADDRESS.ADDRESS_LINE_1 AS PAYMENT_SOURCE_ADDRESS_ADDRESS_LINE_1,
		PAYMENTMETHOD_ADDRESS.ADDRESS_LINE_2 AS PAYMENT_SOURCE_ADDRESS_ADDRESS_LINE_2,
		PAYMENTMETHOD_ADDRESS.ADDRESS_LINE_3 AS PAYMENT_SOURCE_ADDRESS_ADDRESS_LINE_3,
		PAYMENTMETHOD_ADDRESS.CITY AS PAYMENT_SOURCE_ADDRESS_CITY,
		PAYMENTMETHOD_ADDRESS.STATE_PROVINCE AS PAYMENT_SOURCE_ADDRESS_STATE_PROVINCE,
		PAYMENTMETHOD_ADDRESS.POSTAL_CODE AS PAYMENT_SOURCE_ADDRESS_POSTAL_CODE,
		PAYMENTMETHOD_ADDRESS.COUNTRY AS PAYMENT_SOURCE_ADDRESS_COUNTRY,
			-- Payment Phone
		PAYMENTMETHOD_PHONE.NUMBER AS PAYMENT_SOURCE_PHONE_NUMBER
	FROM PAYMENT_SOURCE
	LEFT JOIN ADDRESS PAYMENTMETHOD_ADDRESS ON PAYMENT_SOURCE.ADDRESS_ID = PAYMENTMETHOD_ADDRESS.ADDRESS_ID
	LEFT JOIN PHONE PAYMENTMETHOD_PHONE ON PAYMENT_SOURCE.PHONE_ID = PAYMENTMETHOD_PHONE.PHONE_ID
;


-- *********************************************************************************************************************
--
-- Pledges View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_PLEDGES;
CREATE VIEW VW_PLEDGES
AS
	SELECT
		COMMITMENT.CONSTITUENT_ID AS COMMITMENT_CONSTITUENT_ID,
		COMMITMENT.PLEDGE_ID AS COMMITMENT_COMMITMENT_ID,
		COMMITMENT.RECURRING AS COMMITMENT_RECURRING,
		COMMITMENT.AMOUNT_PER_GIFT AS COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT.AMOUNT_TOTAL AS COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT.CURRENCY_CODE AS COMMITMENT_CURRENCY_CODE,
		COMMITMENT.PLEDGE_STATUS AS COMMITMENT_STATUS,
		COMMITMENT.FREQUENCY AS COMMITMENT_FREQUENCY,
		COMMITMENT.PLEDGE_DATE AS COMMITMENT_PLEDGE_DATE,
		COMMITMENT.PROJECTED_DATE AS COMMITMENT_PROJECTED_DATE,
		COMMITMENT.START_DATE AS COMMITMENT_START_DATE,
		COMMITMENT.END_DATE AS COMMITMENT_END_DATE,
		COMMITMENT.COMMENTS AS COMMITMENT_COMMENTS
	FROM PLEDGE AS COMMITMENT
;


-- *********************************************************************************************************************
--
-- Pledges & Distributions View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_PLEDGES_DISTRIBUTIONS;
CREATE VIEW VW_PLEDGES_DISTRIBUTIONS
AS
	SELECT
		COMMITMENT.CONSTITUENT_ID AS COMMITMENT_CONSTITUENT_ID,
		COMMITMENT.PLEDGE_ID AS COMMITMENT_COMMITMENT_ID,
		COMMITMENT.RECURRING AS COMMITMENT_RECURRING,
		COMMITMENT.AMOUNT_PER_GIFT AS COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT.AMOUNT_TOTAL AS COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT.CURRENCY_CODE AS COMMITMENT_CURRENCY_CODE,
		COMMITMENT.PLEDGE_STATUS AS COMMITMENT_STATUS,
		COMMITMENT.FREQUENCY AS COMMITMENT_FREQUENCY,
		COMMITMENT.PLEDGE_DATE AS COMMITMENT_PLEDGE_DATE,
		COMMITMENT.PROJECTED_DATE AS COMMITMENT_PROJECTED_DATE,
		COMMITMENT.START_DATE AS COMMITMENT_START_DATE,
		COMMITMENT.END_DATE AS COMMITMENT_END_DATE,
		COMMITMENT.COMMENTS AS COMMITMENT_COMMENTS,

		-- Gift Distribution Line Information
		DISTRO_LINE.DISTRO_LINE_ID AS DISTRO_LINE_DISTRO_LINE_ID,
		DISTRO_LINE.AMOUNT AS DISTRO_LINE_AMOUNT,
		DISTRO_LINE.PERCENTAGE AS DISTRO_LINE_PERCENTAGE,
		DISTRO_LINE.PROJECT_CODE AS DISTRO_LINE_PROJECT_CODE,
		PROJECTCODE_PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE AS DISTRO_LINE_PROJECT_CODE_DESCRIPTION,
		DISTRO_LINE.MOTIVATION_CODE AS DISTRO_LINE_MOTIVATION_CODE,
		MOTIVATIONCODE_PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE AS DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION

	FROM PLEDGE AS COMMITMENT
	LEFT JOIN DISTRO_LINE ON COMMITMENT.PLEDGE_ID = DISTRO_LINE.PLEDGE_ID
	LEFT JOIN CONSTITUENT ON CONSTITUENT.CONSTITUENT_ID = COMMITMENT.CONSTITUENT_ID
	LEFT JOIN PICKLIST PROJECTCODE_PICKLIST ON PROJECTCODE_PICKLIST.PICKLIST_NAME = 'projectCode'
	LEFT JOIN PICKLIST_ITEM PROJECTCODE_PICKLIST_ITEM ON PROJECTCODE_PICKLIST.PICKLIST_ID = PROJECTCODE_PICKLIST_ITEM.PICKLIST_ID AND PROJECTCODE_PICKLIST_ITEM.ITEM_NAME = DISTRO_LINE.PROJECT_CODE
	LEFT JOIN PICKLIST MOTIVATIONCODE_PICKLIST ON MOTIVATIONCODE_PICKLIST.PICKLIST_NAME = 'motivationCode'
	LEFT JOIN PICKLIST_ITEM MOTIVATIONCODE_PICKLIST_ITEM ON MOTIVATIONCODE_PICKLIST.PICKLIST_ID = MOTIVATIONCODE_PICKLIST_ITEM.PICKLIST_ID AND MOTIVATIONCODE_PICKLIST_ITEM.ITEM_NAME = DISTRO_LINE.MOTIVATION_CODE
;


-- *********************************************************************************************************************
--
-- Recurring Gifts View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_RECURRINGGIFTS;
CREATE VIEW VW_RECURRINGGIFTS
AS
	SELECT
		COMMITMENT.RECURRING_GIFT_ID AS COMMITMENT_COMMITMENT_ID,
		COMMITMENT.CONSTITUENT_ID AS COMMITMENT_CONSTITUENT_ID,
		COMMITMENT.AUTO_PAY AS COMMITMENT_AUTO_PAY,
		COMMITMENT.AMOUNT_PER_GIFT AS COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT.AMOUNT_TOTAL AS COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT.CURRENCY_CODE AS COMMITMENT_CURRENCY_CODE,
		COMMITMENT.FREQUENCY AS COMMITMENT_FREQUENCY,
		COMMITMENT.START_DATE AS COMMITMENT_START_DATE,
		COMMITMENT.END_DATE AS COMMITMENT_END_DATE,
		COMMITMENT.RECURRING_GIFT_STATUS AS COMMITMENT_STATUS,
		COMMITMENT.COMMENTS AS COMMITMENT_COMMENTS,
		COMMITMENT.LAST_ENTRY_DATE AS COMMITMENT_LAST_ENTRY_DATE,
		COMMITMENT.CREATE_DATE AS COMMITMENT_CREATE_DATE,
		COMMITMENT.UPDATE_DATE AS COMMITMENT_UPDATE_DATE,

		-- Payment Information
		PAYMENT_SOURCE.PAYMENT_PROFILE AS COMMITMENT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		COMMITMENT.PAYMENT_TYPE AS COMMITMENT_PAYMENT_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_TYPE AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_HOLDER_NAME AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		CONCAT(MONTH(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION), '/', YEAR(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION)) AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		PAYMENT_SOURCE.ACH_HOLDER_NAME AS COMMITMENT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		CONCAT('****', RIGHT(PAYMENT_SOURCE.ACH_ROUTING_NUMBER, 4)) AS COMMITMENT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		COMMITMENT.CHECK_NUMBER AS COMMITMENT_CHECK_NUMBER,
			-- Payment Address
		COMMITMENT_PAYMENT_ADDRESS.ADDRESS_LINE_1 AS COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		COMMITMENT_PAYMENT_ADDRESS.ADDRESS_LINE_2 AS COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		COMMITMENT_PAYMENT_ADDRESS.ADDRESS_LINE_3 AS COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		COMMITMENT_PAYMENT_ADDRESS.CITY AS COMMITMENT_PAYMENT_ADDRESS_CITY,
		COMMITMENT_PAYMENT_ADDRESS.STATE_PROVINCE AS COMMITMENT_PAYMENT_ADDRESS_STATE_PROVINCE,
		COMMITMENT_PAYMENT_ADDRESS.POSTAL_CODE AS COMMITMENT_PAYMENT_ADDRESS_POSTAL_CODE,
		COMMITMENT_PAYMENT_ADDRESS.COUNTRY AS COMMITMENT_PAYMENT_ADDRESS_COUNTRY,
			-- Payment Phone
		COMMITMENT_PAYMENT_PHONE.NUMBER AS COMMITMENT_PAYMENT_PHONE_NUMBER
	FROM RECURRING_GIFT AS COMMITMENT
	LEFT JOIN PAYMENT_SOURCE ON COMMITMENT.PAYMENT_SOURCE_ID = PAYMENT_SOURCE.PAYMENT_SOURCE_ID
	LEFT JOIN ADDRESS COMMITMENT_PAYMENT_ADDRESS ON COMMITMENT.ADDRESS_ID = COMMITMENT_PAYMENT_ADDRESS.ADDRESS_ID
	LEFT JOIN PHONE COMMITMENT_PAYMENT_PHONE ON COMMITMENT.PHONE_ID = COMMITMENT_PAYMENT_PHONE.PHONE_ID
;


-- *********************************************************************************************************************
--
-- Recurring Gifts & Distributions View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_RECURRINGGIFTS_DISTRIBUTIONS;
CREATE VIEW VW_RECURRINGGIFTS_DISTRIBUTIONS
AS
	SELECT
		COMMITMENT.RECURRING_GIFT_ID AS COMMITMENT_COMMITMENT_ID,
		COMMITMENT.CONSTITUENT_ID AS COMMITMENT_CONSTITUENT_ID,
		COMMITMENT.AUTO_PAY AS COMMITMENT_AUTO_PAY,
		COMMITMENT.AMOUNT_PER_GIFT AS COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT.AMOUNT_TOTAL AS COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT.CURRENCY_CODE AS COMMITMENT_CURRENCY_CODE,
		COMMITMENT.FREQUENCY AS COMMITMENT_FREQUENCY,
		COMMITMENT.START_DATE AS COMMITMENT_START_DATE,
		COMMITMENT.END_DATE AS COMMITMENT_END_DATE,
		COMMITMENT.RECURRING_GIFT_STATUS AS COMMITMENT_STATUS,
		COMMITMENT.COMMENTS AS COMMITMENT_COMMENTS,
		-- COMMITMENT.RECURRING AS COMMITMENT_RECURRING,
		COMMITMENT.LAST_ENTRY_DATE AS COMMITMENT_LAST_ENTRY_DATE,
		COMMITMENT.CREATE_DATE AS COMMITMENT_CREATE_DATE,
		COMMITMENT.UPDATE_DATE AS COMMITMENT_UPDATE_DATE,

		-- Payment Information
		PAYMENT_SOURCE.PAYMENT_PROFILE AS COMMITMENT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		COMMITMENT.PAYMENT_TYPE AS COMMITMENT_PAYMENT_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_TYPE AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_HOLDER_NAME AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		CONCAT(MONTH(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION), '/', YEAR(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION)) AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION AS COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		PAYMENT_SOURCE.ACH_HOLDER_NAME AS COMMITMENT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		CONCAT('****', RIGHT(PAYMENT_SOURCE.ACH_ROUTING_NUMBER, 4)) AS COMMITMENT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		COMMITMENT.CHECK_NUMBER AS COMMITMENT_CHECK_NUMBER,
			-- Payment Address
		COMMITMENT_PAYMENT_ADDRESS.ADDRESS_LINE_1 AS COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		COMMITMENT_PAYMENT_ADDRESS.ADDRESS_LINE_2 AS COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		COMMITMENT_PAYMENT_ADDRESS.ADDRESS_LINE_3 AS COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		COMMITMENT_PAYMENT_ADDRESS.CITY AS COMMITMENT_PAYMENT_ADDRESS_CITY,
		COMMITMENT_PAYMENT_ADDRESS.STATE_PROVINCE AS COMMITMENT_PAYMENT_ADDRESS_STATE_PROVINCE,
		COMMITMENT_PAYMENT_ADDRESS.POSTAL_CODE AS COMMITMENT_PAYMENT_ADDRESS_POSTAL_CODE,
		COMMITMENT_PAYMENT_ADDRESS.COUNTRY AS COMMITMENT_PAYMENT_ADDRESS_COUNTRY,
			-- Payment Phone
		COMMITMENT_PAYMENT_PHONE.NUMBER AS COMMITMENT_PAYMENT_PHONE_NUMBER,

		-- Gift Distribution Line Information
		DISTRO_LINE.DISTRO_LINE_ID AS DISTRO_LINE_DISTRO_LINE_ID,
		DISTRO_LINE.AMOUNT AS DISTRO_LINE_AMOUNT,
		DISTRO_LINE.PERCENTAGE AS DISTRO_LINE_PERCENTAGE,
		DISTRO_LINE.PROJECT_CODE AS DISTRO_LINE_PROJECT_CODE,
		PROJECTCODE_PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE AS DISTRO_LINE_PROJECT_CODE_DESCRIPTION,
		DISTRO_LINE.MOTIVATION_CODE AS DISTRO_LINE_MOTIVATION_CODE,
		MOTIVATIONCODE_PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE AS DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION

	FROM RECURRING_GIFT AS COMMITMENT
	LEFT JOIN PAYMENT_SOURCE ON COMMITMENT.PAYMENT_SOURCE_ID = PAYMENT_SOURCE.PAYMENT_SOURCE_ID
	LEFT JOIN ADDRESS COMMITMENT_PAYMENT_ADDRESS ON COMMITMENT.ADDRESS_ID = COMMITMENT_PAYMENT_ADDRESS.ADDRESS_ID
	LEFT JOIN PHONE COMMITMENT_PAYMENT_PHONE ON COMMITMENT.PHONE_ID = COMMITMENT_PAYMENT_PHONE.PHONE_ID
	LEFT JOIN DISTRO_LINE ON COMMITMENT.RECURRING_GIFT_ID = DISTRO_LINE.RECURRING_GIFT_ID
	LEFT JOIN CONSTITUENT ON CONSTITUENT.CONSTITUENT_ID = COMMITMENT.CONSTITUENT_ID
	LEFT JOIN PICKLIST PROJECTCODE_PICKLIST ON PROJECTCODE_PICKLIST.PICKLIST_NAME = 'projectCode'
	LEFT JOIN PICKLIST_ITEM PROJECTCODE_PICKLIST_ITEM ON PROJECTCODE_PICKLIST.PICKLIST_ID = PROJECTCODE_PICKLIST_ITEM.PICKLIST_ID AND PROJECTCODE_PICKLIST_ITEM.ITEM_NAME = DISTRO_LINE.PROJECT_CODE
	LEFT JOIN PICKLIST MOTIVATIONCODE_PICKLIST ON MOTIVATIONCODE_PICKLIST.PICKLIST_NAME = 'motivationCode'
	LEFT JOIN PICKLIST_ITEM MOTIVATIONCODE_PICKLIST_ITEM ON MOTIVATIONCODE_PICKLIST.PICKLIST_ID = MOTIVATIONCODE_PICKLIST_ITEM.PICKLIST_ID AND MOTIVATIONCODE_PICKLIST_ITEM.ITEM_NAME = DISTRO_LINE.MOTIVATION_CODE
;


-- *********************************************************************************************************************
--
-- Constituents & Gifts View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_GIFTS;
CREATE VIEW VW_CONSTITUENTS_GIFTS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		-- Gift Information
		GIFT_CONSTITUENT_ID,
		GIFT_GIFT_ID,
		GIFT_AMOUNT,
		GIFT_CURRENCY_CODE,
		GIFT_DONATION_DATE,
		GIFT_POSTMARK_DATE,
		GIFT_COMMENTS,
		GIFT_TRANSACTIONDATE,
		GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		GIFT_PAYMENT_TYPE,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		GIFT_CHECK_NUMBER,
		GIFT_AUTH_CODE,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		GIFT_PAYMENT_ADDRESS_CITY,
		GIFT_PAYMENT_ADDRESS_STATE_PROVINCE,
		GIFT_PAYMENT_ADDRESS_POSTAL_CODE,
		GIFT_PAYMENT_ADDRESS_COUNTRY,
		GIFT_PAYMENT_PHONE_NUMBER
	FROM VW_CONSTITUENTS
	LEFT JOIN VW_GIFTS ON CONSTITUENT_CONSTITUENT_ID = GIFT_CONSTITUENT_ID
;


-- *********************************************************************************************************************
--
-- Constituents & Gift Distributions View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_GIFTDISTRIBUTIONS;
CREATE VIEW VW_CONSTITUENTS_GIFTDISTRIBUTIONS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		-- Gift Information
		GIFT_GIFT_ID,
		GIFT_AMOUNT,
		GIFT_CURRENCY_CODE,
		GIFT_DONATION_DATE,
		GIFT_POSTMARK_DATE,
		GIFT_COMMENTS,
		GIFT_TRANSACTIONDATE,
		GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		GIFT_PAYMENT_TYPE,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		GIFT_CHECK_NUMBER,
		GIFT_AUTH_CODE,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		GIFT_PAYMENT_ADDRESS_CITY,
		GIFT_PAYMENT_ADDRESS_STATE_PROVINCE,
		GIFT_PAYMENT_ADDRESS_POSTAL_CODE,
		GIFT_PAYMENT_ADDRESS_COUNTRY,
		GIFT_PAYMENT_PHONE_NUMBER,
		DISTRO_LINE_DISTRO_LINE_ID,
		DISTRO_LINE_AMOUNT,
		DISTRO_LINE_PERCENTAGE,
		DISTRO_LINE_PROJECT_CODE,
		DISTRO_LINE_PROJECT_CODE_DESCRIPTION,
		DISTRO_LINE_MOTIVATION_CODE,
		DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION
	FROM VW_CONSTITUENTS
	LEFT JOIN VW_GIFTS_DISTRIBUTIONS ON CONSTITUENT_CONSTITUENT_ID = GIFT_CONSTITUENT_ID
;


-- *********************************************************************************************************************
--
-- Constituents & Payment History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_PAYMENTHISTORY;
CREATE VIEW VW_CONSTITUENTS_PAYMENTHISTORY
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		PAYMENT_HISTORY_PAYMENT_HISTORY_ID,
		PAYMENT_HISTORY_CONSTITUENT_ID,
		PAYMENT_HISTORY_GIFT_ID,
		PAYMENT_HISTORY_TRANSACTION_DATE,
		PAYMENT_HISTORY_PAYMENT_TYPE,
		PAYMENT_HISTORY_AMOUNT,
		PAYMENT_HISTORY_CURRENCY_CODE,
		PAYMENT_HISTORY_PAYMENT_DESC,
		PAYMENT_HISTORY_PAYMENT_HISTORY_TYPE
	FROM VW_CONSTITUENTS
	LEFT JOIN VW_PAYMENTHISTORY ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_PAYMENTHISTORY.PAYMENT_HISTORY_CONSTITUENT_ID
;


-- *********************************************************************************************************************
--
-- Constituents & Payment Methods View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_PAYMENTMETHODS;
CREATE VIEW VW_CONSTITUENTS_PAYMENTMETHODS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,
		-- Payment Information
		PAYMENT_SOURCE.PAYMENT_SOURCE_ID AS PAYMENT_SOURCE_PAYMENT_SOURCE_ID,
		PAYMENT_SOURCE.CONSTITUENT_ID AS PAYMENT_SOURCE_CONSTITUENT_ID,
		PAYMENT_SOURCE.PAYMENT_PROFILE AS GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		PAYMENT_SOURCE.PAYMENT_TYPE AS GIFT_PAYMENT_SOURCE_PAYMENT_TYPE,
		PAYMENT_SOURCE.CREDIT_CARD_HOLDER_NAME AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		PAYMENT_SOURCE.CREDIT_CARD_TYPE AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		CONCAT(MONTH(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION), '/', YEAR(PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION)) AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		PAYMENT_SOURCE.CREDIT_CARD_EXPIRATION AS GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		PAYMENT_SOURCE.ACH_HOLDER_NAME AS GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		CONCAT('****', RIGHT(PAYMENT_SOURCE.ACH_ROUTING_NUMBER, 4)) AS GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
			-- Payment Address
		PAYMENTMETHOD_ADDRESS.ADDRESS_LINE_1 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		PAYMENTMETHOD_ADDRESS.ADDRESS_LINE_2 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		PAYMENTMETHOD_ADDRESS.ADDRESS_LINE_3 AS GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		PAYMENTMETHOD_ADDRESS.CITY AS GIFT_PAYMENT_ADDRESS_CITY,
		PAYMENTMETHOD_ADDRESS.STATE_PROVINCE AS GIFT_PAYMENT_ADDRESS_STATE_PROVINCE,
		PAYMENTMETHOD_ADDRESS.POSTAL_CODE AS GIFT_PAYMENT_ADDRESS_POSTAL_CODE,
		PAYMENTMETHOD_ADDRESS.COUNTRY AS GIFT_PAYMENT_ADDRESS_COUNTRY,
			-- Payment Phone
		PAYMENTMETHOD_PHONE.NUMBER AS GIFT_PAYMENT_PHONE_NUMBER
	FROM VW_CONSTITUENTS
	LEFT JOIN PAYMENT_SOURCE ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PAYMENT_SOURCE.CONSTITUENT_ID
	LEFT JOIN ADDRESS PAYMENTMETHOD_ADDRESS ON PAYMENT_SOURCE.ADDRESS_ID = PAYMENTMETHOD_ADDRESS.ADDRESS_ID
	LEFT JOIN PHONE PAYMENTMETHOD_PHONE ON PAYMENT_SOURCE.PHONE_ID = PAYMENTMETHOD_PHONE.PHONE_ID
;


-- *********************************************************************************************************************
--
-- Constituents & Pledges View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_PLEDGES;
CREATE VIEW VW_CONSTITUENTS_PLEDGES
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		COMMITMENT_CONSTITUENT_ID,
		COMMITMENT_COMMITMENT_ID,
		COMMITMENT_RECURRING,
		COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT_CURRENCY_CODE,
		COMMITMENT_STATUS,
		COMMITMENT_FREQUENCY,
		COMMITMENT_PLEDGE_DATE,
		COMMITMENT_PROJECTED_DATE,
		COMMITMENT_START_DATE,
		COMMITMENT_END_DATE,
		COMMITMENT_COMMENTS
	FROM VW_CONSTITUENTS
	LEFT JOIN VW_PLEDGES ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_PLEDGES.COMMITMENT_CONSTITUENT_ID
;



-- *********************************************************************************************************************
--
-- Constituents & Pledges & Distributions View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_PLEDGES_DISTRIBUTIONS;
CREATE VIEW VW_CONSTITUENTS_PLEDGES_DISTRIBUTIONS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		COMMITMENT_CONSTITUENT_ID,
		COMMITMENT_COMMITMENT_ID,
		COMMITMENT_RECURRING,
		COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT_CURRENCY_CODE,
		COMMITMENT_STATUS,
		COMMITMENT_FREQUENCY,
		COMMITMENT_PLEDGE_DATE,
		COMMITMENT_PROJECTED_DATE,
		COMMITMENT_START_DATE,
		COMMITMENT_END_DATE,
		COMMITMENT_COMMENTS
		DISTRO_LINE_DISTRO_LINE_ID,
		DISTRO_LINE_AMOUNT,
		DISTRO_LINE_PERCENTAGE,
		DISTRO_LINE_PROJECT_CODE,
		DISTRO_LINE_PROJECT_CODE_DESCRIPTION,
		DISTRO_LINE_MOTIVATION_CODE,
		DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION

	FROM VW_CONSTITUENTS
	LEFT JOIN VW_PLEDGES_DISTRIBUTIONS ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_PLEDGES_DISTRIBUTIONS.COMMITMENT_CONSTITUENT_ID
;


-- *********************************************************************************************************************
--
-- Constituents & Recurring Gifts View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_RECURRINGGIFTS;
CREATE VIEW VW_CONSTITUENTS_RECURRINGGIFTS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		COMMITMENT_COMMITMENT_ID,
		COMMITMENT_CONSTITUENT_ID,
		COMMITMENT_AUTO_PAY,
		COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT_CURRENCY_CODE,
		COMMITMENT_FREQUENCY,
		COMMITMENT_START_DATE,
		COMMITMENT_END_DATE,
		COMMITMENT_STATUS,
		COMMITMENT_COMMENTS,
		COMMITMENT_LAST_ENTRY_DATE,
		COMMITMENT_CREATE_DATE,
		COMMITMENT_UPDATE_DATE,
		COMMITMENT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		COMMITMENT_PAYMENT_TYPE,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		COMMITMENT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		COMMITMENT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		COMMITMENT_CHECK_NUMBER,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		COMMITMENT_PAYMENT_ADDRESS_CITY,
		COMMITMENT_PAYMENT_ADDRESS_STATE_PROVINCE,
		COMMITMENT_PAYMENT_ADDRESS_POSTAL_CODE,
		COMMITMENT_PAYMENT_ADDRESS_COUNTRY,
		COMMITMENT_PAYMENT_PHONE_NUMBER
	FROM VW_CONSTITUENTS
	LEFT JOIN VW_RECURRINGGIFTS ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_RECURRINGGIFTS.COMMITMENT_CONSTITUENT_ID
;


-- *********************************************************************************************************************
--
-- Constituents & Recurring Gifts & Distributions View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS;
CREATE VIEW VW_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS
AS
	SELECT
		CONSTITUENT_CONSTITUENT_ID,
 		CONSTITUENT_CONSTITUENT_ROLE,
		CONSTITUENT_CONSTITUENT_TYPE,
		CONSTITUENT_CREATE_DATE,
		CONSTITUENT_FIRST_NAME,
 		CONSTITUENT_DONOR_PROFILE,
		CONSTITUENT_LAST_NAME,
		CONSTITUENT_LEGAL_NAME,
		CONSTITUENT_LOGIN_ID,
		CONSTITUENT_MARITAL_STATUS,
		CONSTITUENT_MIDDLE_NAME,
		CONSTITUENT_NCAIS_CODE,
		CONSTITUENT_ORGANIZATION_NAME,
		CONSTITUENT_PREFERRED_PHONE_TYPE,
		CONSTITUENT_RECOGNITION_NAME,
		CONSTITUENT_SUFFIX,
		CONSTITUENT_TITLE,
		CONSTITUENT_UPDATE_DATE,
		CONSTITUENT_SITE_NAME,

		COMMITMENT_COMMITMENT_ID,
		COMMITMENT_CONSTITUENT_ID,
		COMMITMENT_AUTO_PAY,
		COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT_CURRENCY_CODE,
		COMMITMENT_FREQUENCY,
		COMMITMENT_START_DATE,
		COMMITMENT_END_DATE,
		COMMITMENT_STATUS,
		COMMITMENT_COMMENTS,
		COMMITMENT_LAST_ENTRY_DATE,
		COMMITMENT_CREATE_DATE,
		COMMITMENT_UPDATE_DATE,
		COMMITMENT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		COMMITMENT_PAYMENT_TYPE,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		COMMITMENT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		COMMITMENT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		COMMITMENT_CHECK_NUMBER,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		COMMITMENT_PAYMENT_ADDRESS_CITY,
		COMMITMENT_PAYMENT_ADDRESS_STATE_PROVINCE,
		COMMITMENT_PAYMENT_ADDRESS_POSTAL_CODE,
		COMMITMENT_PAYMENT_ADDRESS_COUNTRY,
		COMMITMENT_PAYMENT_PHONE_NUMBER,
		DISTRO_LINE_DISTRO_LINE_ID,
		DISTRO_LINE_AMOUNT,
		DISTRO_LINE_PERCENTAGE,
		DISTRO_LINE_PROJECT_CODE,
		DISTRO_LINE_PROJECT_CODE_DESCRIPTION,
		DISTRO_LINE_MOTIVATION_CODE,
		DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION
	FROM VW_CONSTITUENTS
	LEFT JOIN VW_RECURRINGGIFTS_DISTRIBUTIONS ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_RECURRINGGIFTS_DISTRIBUTIONS.COMMITMENT_CONSTITUENT_ID
;


-- *********************************************************************************************************************
--
-- Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY;
CREATE VIEW VW_AUDITHISTORY
AS
	SELECT
		AUDIT.AUDIT_ID AS AUDIT_AUDIT_ID,
		AUDIT.DATE AS AUDIT_DATE,
		AUDIT.USER AS AUDIT_USER,
		AUDIT.AUDIT_TYPE AS AUDIT_AUDIT_TYPE,
		AUDIT.DESCRIPTION AS AUDIT_DESCRIPTION,
		AUDIT.ENTITY_TYPE AS AUDIT_ENTITY_TYPE,
		AUDIT.OBJECT_ID AS AUDIT_OBJECT_ID,
		AUDIT.CONSTITUENT_ID AS AUDIT_CONSTITUENT_ID,
		AUDIT.SITE_NAME AS AUDIT_SITE_NAME
	FROM AUDIT
;


-- *********************************************************************************************************************
--
-- Address Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_ADDRESSES;
CREATE VIEW VW_AUDITHISTORY_ADDRESSES
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		-- Address Information
		ADDRESS.ADDRESS_ID AS ADDRESS_ADDRESS_ID,
		ADDRESS.CONSTITUENT_ID AS ADDRESS_CONSTITUENT_ID,
		ADDRESS_TYPE_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS ADDRESS_ADDRESS_TYPE,
		ADDRESS.ACTIVATION_STATUS AS ADDRESS_ACTIVATION_STATUS,
		ADDRESS.EFFECTIVE_DATE AS ADDRESS_EFFECTIVE_DATE,
		ADDRESS.ADDRESS_LINE_1 AS ADDRESS_ADDRESS_LINE_1,
		ADDRESS.ADDRESS_LINE_2 AS ADDRESS_ADDRESS_LINE_2,
		ADDRESS.ADDRESS_LINE_3 AS ADDRESS_ADDRESS_LINE_3,
		ADDRESS.CITY AS ADDRESS_CITY,
		ADDRESS.STATE_PROVINCE AS ADDRESS_STATE_PROVINCE,
		ADDRESS.COUNTRY AS ADDRESS_COUNTRY,
		ADDRESS.POSTAL_CODE AS ADDRESS_POSTAL_CODE,
		ADDRESS.RECEIVE_CORRESPONDENCE AS ADDRESS_RECEIVE_CORRESPONDENCE,
		ADDRESS.COMMENT AS ADDRESS_COMMENT,
		ADDRESS.SEASONAL_END_DATE AS ADDRESS_SEASONAL_END_DATE,
		ADDRESS.SEASONAL_START_DATE AS ADDRESS_SEASONAL_START_DATE,
		ADDRESS.TEMPORARY_END_DATE AS ADDRESS_TEMPORARY_END_DATE,
		ADDRESS.TEMPORARY_START_DATE AS ADDRESS_TEMPORARY_START_DATE,
		ADDRESS.CREATE_DATE AS ADDRESS_CREATE_DATE,
		ADDRESS.UPDATE_DATE AS ADDRESS_UPDATE_DATE,
		ADDRESS.INACTIVE AS ADDRESS_INACTIVE
	FROM VW_AUDITHISTORY
	LEFT JOIN ADDRESS ON VW_AUDITHISTORY.AUDIT_OBJECT_ID = ADDRESS.ADDRESS_ID
	LEFT JOIN CUSTOM_FIELD ADDRESS_TYPE ON ADDRESS_TYPE.ENTITY_TYPE = 'address' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = 'addressType'
	LEFT JOIN PICKLIST AS ADDRESS_TYPE_PICKLIST ON ADDRESS_TYPE_PICKLIST.PICKLIST_NAME_ID = 'customFieldMap[addressType]'
	LEFT JOIN PICKLIST_ITEM AS ADDRESS_TYPE_PICKLISTITEMS ON ADDRESS_TYPE_PICKLISTITEMS.PICKLIST_ID = ADDRESS_TYPE_PICKLIST.PICKLIST_ID AND ADDRESS_TYPE_PICKLISTITEMS.ITEM_NAME = ADDRESS_TYPE.FIELD_VALUE
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'address'
;


-- *********************************************************************************************************************
--
-- Constituents Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_CONSTITUENTS;
CREATE VIEW VW_AUDITHISTORY_CONSTITUENTS
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID,
 		VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ROLE,
		VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_TYPE,
		VW_CONSTITUENTS.CONSTITUENT_CREATE_DATE,
		VW_CONSTITUENTS.CONSTITUENT_FIRST_NAME,
 		VW_CONSTITUENTS.CONSTITUENT_DONOR_PROFILE,
		VW_CONSTITUENTS.CONSTITUENT_LAST_NAME,
		VW_CONSTITUENTS.CONSTITUENT_LEGAL_NAME,
		VW_CONSTITUENTS.CONSTITUENT_LOGIN_ID,
		VW_CONSTITUENTS.CONSTITUENT_MARITAL_STATUS,
		VW_CONSTITUENTS.CONSTITUENT_MIDDLE_NAME,
		VW_CONSTITUENTS.CONSTITUENT_NCAIS_CODE,
		VW_CONSTITUENTS.CONSTITUENT_ORGANIZATION_NAME,
		VW_CONSTITUENTS.CONSTITUENT_PREFERRED_PHONE_TYPE,
		VW_CONSTITUENTS.CONSTITUENT_RECOGNITION_NAME,
		VW_CONSTITUENTS.CONSTITUENT_SUFFIX,
		VW_CONSTITUENTS.CONSTITUENT_TITLE,
		VW_CONSTITUENTS.CONSTITUENT_UPDATE_DATE,
		VW_CONSTITUENTS.CONSTITUENT_SITE_NAME
	FROM VW_AUDITHISTORY
	LEFT JOIN VW_CONSTITUENTS ON VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_AUDITHISTORY.AUDIT_OBJECT_ID
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'CONSTITUENT'
;


-- *********************************************************************************************************************
--
-- Email Addresses Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_EMAILADDRESSES;
CREATE VIEW VW_AUDITHISTORY_EMAILADDRESSES
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		-- Email Information
		EMAIL.EMAIL_ID AS EMAIL_EMAIL_ID,
		EMAIL.CONSTITUENT_ID AS EMAIL_CONSTITUENT_ID,
		EMAIL_TYPES_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS EMAIL_EMAIL_TYPE,
		EMAIL.ACTIVATION_STATUS AS EMAIL_ACTIVATION_STATUS,
		EMAIL.EFFECTIVE_DATE AS EMAIL_EFFECTIVE_DATE,
		EMAIL.SEASONAL_START_DATE AS EMAIL_SEASONAL_START_DATE,
		EMAIL.SEASONAL_END_DATE AS EMAIL_SEASONAL_END_DATE,
		EMAIL.TEMPORARY_START_DATE AS EMAIL_TEMPORARY_START_DATE,
		EMAIL.TEMPORARY_END_DATE AS EMAIL_TEMPORARY_END_DATE,
		EMAIL.EMAIL_ADDRESS AS EMAIL_EMAIL_ADDRESS,
		EMAIL.EMAIL_DISPLAY AS EMAIL_EMAIL_DISPLAY,
		EMAIL.RECEIVE_CORRESPONDENCE AS EMAIL_RECEIVE_CORRESPONDENCE,
		EMAIL.COMMENT AS EMAIL_COMMENT,
		EMAIL.CREATE_DATE AS EMAIL_CREATE_DATE,
		EMAIL.UPDATE_DATE AS EMAIL_UPDATE_DATE,
		EMAIL.INACTIVE AS EMAIL_INACTIVE
	FROM VW_AUDITHISTORY
	LEFT JOIN EMAIL ON VW_AUDITHISTORY.AUDIT_OBJECT_ID = EMAIL.EMAIL_ID
	LEFT JOIN CUSTOM_FIELD AS EMAIL_TYPES ON EMAIL_TYPES.ENTITY_TYPE = 'email' AND EMAIL_TYPES.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPES.FIELD_NAME = 'emailType'
	LEFT JOIN PICKLIST AS EMAIL_TYPES_PICKLIST ON EMAIL_TYPES_PICKLIST.PICKLIST_NAME_ID = 'customFieldMap[emailType]'
	LEFT JOIN PICKLIST_ITEM AS EMAIL_TYPES_PICKLISTITEMS ON EMAIL_TYPES_PICKLISTITEMS.PICKLIST_ID = EMAIL_TYPES_PICKLIST.PICKLIST_ID AND EMAIL_TYPES_PICKLISTITEMS.ITEM_NAME = EMAIL_TYPES.FIELD_VALUE
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'email'
;


-- *********************************************************************************************************************
--
-- Gift Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_GIFTS;
CREATE VIEW VW_AUDITHISTORY_GIFTS
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		GIFT_CONSTITUENT_ID,
		GIFT_GIFT_ID,
		GIFT_AMOUNT,
		GIFT_CURRENCY_CODE,
		GIFT_DONATION_DATE,
		GIFT_POSTMARK_DATE,
		GIFT_COMMENTS,
		GIFT_TRANSACTIONDATE,
		GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		GIFT_PAYMENT_TYPE,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		GIFT_CHECK_NUMBER,
		GIFT_AUTH_CODE,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		GIFT_PAYMENT_ADDRESS_CITY,
		GIFT_PAYMENT_ADDRESS_STATE_PROVINCE,
		GIFT_PAYMENT_ADDRESS_POSTAL_CODE,
		GIFT_PAYMENT_ADDRESS_COUNTRY,
		GIFT_PAYMENT_PHONE_NUMBER
	FROM VW_AUDITHISTORY
	LEFT JOIN VW_GIFTS ON VW_AUDITHISTORY.AUDIT_OBJECT_ID = VW_GIFTS.GIFT_GIFT_ID
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'gift'
;


-- *********************************************************************************************************************
--
-- Payment Method Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_PAYMENTMETHODS;
CREATE VIEW VW_AUDITHISTORY_PAYMENTMETHODS
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		PAYMENT_SOURCE_PAYMENT_SOURCE_ID,
		PAYMENT_SOURCE_CONSTITUENT_ID,
		PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		PAYMENT_SOURCE_PAYMENT_TYPE,
		PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		PAYMENT_SOURCE_ACH_HOLDER_NAME,
		PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		PAYMENT_SOURCE_ADDRESS_ADDRESS_LINE_1,
		PAYMENT_SOURCE_ADDRESS_ADDRESS_LINE_2,
		PAYMENT_SOURCE_ADDRESS_ADDRESS_LINE_3,
		PAYMENT_SOURCE_ADDRESS_CITY,
		PAYMENT_SOURCE_ADDRESS_STATE_PROVINCE,
		PAYMENT_SOURCE_ADDRESS_POSTAL_CODE,
		PAYMENT_SOURCE_ADDRESS_COUNTRY,
		PAYMENT_SOURCE_PHONE_NUMBER
	FROM VW_AUDITHISTORY
	LEFT JOIN VW_PAYMENTMETHODS ON VW_AUDITHISTORY.AUDIT_OBJECT_ID = VW_PAYMENTMETHODS.PAYMENT_SOURCE_PAYMENT_SOURCE_ID
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'paymentsource'
;



-- *********************************************************************************************************************
--
-- Phone Number Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_PHONENUMBERS;
CREATE VIEW VW_AUDITHISTORY_PHONENUMBERS
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		-- Phone Number Information
		PHONE.PHONE_ID AS PHONE_PHONE_ID,
		PHONE.CONSTITUENT_ID AS PHONE_CONSTITUENT_ID,
 		PHONE_TYPES_PICKLISTITEMS.DEFAULT_DISPLAY_VALUE AS PHONE_PHONE_TYPE,
		PHONE.ACTIVATION_STATUS AS PHONE_ACTIVATION_STATUS,
		PHONE.EFFECTIVE_DATE AS PHONE_EFFECTIVE_DATE,
		PHONE.SEASONAL_START_DATE AS PHONE_SEASONAL_START_DATE,
		PHONE.SEASONAL_END_DATE AS PHONE_SEASONAL_END_DATE,
		PHONE.TEMPORARY_START_DATE AS PHONE_TEMPORARY_START_DATE,
		PHONE.TEMPORARY_END_DATE AS PHONE_TEMPORARY_END_DATE,
		PHONE.NUMBER AS PHONE_NUMBER,
		PHONE.PROVIDER AS PHONE_PROVIDER,
		PHONE.SMS AS PHONE_SMS,
		PHONE.RECEIVE_CORRESPONDENCE AS PHONE_RECEIVE_CORRESPONDENCE,
		PHONE.COMMENT AS PHONE_COMMENT,
		PHONE.CREATE_DATE AS PHONE_CREATE_DATE,
		PHONE.UPDATE_DATE AS PHONE_UPDATE_DATE,
		PHONE.INACTIVE AS PHONE_INACTIVE
	FROM VW_AUDITHISTORY
	LEFT JOIN PHONE ON VW_AUDITHISTORY.AUDIT_OBJECT_ID = PHONE.PHONE_ID
	LEFT JOIN CUSTOM_FIELD AS PHONE_TYPES ON PHONE_TYPES.ENTITY_TYPE = 'phone' AND PHONE_TYPES.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPES.FIELD_NAME = 'phoneType'
	LEFT JOIN PICKLIST AS PHONE_TYPES_PICKLIST ON PHONE_TYPES_PICKLIST.PICKLIST_NAME_ID = 'customFieldMap[phoneType]'
	LEFT JOIN PICKLIST_ITEM AS PHONE_TYPES_PICKLISTITEMS ON PHONE_TYPES_PICKLISTITEMS.PICKLIST_ID = PHONE_TYPES_PICKLIST.PICKLIST_ID AND PHONE_TYPES_PICKLISTITEMS.ITEM_NAME = PHONE_TYPES.FIELD_VALUE
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'phone'
;


-- *********************************************************************************************************************
--
-- Pledge Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_PLEDGES;
CREATE VIEW VW_AUDITHISTORY_PLEDGES
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		-- Pledge Number Information
		COMMITMENT_CONSTITUENT_ID,
		COMMITMENT_COMMITMENT_ID,
		COMMITMENT_RECURRING,
		COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT_CURRENCY_CODE,
		COMMITMENT_STATUS,
		COMMITMENT_FREQUENCY,
		COMMITMENT_PLEDGE_DATE,
		COMMITMENT_PROJECTED_DATE,
		COMMITMENT_START_DATE,
		COMMITMENT_END_DATE,
		COMMITMENT_COMMENTS
	FROM VW_AUDITHISTORY
	LEFT JOIN VW_PLEDGES ON VW_AUDITHISTORY.AUDIT_OBJECT_ID = VW_PLEDGES.COMMITMENT_COMMITMENT_ID
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'pledge'
;



-- *********************************************************************************************************************
--
-- Recurring Gift Audit History View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_AUDITHISTORY_RECURRINGGIFTS;
CREATE VIEW VW_AUDITHISTORY_RECURRINGGIFTS
AS
	SELECT
		VW_AUDITHISTORY.AUDIT_AUDIT_ID,
		VW_AUDITHISTORY.AUDIT_DATE,
		VW_AUDITHISTORY.AUDIT_USER,
		VW_AUDITHISTORY.AUDIT_AUDIT_TYPE,
		VW_AUDITHISTORY.AUDIT_DESCRIPTION,
		VW_AUDITHISTORY.AUDIT_ENTITY_TYPE,
		VW_AUDITHISTORY.AUDIT_OBJECT_ID,
		VW_AUDITHISTORY.AUDIT_CONSTITUENT_ID,
		VW_AUDITHISTORY.AUDIT_SITE_NAME,

		-- Recurring Gift Information
		COMMITMENT_COMMITMENT_ID,
		COMMITMENT_CONSTITUENT_ID,
		COMMITMENT_AUTO_PAY,
		COMMITMENT_AMOUNT_PER_GIFT,
		COMMITMENT_AMOUNT_TOTAL,
		COMMITMENT_CURRENCY_CODE,
		COMMITMENT_FREQUENCY,
		COMMITMENT_START_DATE,
		COMMITMENT_END_DATE,
		COMMITMENT_STATUS,
		COMMITMENT_COMMENTS,
		COMMITMENT_LAST_ENTRY_DATE,
		COMMITMENT_CREATE_DATE,
		COMMITMENT_UPDATE_DATE,
		COMMITMENT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION,
		COMMITMENT_PAYMENT_TYPE,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_TYPE,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION,
		COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE,
		COMMITMENT_PAYMENT_SOURCE_ACH_HOLDER_NAME,
		COMMITMENT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER,
		COMMITMENT_CHECK_NUMBER,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_1,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_2,
		COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_3,
		COMMITMENT_PAYMENT_ADDRESS_CITY,
		COMMITMENT_PAYMENT_ADDRESS_STATE_PROVINCE,
		COMMITMENT_PAYMENT_ADDRESS_POSTAL_CODE,
		COMMITMENT_PAYMENT_ADDRESS_COUNTRY,
		COMMITMENT_PAYMENT_PHONE_NUMBER
	FROM VW_AUDITHISTORY
	LEFT JOIN VW_RECURRINGGIFTS ON VW_AUDITHISTORY.AUDIT_OBJECT_ID = VW_RECURRINGGIFTS.COMMITMENT_COMMITMENT_ID
	WHERE VW_AUDITHISTORY.AUDIT_ENTITY_TYPE = 'recurring gift'
;


-- *********************************************************************************************************************
--
-- Journals View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_JOURNALS;
CREATE VIEW VW_JOURNALS
AS
	SELECT
		COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID AS COMMUNICATION_HISTORY_COMMUNICATION_HISTORY_ID,
		COMMUNICATION_HISTORY.COMMUNICATION_TYPE AS COMMUNICATION_HISTORY_COMMUNICATION_TYPE,
		COMMUNICATION_HISTORY.RECORD_DATE AS COMMUNICATION_HISTORY_RECORD_DATE,
		COMMUNICATION_HISTORY.COMMENTS AS COMMUNICATION_HISTORY_COMMENTS,
		COMMUNICATION_HISTORY.SYSTEM_GENERATED AS COMMUNICATION_HISTORY_SYSTEM_GENERATED,
		COMMUNICATION_HISTORY.CREATE_DATE AS COMMUNICATION_HISTORY_CREATE_DATE,
		COMMUNICATION_HISTORY.UPDATE_DATE AS COMMUNICATION_HISTORY_UPDATE_DATE,
		COMMUNICATION_HISTORY.CONSTITUENT_ID AS COMMUNICATION_HISTORY_CONSTITUENT_ID,
		GETCUSTOMFIELD(COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID, 'communicationhistory', 'assignedTo') AS COMMUNICATION_HISTORY_ASSIGNED_TO,
		GETCUSTOMFIELD(COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID, 'communicationhistory', 'recordedBy') AS COMMUNICATION_HISTORY_RECORDED_BY
	FROM COMMUNICATION_HISTORY
;


-- *********************************************************************************************************************
--
-- Journals & Constituents View
--
-- *********************************************************************************************************************
DROP VIEW IF EXISTS VW_JOURNALS_CONSTITUENTS;
CREATE VIEW VW_JOURNALS_CONSTITUENTS
AS
	SELECT
		COMMUNICATION_HISTORY_COMMUNICATION_HISTORY_ID,
		COMMUNICATION_HISTORY_COMMUNICATION_TYPE,
		COMMUNICATION_HISTORY_RECORD_DATE,
		COMMUNICATION_HISTORY_COMMENTS,
		COMMUNICATION_HISTORY_SYSTEM_GENERATED,
		COMMUNICATION_HISTORY_CREATE_DATE,
		COMMUNICATION_HISTORY_UPDATE_DATE,
		COMMUNICATION_HISTORY_CONSTITUENT_ID,
		GETCUSTOMFIELD(COMMUNICATION_HISTORY_COMMUNICATION_HISTORY_ID, 'communicationhistory', 'assignedTo') AS COMMUNICATION_HISTORY_ASSIGNED_TO,
		GETCUSTOMFIELD(COMMUNICATION_HISTORY_COMMUNICATION_HISTORY_ID, 'communicationhistory', 'recordedBy') AS COMMUNICATION_HISTORY_RECORDED_BY,

		-- Constituent Information
		VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID,
 		VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ROLE,
		VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_TYPE,
		VW_CONSTITUENTS.CONSTITUENT_CREATE_DATE,
		VW_CONSTITUENTS.CONSTITUENT_FIRST_NAME,
 		VW_CONSTITUENTS.CONSTITUENT_DONOR_PROFILE,
		VW_CONSTITUENTS.CONSTITUENT_LAST_NAME,
		VW_CONSTITUENTS.CONSTITUENT_LEGAL_NAME,
		VW_CONSTITUENTS.CONSTITUENT_LOGIN_ID,
		VW_CONSTITUENTS.CONSTITUENT_MARITAL_STATUS,
		VW_CONSTITUENTS.CONSTITUENT_MIDDLE_NAME,
		VW_CONSTITUENTS.CONSTITUENT_NCAIS_CODE,
		VW_CONSTITUENTS.CONSTITUENT_ORGANIZATION_NAME,
		VW_CONSTITUENTS.CONSTITUENT_PREFERRED_PHONE_TYPE,
		VW_CONSTITUENTS.CONSTITUENT_RECOGNITION_NAME,
		VW_CONSTITUENTS.CONSTITUENT_SUFFIX,
		VW_CONSTITUENTS.CONSTITUENT_TITLE,
		VW_CONSTITUENTS.CONSTITUENT_UPDATE_DATE,
		VW_CONSTITUENTS.CONSTITUENT_SITE_NAME
	FROM VW_JOURNALS
	LEFT JOIN VW_CONSTITUENTS ON VW_JOURNALS.COMMUNICATION_HISTORY_CONSTITUENT_ID = VW_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID
;