-- CLEMENTINE-363 - Change View_Name in ReportDataSubsource to 8000 characters
ALTER TABLE REPORTDATASUBSOURCE MODIFY COLUMN VIEW_NAME VARCHAR(8000) DEFAULT NULL;

-- TANGERINE-1066 - Correct Gift Status column definition
UPDATE REPORTFIELD SET COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''giftStatus'', GIFT_GIFT_STATUS)' WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''giftStatus'', GIFT_GIFT_STATUS),';