--
-- Definition of function `COUNTOFVALUES`
--

DROP FUNCTION IF EXISTS `COUNTOFVALUES`;

--
-- Definition of function `GETCONSTITUENTDISPLAYNAME`
--

DROP FUNCTION IF EXISTS `GETCONSTITUENTDISPLAYNAME`;

--
-- Definition of function `GETCONSTITUENTDISPLAYNAMES`
--

DROP FUNCTION IF EXISTS `GETCONSTITUENTDISPLAYNAMES`;

--
-- Definition of function `GETCUSTOMFIELD`
--

DROP FUNCTION IF EXISTS `GETCUSTOMFIELD`;

--
-- Definition of function `GETVALUE`
--

DROP FUNCTION IF EXISTS `GETVALUE`;

--
-- Definition of function `SPLITCAMELCASEDSTRING`
--

DROP FUNCTION IF EXISTS `SPLITCAMELCASEDSTRING`;

--
-- Definition of procedure `ASSOCIATECUSTOMFILTERSWITHDATASUBSOURCES`
--

DROP PROCEDURE IF EXISTS `ASSOCIATECUSTOMFILTERSWITHDATASUBSOURCES`;

--
-- Definition of procedure `INSERTREPORTFIELD`
--

DROP PROCEDURE IF EXISTS `INSERTREPORTFIELD`;

--
-- Definition of procedure `INSERTREPORTFIELDGROUP`
--

DROP PROCEDURE IF EXISTS `INSERTREPORTFIELDGROUP`;

--
-- Definition of procedure `INSERTREPORTFIELDWITHALIAS`
--

DROP PROCEDURE IF EXISTS `INSERTREPORTFIELDWITHALIAS`;

--
-- Definition of procedure `NUMBERBUILDER`
--

DROP PROCEDURE IF EXISTS `NUMBERBUILDER`;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
