INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
WHERE REPORTCUSTOMFILTERDEFINITION_ID = 600000
AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
	(SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
	 WHERE REPORTFIELD_ID IN
		(SELECT REPORTFIELD_ID FROM REPORTFIELD
    	 WHERE COLUMN_NAME = 'CONSTITUENT_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%CONSTITUENT_CONSTITUENT_ID%'))
AND NOT EXISTS
	(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
	 WHERE reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 600000
	 AND REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTFIELDGROUP_REPORTDATASUBSOURCE.REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID
	 AND REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID = REPORTFIELDGROUP_REPORTDATASUBSOURCE.REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID);
