DELIMITER $$

DROP PROCEDURE IF EXISTS ADDCOLUMN_UPDATESCRIPT$$

CREATE PROCEDURE ADDCOLUMN_UPDATESCRIPT() BEGIN
	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='USE_REPORT_AS_SEGMENTATION' AND TABLE_NAME='REPORTWIZARD' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTWIZARD
		ADD COLUMN USE_REPORT_AS_SEGMENTATION BIT(1) DEFAULT b'0';
	END IF;
END;
$$

DELIMITER ;

CALL ADDCOLUMN_UPDATESCRIPT();

DROP PROCEDURE ADDCOLUMN_UPDATESCRIPT;
