CREATE TABLE IF NOT EXISTS `VERSIONLOG` (
  `VERSION_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SCRIPT` VARCHAR(255) NOT NULL,
  `INSTALLDATE` DATETIME NOT NULL,
  PRIMARY KEY (`VERSION_ID`)
)
ENGINE = InnoDB;