DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS(COLUMNNAMEVAR VARCHAR(100), SEGMENTATIONTYPEVAR VARCHAR(100))
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTSEGMENTATIONTYPE
		WHERE COLUMN_NAME = COLUMNNAMEVAR
		AND SEGMENTATIONTYPE = SEGMENTATIONTYPEVAR)
	THEN
		INSERT REPORTSEGMENTATIONTYPE
		  (COLUMN_NAME, SEGMENTATIONTYPE)
		SELECT
		  COLUMNNAMEVAR, SEGMENTATIONTYPEVAR;

		SET @REPORTSEGMENTATIONTYPEID = LAST_INSERT_ID();

		INSERT REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE
		  (reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTSEGMENTATIONTYPE_ID)

		SELECT DISTINCT
 		  @REPORTSEGMENTATIONTYPEID, REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID, @REPORTSEGMENTATIONTYPEID
		FROM REPORTDATASUBSOURCE
		WHERE REPORTDATASUBSOURCE.VIEW_NAME IN ('VW_GIFTS_DISTRIBUTIONS', 'VW_CONSTITUENTS_GIFTDISTRIBUTIONS', 'VW_CONSTITUENTS_RELATIONSHIPS_GIFTDISTRIBUTIONS');
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS('DISTRO_LINE_DISTRO_LINE_ID', 'Gift Distribution Segmentation');

DROP PROCEDURE ADDREPORTFIELDS;