DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS()
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 630000)
	THEN
		-- Gift is in a segmentation
		INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
		SELECT 630000, 'Segmentation - Gift Adjustment is in segmentation / report',
		'EXISTS (SELECT * FROM THEGURU_SEGMENTATION_RESULT SEGTABLE WHERE SEGTABLE.REPORT_ID = {0} AND SEGTABLE.ENTITY_ID = [VIEWNAME].ADJUSTED_GIFT_ADJUSTED_GIFT_ID)',
		'Segmentation - Gift Adjustment is in segmentation / report <br> {lookupReferenceBean:orangeLeapAdjustedGiftSegmentationList}';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 630000
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'ADJUSTED_GIFT_ADJUSTED_GIFT_ID'));
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS();

DROP PROCEDURE ADDREPORTFIELDS;


DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS()
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 630001)
	THEN
		-- Gift is in a segmentation
		INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
		SELECT 630001, 'Segmentation - Gift Adjustment is in segmentation / report',
		'EXISTS (SELECT * FROM THEGURU_SEGMENTATION_RESULT SEGTABLE WHERE SEGTABLE.REPORT_ID = {0} AND SEGTABLE.ENTITY_ID = [VIEWNAME].VW_AGD_ADJUSTED_GIFT_ADJUSTED_GIFT_ID)',
		'Segmentation - Gift Adjustment is in segmentation / report <br> {lookupReferenceBean:orangeLeapAdjustedGiftSegmentationList}';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 630001
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'VW_AGD_ADJUSTED_GIFT_ADJUSTED_GIFT_ID'));
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS();

DROP PROCEDURE ADDREPORTFIELDS;


