DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS()
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500000)
	THEN
    -- Account Gift Total - tied to ADDRESS_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500000, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].ADDRESS_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500000
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'ADDRESS_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%ADDRESS_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500100)
	THEN
    -- Account Gift Total - tied to AUDIT_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500100, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].AUDIT_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500100
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'AUDIT_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%AUDIT_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500200)
	THEN
    -- Account Gift Total - tied to COMMITMENT_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500200, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].COMMITMENT_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500200
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'COMMITMENT_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%COMMITMENT_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500300)
	THEN
    -- Account Gift Total - tied to COMMUNICATION_HISTORY_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500300, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].COMMUNICATION_HISTORY_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500300
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'COMMUNICATION_HISTORY_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%COMMUNICATION_HISTORY_CONSTITUENT_ID%'));
	END IF;

-- START HERE
	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500400)
	THEN
    -- Account Gift Total - tied to EMAIL_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500400, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].EMAIL_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500400
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'EMAIL_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%EMAIL_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500500)
	THEN
    -- Account Gift Total - tied to GIFT_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500500, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].GIFT_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500500
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'GIFT_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%GIFT_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500600)
	THEN
    -- Account Gift Total - tied to PAYMENT_HISTORY_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500600, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].PAYMENT_HISTORY_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500600
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'PAYMENT_HISTORY_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%PAYMENT_HISTORY_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500700)
	THEN
    -- Account Gift Total - tied to PAYMENT_SOURCE_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500700, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].PAYMENT_SOURCE_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500700
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'PAYMENT_SOURCE_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%PAYMENT_SOURCE_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500800)
	THEN
    -- Account Gift Total - tied to CONSTITUENT_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500800, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].CONSTITUENT_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500800
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'CONSTITUENT_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%CONSTITUENT_CONSTITUENT_ID%'));
	END IF;


	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500900)
	THEN
    -- Account Gift Total - tied to PHONE_CONSTITUENT_ID
    INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
    SELECT 500900, 'Gift Totals - Account gave at least $[GIFTAMOUNT] in hard gifts between [GIFTDATE] and [GIFTDATE]',
    '((SELECT SUM(AMOUNT) FROM GIFT GIFTLOOKUP WHERE GIFTLOOKUP.CONSTITUENT_ID = [VIEWNAME].PHONE_CONSTITUENT_ID AND CAST(GIFTLOOKUP.DONATION_DATE AS DATE) BETWEEN CAST(CONCAT(SUBSTRING_INDEX(''{1}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{1}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{1}'',''/'',2),''/'',-1)) AS DATE) AND CAST(CONCAT(SUBSTRING_INDEX(''{2}'',''/'',-1), ''-'', SUBSTRING_INDEX(''{2}'',''/'',1), ''-'', SUBSTRING_INDEX(SUBSTRING_INDEX(''{2}'',''/'',2),''/'',-1)) AS DATE)) >= {0})',
    'Gift Totals - Account gave at least <span class="criteriaWrapper">$<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}" style="width:100px" fieldtype="MONEY" /></span> in hard gifts <br>between <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" fieldtype="DATE" value="''{1}''" style="width:110px"/></span> and <span class="criteriaWrapper"><input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" fieldtype="DATE" value="''{2}''" style="width:110px"/></span>';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 500900
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'PHONE_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%PHONE_CONSTITUENT_ID%'));
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS();

DROP PROCEDURE ADDREPORTFIELDS;