DELIMITER $$

DROP PROCEDURE IF EXISTS ADDCOLUMN_UPDATESCRIPT$$

CREATE PROCEDURE ADDCOLUMN_UPDATESCRIPT() BEGIN
	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='SEGMENTATION_QUERY' AND TABLE_NAME='REPORTWIZARD' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTWIZARD
		ADD COLUMN SEGMENTATION_QUERY TEXT;
	END IF;
END;
$$

DELIMITER ;

CALL ADDCOLUMN_UPDATESCRIPT();

DROP PROCEDURE ADDCOLUMN_UPDATESCRIPT;
