-- This is the same script as 20090903_11_DU_ReportCustomFilterDefinition_ReportDataSubSource.sql
-- The records inserted from the first script were truncated and this needs to run again
DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS()
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 600000)
	THEN
		-- Account is in a segmentation
		INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
		SELECT 600000, 'Segmentation - Account is in segmentation / report',
		'EXISTS (SELECT * FROM THEGURU_SEGMENTATION_RESULT SEGTABLE WHERE SEGTABLE.REPORT_ID = {0} AND SEGTABLE.ENTITY_ID = [VIEWNAME].CONSTITUENT_CONSTITUENT_ID)',
		'Segmentation - Account is in segmentation / report <br> {lookupReferenceBean:orangeLeapConstituentSegmentationList}';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 600000
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'CONSTITUENT_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%CONSTITUENT_CONSTITUENT_ID%'));
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS();

DROP PROCEDURE ADDREPORTFIELDS;



DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS()
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 610000)
	THEN
		-- Gift is in a segmentation
		INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
		SELECT 610000, 'Segmentation - Gift is in segmentation / report',
		'EXISTS (SELECT * FROM THEGURU_SEGMENTATION_RESULT SEGTABLE WHERE SEGTABLE.REPORT_ID = {0} AND SEGTABLE.ENTITY_ID = [VIEWNAME].GIFT_GIFT_ID)',
		'Segmentation - Gift is in segmentation / report <br> {lookupReferenceBean:orangeLeapGiftSegmentationList}';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 610000
		AND REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN
		  (SELECT REPORTFIELDGROUP_ID FROM REPORTFIELD_REPORTFIELDGROUP
		  WHERE REPORTFIELD_ID IN
		    (SELECT REPORTFIELD_ID FROM REPORTFIELD
		    WHERE COLUMN_NAME = 'GIFT_GIFT_ID' OR PRIMARY_KEYS LIKE '%GIFT_GIFT_ID%'));
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS();

DROP PROCEDURE ADDREPORTFIELDS;