DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS(VIEWNAME VARCHAR(100))
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTFIELD
		JOIN REPORTFIELD_REPORTFIELDGROUP ON REPORTFIELD_REPORTFIELDGROUP.fields_REPORTFIELD_ID = REPORTFIELD.REPORTFIELD_ID
		JOIN REPORTFIELDGROUP_REPORTDATASUBSOURCE ON REPORTFIELDGROUP_REPORTDATASUBSOURCE.REPORTFIELDGROUP_REPORTFIELDGROUP_ID = REPORTFIELD_REPORTFIELDGROUP.reportFieldGroup_REPORTFIELDGROUP_ID
		WHERE COLUMN_NAME = 'ADDRESS_CURRENT_ADDRESS_ID'
		AND reportDataSubSource_REPORTSUBSOURCE_ID = (SELECT MAX(REPORTSUBSOURCE_ID) FROM REPORTDATASUBSOURCE WHERE VIEW_NAME = VIEWNAME))
	THEN
		SET @REPORTSUBSOURCE_ID = (SELECT MAX(REPORTSUBSOURCE_ID) FROM REPORTDATASUBSOURCE WHERE VIEW_NAME = VIEWNAME);

		-- ***********************************************************************
		-- Current Address Information Field Group
		-- ***********************************************************************
		CALL INSERTREPORTFIELDGROUP('Current Address Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

		-- Address ID
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_ID', 'Address ID', b'0', 2, @REPORTFIELDGROUP_ID);

		-- Address Type
		CALL INSERTREPORTFIELDWITHALIAS('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_TYPE', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(ADDRESS_CURRENT_ADDRESS_ID, ''address'', ''addressType'', ''customFieldMap[addressType]'')', 'Address Type', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Address Status
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ACTIVATION_STATUS', 'Address Status', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Effective Date
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_EFFECTIVE_DATE', 'Address Effective Date', b'0', 4, @REPORTFIELDGROUP_ID);

		-- Seasonal Start Date
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_SEASONAL_START_DATE_DISPLAY', 'Seasonal Start Date', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Seasonal End Date
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_SEASONAL_END_DATE_DISPLAY', 'Seasonal End Date', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Temporary Start Date
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_TEMPORARY_START_DATE', 'Temporary Start Date', b'0', 4, @REPORTFIELDGROUP_ID);

		-- Temporary End Date
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_TEMPORARY_END_DATE', 'Temporary End Date', b'0', 4, @REPORTFIELDGROUP_ID);

		-- Address Line 1
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_LINE_1', 'Address Line 1', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Address Line 2
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_LINE_2', 'Address Line 2', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Address Line 3
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_LINE_3', 'Address Line 3', b'0', 1, @REPORTFIELDGROUP_ID);

		-- City
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_CITY', 'City', b'0', 1, @REPORTFIELDGROUP_ID);

		-- State/Province
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_STATE_PROVINCE', 'State/Province', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Country
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_COUNTRY', 'Country', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Zip/Postal Code
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_POSTAL_CODE', 'Zip/Postal Code', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Receive Correspondence
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_RECEIVE_CORRESPONDENCE', 'Receive Correspondence', b'0', 6, @REPORTFIELDGROUP_ID);

		-- Comments
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_COMMENT', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);

		-- Address Create Date
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_CREATE_DATE', 'Address Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

		-- Address Update Date
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_UPDATE_DATE', 'Address Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

		-- Primary Address
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_IS_PRIMARY', 'Primary Address', b'0', 6, @REPORTFIELDGROUP_ID);

		-- Address Undeliverable
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_UNDELIVERABLE', 'Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);

		-- Address Inactive
		CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_INACTIVE', 'Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS('VW_CONSTITUENTS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_ADDRESSES');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_CONTACTINFORMATION');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_RELATIONSHIPS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_GIFTS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_GIFTDISTRIBUTIONS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_GIFTS_IN_KIND');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_GIFTS_IN_KIND_DETAILS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_PAYMENTHISTORY');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_PAYMENTMETHODS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_PLEDGES');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_PLEDGES_DISTRIBUTIONS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_RECURRINGGIFTS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_RELATIONSHIPS_GIFTS');
CALL ADDREPORTFIELDS('VW_CONSTITUENTS_RELATIONSHIPS_GIFTDISTRIBUTIONS');
CALL ADDREPORTFIELDS('VW_AUDITHISTORY_CONSTITUENTS');
CALL ADDREPORTFIELDS('VW_TOUCHPOINTS_CONSTITUENT_INFORMATION');

DROP PROCEDURE ADDREPORTFIELDS;
