DELIMITER $$

DROP PROCEDURE IF EXISTS `INSERTCONSTITUENTSRELATIONSHIPDETAILS_UPDATESCRIPT`$$

CREATE PROCEDURE INSERTCONSTITUENTSRELATIONSHIPDETAILS_UPDATESCRIPT()
BEGIN
  IF NOT EXISTS
    (SELECT * FROM REPORTDATASUBSOURCE
    WHERE VIEW_NAME = 'VW_CONSTITUENTS_RELATIONSHIP_DETAILS')
  THEN
    SET @REPORTDATASUBSOURCEGROUP_ID = (SELECT MAX(REPORTSUBSOURCEGROUP_ID) FROM REPORTDATASUBSOURCEGROUP WHERE DISPLAY_NAME = 'Constituents');

    INSERT INTO REPORTDATASUBSOURCE
      (DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME)
    VALUES
      ('Constituents & Relationship Details', 0, 'VW_CONSTITUENTS_RELATIONSHIP_DETAILS', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults');

    SET @REPORTSUBSOURCE_ID = LAST_INSERT_ID();


    -- ***********************************************************************
    -- Contact Details Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Contact Details', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Account Number
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_ACCOUNT_NUMBER', 'Account Number', b'0', 2, @REPORTFIELDGROUP_ID);

    -- Account Manager Name
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ACCOUNTMANAGER', 'GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''accountManager''))', 'Account Manager Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Account Manager Account Number
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ACCOUNTMANAGERACCOUNTNUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''accountManager''))', 'Account Manager Account Number', b'0', 2, @REPORTFIELDGROUP_ID);

    -- Constituent Type
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_CONSTITUENT_TYPE', 'Constituent Type', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Profile Type
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_CONSTITUENT_ROLE', 'Profile Type', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Donor Profile
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_DONOR_PROFILE', 'Donor Profile', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Title
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_TITLE', 'Title', b'0', 1, @REPORTFIELDGROUP_ID);

    -- First Name
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_FIRST_NAME', 'First Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Middle Name
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_MIDDLE_NAME', 'Middle Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Last Name
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_LAST_NAME', 'Last Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Suffix
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_SUFFIX', 'Suffix', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Recognition Name
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_RECOGNITION_NAME', 'Recognition Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Formal Saluation
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_FORMAL_SALUTATION', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''formalSalutation'')', 'Formal Salutation', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Informal Salutation
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_INFORMAL_SALUTATION', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''informalSalutation'')', 'Informal Salutation', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Head of Household Salutation
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_HEADOFHOUSEHOLD_SALUTATION', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''headOfHouseholdSalutation'')', 'Head of Household Salutation', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Organization Name
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_ORGANIZATION_NAME', 'Organization Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Legal Name
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_LEGAL_NAME', 'Legal Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Website
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_WEBSITE', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.website'')', 'Website', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Tax ID
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_TAXID', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.taxid'')', 'Tax ID', b'0', 1, @REPORTFIELDGROUP_ID);

    -- NAICS Code
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_NAICS_CODE', 'NAICS Code', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Communication Preferences
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'COMMUNICATIONPREFERENCES', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''communicationPreferences'')', 'Communication Preferences', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Opt In Preferences
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_OPT_IN_PREFERENCES', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''communicationOptInPreferences'', ''customFieldMap[communicationOptInPreferences]'')', 'Opt In Preferences', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Email Format
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'EMAILFORMAT', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''emailFormat'')', 'Email Format', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Login ID
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_LOGIN_ID', 'Login ID', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Create Date
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_CREATE_DATE', 'Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Update Date
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_UPDATE_DATE', 'Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Demographic Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Demographic Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Marital Status
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_MARITAL_STATUS', 'Marital Status', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Birth Date
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_BIRTHDATE', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.birthDate'')', 'Birth Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Deceased
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_DECEASED', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.deceased'')', 'Deceased', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Gender
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_GENDER', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.gender'')', 'Gender', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Race
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_RACE', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.race'')', 'Race', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Military
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_MILITARY', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.military'')', 'Military', b'0', 1, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Matching Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Matching Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Matching
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MATCHING', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.matching'')', 'Matching', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Percent Matching
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PERCENTMATCH', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.percentMatch'')', 'Percent Matching', b'0', 3, @REPORTFIELDGROUP_ID);

    -- Maximum Annual Limit
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MAXIMUMMATCH', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.maximumAnnualLimit'')', 'Maximum Annual Limit', b'0', 5, @REPORTFIELDGROUP_ID);

    -- Mimimum Gift Match
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MINIMUMGIFTMATCH', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.minimumGiftMatch'')', 'Mimimum Gift Match', b'0', 5, @REPORTFIELDGROUP_ID);

    -- Total Per Employee Per Year
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_TOTALPEREMPLOYEEPERYEAR', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.totalPerEmployeePerYear'')', 'Total Per Employee Per Year', b'0', 5, @REPORTFIELDGROUP_ID);

    -- Eligibility
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MINIMUMGIFTMATCH', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.eligibility'', ''customFieldMap[organization.eligibility]'')', 'Eligibility', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Funds
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEFUNDS', 'GETCUSTOMFIELDCONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.eligibleFunds'')', 'Eligible Funds', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Funds - Additional
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEFUNDSADDITIONAL', 'GETCUSTOMFIELDCONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.additional_eligibleFunds'')', 'Eligible Funds - Additional', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Organizations
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEORGANIZATIONS', 'GETCUSTOMFIELDCONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.eligibleOrganizations'')', 'Eligible Organizations', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Organizations - Additional
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEORGANIZATIONSADDITIONAL', 'GETCUSTOMFIELDCONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.additional_eligibleOrganizations'')', 'Eligible Organizations - Additional', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Ineligible Organizations
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_INELIGIBLEORGANIZATIONS', 'GETCUSTOMFIELDCONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.ineligibleOrganizations'')', 'Ineligible Organizations', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Ineligible Organizations - Additional
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_INELIGIBLEORGANIZATIONSADDITIONAL', 'GETCUSTOMFIELDCONCATENATED(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.additional_ineligibleOrganizations'')', 'Ineligible Organizations - Additional', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Matching Gift Form
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MATCHINGGIFTFORM', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.onlineMatchingGiftForm'')', 'Matching Gift Form', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Program Start Date
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROGRAMSTARTMONTH', 'GETPICKLISTDISPLAYVALUE(''customFieldMap[organization.programStartMonth]'', GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.programStartMonth''))', 'Program Start Month', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Program Contact Account Number
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROGRAMCONTACTACCOUNTNUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.programContact''))', 'Program Contact Account Number', b'0', 2, @REPORTFIELDGROUP_ID);

    -- Program Contact Account Name
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROGRAMCONTACTACCOUNTNAME', 'GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.programContact''))', 'Program Contact Account Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Procedure For Requesting Match
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROCEDUREFORREQUESTINGMATCH', 'GETCUSTOMFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.procedureForRequestingMatch'')', 'Procedure For Requesting Match', b'0', 1, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Miscellaneous Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Miscellaneous Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Site Name
    CALL INSERTREPORTFIELD('CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_SITE_NAME', 'Site Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Current Address Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Current Address Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Address ID
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_ID', 'Address ID', b'0', 2, @REPORTFIELDGROUP_ID);

    -- Address Type
    CALL INSERTREPORTFIELDWITHALIAS('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_TYPE', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(ADDRESS_CURRENT_ADDRESS_ID, ''address'', ''addressType'', ''customFieldMap[addressType]'')', 'Address Type', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Status
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ACTIVATION_STATUS', 'Address Status', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Effective Date
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_EFFECTIVE_DATE', 'Address Effective Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Seasonal Start Date
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_SEASONAL_START_DATE_DISPLAY', 'Seasonal Start Date', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Seasonal End Date
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_SEASONAL_END_DATE_DISPLAY', 'Seasonal End Date', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Temporary Start Date
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_TEMPORARY_START_DATE', 'Temporary Start Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Temporary End Date
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_TEMPORARY_END_DATE', 'Temporary End Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Address Line 1
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_LINE_1', 'Address Line 1', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Line 2
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_LINE_2', 'Address Line 2', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Line 3
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_ADDRESS_LINE_3', 'Address Line 3', b'0', 1, @REPORTFIELDGROUP_ID);

    -- City
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_CITY', 'City', b'0', 1, @REPORTFIELDGROUP_ID);

    -- State/Province
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_STATE_PROVINCE', 'State/Province', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Country
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_COUNTRY', 'Country', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Zip/Postal Code
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_POSTAL_CODE', 'Zip/Postal Code', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Receive Correspondence
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_RECEIVE_CORRESPONDENCE', 'Receive Correspondence', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Comments
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_COMMENT', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Create Date
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_CREATE_DATE', 'Address Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Address Update Date
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_UPDATE_DATE', 'Address Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Primary Address
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_IS_PRIMARY', 'Primary Address', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Address Undeliverable
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_UNDELIVERABLE', 'Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Address Inactive
    CALL INSERTREPORTFIELD('ADDRESS_CURRENT_ADDRESS_ID', 'ADDRESS_CURRENT_INACTIVE', 'Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Relationship Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Relationship Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Relationship Type
    CALL INSERTREPORTFIELD('CONSTITUENT_RELATIONSHIP_CONSTITUENT_ID', 'CONSTITUENT_RELATIONSHIP_TYPE', 'Relationship Type', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Related Account's Account Number
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_RELATIONSHIP_CONSTITUENT_ID', 'CONSTITUENT_RELATIONSHIP_ACCOUNTNUMBER', 'GETCONSTITUENTACCOUNTNUMBER(CONSTITUENT_RELATIONSHIP_CONSTITUENT_ID)', 'Related Account''s Account Number', b'0', 2, @REPORTFIELDGROUP_ID);
    -- Related Account's Names
    CALL INSERTREPORTFIELDWITHALIAS('CONSTITUENT_RELATIONSHIP_CONSTITUENT_ID', 'CONSTITUENT_RELATIONSHIP_NAME', 'GETCONSTITUENTDISPLAYNAME(CONSTITUENT_RELATIONSHIP_CONSTITUENT_ID)', 'Related Account''s Name', b'0', 1, @REPORTFIELDGROUP_ID);
    -- Related Account Custom Field Name
    CALL INSERTREPORTFIELD('CONSTITUENT_RELATIONSHIP_CUSTOM_FIELD_NAME', 'CONSTITUENT_RELATIONSHIP_CUSTOM_FIELD_NAME', 'Related Account Custom Field Name', b'0', 1, @REPORTFIELDGROUP_ID);
    -- Related Account Custom Field Value
    CALL INSERTREPORTFIELD('CONSTITUENT_RELATIONSHIP_CUSTOM_FIELD_NAME', 'CONSTITUENT_RELATIONSHIP_CUSTOM_FIELD_VALUE', 'Related Account Custom Field Value', b'0', 1, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Contact Details Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Related Account Contact Details', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Account Number
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_ACCOUNT_NUMBER', 'Account Number', b'1', 2, @REPORTFIELDGROUP_ID);

    -- Account Manager Name
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ACCOUNTMANAGER', 'GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''accountManager''))', 'Account Manager Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Account Manager Account Number
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ACCOUNTMANAGERACCOUNTNUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''accountManager''))', 'Account Manager Account Number', b'0', 2, @REPORTFIELDGROUP_ID);

    -- Constituent Type
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_CONSTITUENT_TYPE', 'Constituent Type', b'1', 1, @REPORTFIELDGROUP_ID);

    -- Profile Type
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_CONSTITUENT_ROLE', 'Profile Type', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Donor Profile
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_DONOR_PROFILE', 'Donor Profile', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Title
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_TITLE', 'Title', b'0', 1, @REPORTFIELDGROUP_ID);

    -- First Name
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_FIRST_NAME', 'First Name', b'1', 1, @REPORTFIELDGROUP_ID);

    -- Middle Name
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_MIDDLE_NAME', 'Middle Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Last Name
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_LAST_NAME', 'Last Name', b'1', 1, @REPORTFIELDGROUP_ID);

    -- Suffix
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_SUFFIX', 'Suffix', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Recognition Name
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_RECOGNITION_NAME', 'Recognition Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Formal Saluation
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_FORMAL_SALUTATION', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''formalSalutation'')', 'Formal Salutation', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Informal Salutation
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_INFORMAL_SALUTATION', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''informalSalutation'')', 'Informal Salutation', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Head of Household Salutation
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_HEADOFHOUSEHOLD_SALUTATION', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''headOfHouseholdSalutation'')', 'Head of Household Salutation', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Organization Name
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_ORGANIZATION_NAME', 'Organization Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Legal Name
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_LEGAL_NAME', 'Legal Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Website
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_ORGANIZATION_WEBSITE', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.website'')', 'Website', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Tax ID
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_ORGANIZATION_TAXID', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.taxid'')', 'Tax ID', b'0', 1, @REPORTFIELDGROUP_ID);

    -- NAICS Code
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_NAICS_CODE', 'NAICS Code', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Communication Preferences
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'COMMUNICATIONPREFERENCES', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''communicationPreferences'')', 'Communication Preferences', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Opt In Preferences
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_OPT_IN_PREFERENCES', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''communicationOptInPreferences'', ''customFieldMap[communicationOptInPreferences]'')', 'Opt In Preferences', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Email Format
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'EMAILFORMAT', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''emailFormat'')', 'Email Format', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Login ID
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_LOGIN_ID', 'Login ID', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Create Date
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_CREATE_DATE', 'Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Update Date
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'RELATED_CONSTITUENT_UPDATE_DATE', 'Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Demographic Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Related Account Demographic Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Marital Status
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_MARITAL_STATUS', 'Marital Status', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Birth Date
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_BIRTHDATE', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.birthDate'')', 'Birth Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Deceased
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_DECEASED', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.deceased'')', 'Deceased', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Gender
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_GENDER', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.gender'')', 'Gender', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Race
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_RACE', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.race'')', 'Race', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Military
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'INDIVIDUAL_MILITARY', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.military'')', 'Military', b'0', 1, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Matching Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Related Account Matching Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Matching
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MATCHING', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.matching'')', 'Matching', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Percent Matching
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PERCENTMATCH', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.percentMatch'')', 'Percent Matching', b'0', 3, @REPORTFIELDGROUP_ID);

    -- Maximum Annual Limit
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MAXIMUMMATCH', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.maximumAnnualLimit'')', 'Maximum Annual Limit', b'0', 5, @REPORTFIELDGROUP_ID);

    -- Mimimum Gift Match
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MINIMUMGIFTMATCH', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.minimumGiftMatch'')', 'Mimimum Gift Match', b'0', 5, @REPORTFIELDGROUP_ID);

    -- Total Per Employee Per Year
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_TOTALPEREMPLOYEEPERYEAR', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.totalPerEmployeePerYear'')', 'Total Per Employee Per Year', b'0', 5, @REPORTFIELDGROUP_ID);

    -- Eligibility
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MINIMUMGIFTMATCH', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.eligibility'', ''customFieldMap[organization.eligibility]'')', 'Eligibility', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Funds
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEFUNDS', 'GETCUSTOMFIELDCONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.eligibleFunds'')', 'Eligible Funds', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Funds - Additional
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEFUNDSADDITIONAL', 'GETCUSTOMFIELDCONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.additional_eligibleFunds'')', 'Eligible Funds - Additional', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Organizations
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEORGANIZATIONS', 'GETCUSTOMFIELDCONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.eligibleOrganizations'')', 'Eligible Organizations', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Eligible Organizations - Additional
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_ELIGIBLEORGANIZATIONSADDITIONAL', 'GETCUSTOMFIELDCONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.additional_eligibleOrganizations'')', 'Eligible Organizations - Additional', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Ineligible Organizations
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_INELIGIBLEORGANIZATIONS', 'GETCUSTOMFIELDCONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.ineligibleOrganizations'')', 'Ineligible Organizations', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Ineligible Organizations - Additional
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_INELIGIBLEORGANIZATIONSADDITIONAL', 'GETCUSTOMFIELDCONCATENATED(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.additional_ineligibleOrganizations'')', 'Ineligible Organizations - Additional', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Matching Gift Form
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_MATCHINGGIFTFORM', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.onlineMatchingGiftForm'')', 'Matching Gift Form', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Program Start Date
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROGRAMSTARTMONTH', 'GETPICKLISTDISPLAYVALUE(''customFieldMap[organization.programStartMonth]'', GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.programStartMonth''))', 'Program Start Month', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Program Contact Account Number
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROGRAMCONTACTACCOUNTNUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.programContact''))', 'Program Contact Account Number', b'0', 2, @REPORTFIELDGROUP_ID);

    -- Program Contact Account Name
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROGRAMCONTACTACCOUNTNAME', 'GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.programContact''))', 'Program Contact Account Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Procedure For Requesting Match
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_CONSTITUENT_CONSTITUENT_ID', 'ORGANIZATION_PROCEDUREFORREQUESTINGMATCH', 'GETCUSTOMFIELD(RELATED_CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''organization.procedureForRequestingMatch'')', 'Procedure For Requesting Match', b'0', 1, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Miscellaneous Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Related Account Miscellaneous Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Site Name
    CALL INSERTREPORTFIELD('RELATED_CONSTITUENT_CONSTITUENT_ID', 'CONSTITUENT_SITE_NAME', 'Site Name', b'0', 1, @REPORTFIELDGROUP_ID);

    -- ***********************************************************************
    -- Current Address Information Field Group
    -- ***********************************************************************
    CALL INSERTREPORTFIELDGROUP('Related Account Current Address Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

    -- Address ID
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'Address ID', b'0', 2, @REPORTFIELDGROUP_ID);

    -- Address Type
    CALL INSERTREPORTFIELDWITHALIAS('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_ADDRESS_TYPE', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(RELATED_ADDRESS_CURRENT_ADDRESS_ID, ''address'', ''addressType'', ''customFieldMap[addressType]'')', 'Address Type', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Status
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_ACTIVATION_STATUS', 'Address Status', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Effective Date
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_EFFECTIVE_DATE', 'Address Effective Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Seasonal Start Date
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_SEASONAL_START_DATE_DISPLAY', 'Seasonal Start Date', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Seasonal End Date
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_SEASONAL_END_DATE_DISPLAY', 'Seasonal End Date', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Temporary Start Date
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_TEMPORARY_START_DATE', 'Temporary Start Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Temporary End Date
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_TEMPORARY_END_DATE', 'Temporary End Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Address Line 1
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_ADDRESS_LINE_1', 'Address Line 1', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Line 2
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_ADDRESS_LINE_2', 'Address Line 2', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Line 3
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_ADDRESS_LINE_3', 'Address Line 3', b'0', 1, @REPORTFIELDGROUP_ID);

    -- City
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_CITY', 'City', b'0', 1, @REPORTFIELDGROUP_ID);

    -- State/Province
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_STATE_PROVINCE', 'State/Province', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Country
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_COUNTRY', 'Country', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Zip/Postal Code
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_POSTAL_CODE', 'Zip/Postal Code', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Receive Correspondence
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_RECEIVE_CORRESPONDENCE', 'Receive Correspondence', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Comments
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_COMMENT', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);

    -- Address Create Date
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_CREATE_DATE', 'Address Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Address Update Date
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_UPDATE_DATE', 'Address Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

    -- Primary Address
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_IS_PRIMARY', 'Primary Address', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Address Undeliverable
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_UNDELIVERABLE', 'Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);

    -- Address Inactive
    CALL INSERTREPORTFIELD('RELATED_ADDRESS_CURRENT_ADDRESS_ID', 'RELATED_ADDRESS_CURRENT_INACTIVE', 'Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);

  END IF;
END$$

DELIMITER ;

CALL INSERTCONSTITUENTSRELATIONSHIPDETAILS_UPDATESCRIPT();
