UPDATE THEGURU_VIEW_JOIN
SET JOIN_TABLE_ALIAS = 'VW_V2_AGD',
JOIN_CRITERIA = REPLACE(JOIN_CRITERIA, 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS.', 'VW_V2_AGD.')
WHERE JOIN_TABLE_ALIAS = 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS';


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'CONSTITUENT_AH', 'CONSTITUENT_AH_', 'CONSTITUENT_AH.ENTITY_TYPE = ''constituent'' AND CONSTITUENT_AH.ENTITY_ID = CONSTITUENT.CONSTITUENT_ID AND CONSTITUENT_AH.IS_DELETED = 0', TRUE, 4, 'Contact '
FROM THEGURU_VIEW
WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS';


INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'ATTRIBUTE_HISTORY', 'Attribute History', 'Attribute History Reference Number', '${COLUMN_PREFIX}ATTRIBUTE_HISTORY_ID', 'ATTRIBUTE_HISTORY_ID', 2;
    
INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'ATTRIBUTE_HISTORY', 'Attribute History', 'Attribute Name', '${COLUMN_PREFIX}ATTRIBUTE_DISPLAY_NAME', 'ATTRIBUTE_DISPLAY_NAME', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'ATTRIBUTE_HISTORY', 'Attribute History', 'Attribute Value', '${COLUMN_PREFIX}ATTRIBUTE_DISPLAY_VALUE', 'ATTRIBUTE_DISPLAY_VALUE', 1;
    
INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'ATTRIBUTE_HISTORY', 'Attribute History', 'Attribute Start Date', '${COLUMN_PREFIX}START_DATE', 'START_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'ATTRIBUTE_HISTORY', 'Attribute History', 'Attribute End Date', '${COLUMN_PREFIX}END_DATE', 'END_DATE', 4;


-- Address
INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT(PRIMARY_TABLE_ALIAS, '_AH'),
  CONCAT(PRIMARY_TABLE_COLUMN_PREFIX, 'AH_'), CONCAT(PRIMARY_TABLE_ALIAS, '_AH.ENTITY_TYPE = ''address'' AND ', PRIMARY_TABLE_ALIAS, '_AH.ENTITY_ID = ', PRIMARY_TABLE_ALIAS, '.ADDRESS_ID AND ', PRIMARY_TABLE_ALIAS, '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, 
  'Address '
FROM THEGURU_VIEW
WHERE VIEW_NAME = 'VW_V2_ADDRESSES_CURRENT';


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT(JOIN_TABLE_ALIAS, '_AH'), CONCAT(JOIN_TABLE_COLUMN_PREFIX, 'AH_'),
  CONCAT(JOIN_TABLE_ALIAS, '_AH.ENTITY_TYPE = ''address'' AND ', JOIN_TABLE_ALIAS, '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.ADDRESS_ID AND ', JOIN_TABLE_ALIAS, '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Address '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'ADDRESS'
AND JOIN_TABLE_ALIAS NOT IN ('ADJUSTED_GIFT_PAYMENT_ADDRESS', 'RECURRING_GIFT_PAYMENT_ADDRESS', 'GIFT_PAYMENT_ADDRESS');


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT(JOIN_TABLE_ALIAS, '_AH'), CONCAT(JOIN_TABLE_COLUMN_PREFIX, 'AH_'),
  CONCAT(JOIN_TABLE_ALIAS, '_AH.ENTITY_TYPE = ''address'' AND ', JOIN_TABLE_ALIAS, '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.ADDRESS_ID AND ', JOIN_TABLE_ALIAS, '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Payment Address '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'ADDRESS'
AND JOIN_TABLE_ALIAS IN ('GIFT_PAYMENT_ADDRESS');


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT('RGP_ADDRESS', '_AH'), CONCAT('RGP_ADDRESS_', 'AH_'),
  CONCAT('RGP_ADDRESS', '_AH.ENTITY_TYPE = ''address'' AND ', 'RGP_ADDRESS', '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.ADDRESS_ID AND ', 'RGP_ADDRESS', '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Recurring Gift Payment Address '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'ADDRESS'
AND JOIN_TABLE_ALIAS = 'RECURRING_GIFT_PAYMENT_ADDRESS';


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT('AGP_ADDRESS', '_AH'), CONCAT('AGP_ADDRESS_', 'AH_'),
  CONCAT('AGP_ADDRESS', '_AH.ENTITY_TYPE = ''address'' AND ', 'AGP_ADDRESS', '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.ADDRESS_ID AND ', 'AGP_ADDRESS', '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Adjustment Payment Address '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'ADDRESS'
AND JOIN_TABLE_ALIAS = 'ADJUSTED_GIFT_PAYMENT_ADDRESS';


-- Phone
INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT(JOIN_TABLE_ALIAS, '_AH'), CONCAT(JOIN_TABLE_COLUMN_PREFIX, 'AH_'),
  CONCAT(JOIN_TABLE_ALIAS, '_AH.ENTITY_TYPE = ''phone'' AND ', JOIN_TABLE_ALIAS, '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.PHONE_ID AND ', JOIN_TABLE_ALIAS, '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Phone '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'PHONE'
AND JOIN_TABLE_ALIAS NOT IN ('ADJUSTED_GIFT_PAYMENT_PHONE', 'RECURRING_GIFT_PAYMENT_PHONE', 'GIFT_PAYMENT_PHONE');


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT(JOIN_TABLE_ALIAS, '_AH'), CONCAT(JOIN_TABLE_COLUMN_PREFIX, 'AH_'),
  CONCAT(JOIN_TABLE_ALIAS, '_AH.ENTITY_TYPE = ''phone'' AND ', JOIN_TABLE_ALIAS, '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.PHONE_ID AND ', JOIN_TABLE_ALIAS, '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Payment Phone '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'PHONE'
AND JOIN_TABLE_ALIAS IN ('GIFT_PAYMENT_PHONE');


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT('RGP_PHONE', '_AH'), CONCAT('RGP_PHONE_', 'AH_'),
  CONCAT('RGP_PHONE', '_AH.ENTITY_TYPE = ''phone'' AND ', 'RGP_PHONE', '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.PHONE_ID AND ', 'RGP_PHONE', '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Recurring Gift Payment Phone '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'PHONE'
AND JOIN_TABLE_ALIAS = 'RECURRING_GIFT_PAYMENT_PHONE';


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT('AGP_PHONE', '_AH'), CONCAT('AGP_PHONE_', 'AH_'),
  CONCAT('AGP_PHONE', '_AH.ENTITY_TYPE = ''phone'' AND ', 'AGP_PHONE', '_AH.ENTITY_ID = ', JOIN_TABLE_ALIAS, '.PHONE_ID AND ', 'AGP_PHONE', '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW_JOIN.VIEW_ID = B.VIEW_ID) + 1, 
  'Adjustment Payment Phone '
FROM THEGURU_VIEW_JOIN
WHERE JOIN_TABLE = 'PHONE'
AND JOIN_TABLE_ALIAS = 'ADJUSTED_GIFT_PAYMENT_PHONE';


-- Gift
INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'GIFT_AH', 'GIFT_AH_', 'GIFT_AH.ENTITY_TYPE = ''gift'' AND GIFT_AH.ENTITY_ID = VW_V2_GIFTS.GIFT_ID AND GIFT_AH.IS_DELETED = 0', TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW.VIEW_ID = B.VIEW_ID) + 1,
  'Donation '
FROM THEGURU_VIEW
WHERE PRIMARY_TABLE = 'GIFT';


-- Touch Point
INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'TOUCH_POINT_AH', 'TOUCH_POINT_AH_', 'TOUCH_POINT_AH.ENTITY_TYPE = ''touchpoint'' AND TOUCH_POINT_AH.ENTITY_ID = COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID AND TOUCH_POINT_AH.IS_DELETED = 0', TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW.VIEW_ID = B.VIEW_ID) + 1,
  'Touch Point '
FROM THEGURU_VIEW
WHERE PRIMARY_TABLE = 'COMMUNICATION_HISTORY';


-- Pledges
INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT(PRIMARY_TABLE_ALIAS, '_AH'), CONCAT(PRIMARY_TABLE_COLUMN_PREFIX, 'AH_'),
  CONCAT(PRIMARY_TABLE_ALIAS, '_AH.ENTITY_TYPE = ''pledge'' AND ', PRIMARY_TABLE_ALIAS, '_AH.ENTITY_ID = ', PRIMARY_TABLE_ALIAS, '.PLEDGE_ID AND ', PRIMARY_TABLE_ALIAS, '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW.VIEW_ID = B.VIEW_ID) + 1,
  'Pledge '
FROM THEGURU_VIEW
WHERE PRIMARY_TABLE = 'PLEDGE';


-- Recurring Gift
INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT DISTINCT
	VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, CONCAT(PRIMARY_TABLE_ALIAS, '_AH'), CONCAT(PRIMARY_TABLE_COLUMN_PREFIX, 'AH_'),
  CONCAT(PRIMARY_TABLE_ALIAS, '_AH.ENTITY_TYPE = ''recurringGift'' AND ', PRIMARY_TABLE_ALIAS, '_AH.ENTITY_ID = ', PRIMARY_TABLE_ALIAS, '.RECURRING_GIFT_ID AND ', PRIMARY_TABLE_ALIAS, '_AH.IS_DELETED = 0'), TRUE, 
  (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN B WHERE THEGURU_VIEW.VIEW_ID = B.VIEW_ID) + 1,
  'Pledge '
FROM THEGURU_VIEW
WHERE PRIMARY_TABLE = 'RECURRING_GIFT';