INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'ADJUSTED_GIFT_OTHERPAYMETHOD_DESCRIPTION', 'Adjustment Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'ADJUSTED_GIFT_OTHERPAYMETHOD_LONG_DISPLAY_NAME', 'Adjustment Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'ADJUSTED_GIFT_OTHERPAYMETHOD_SHORT_DISPLAY_NAME', 'Adjustment Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'VW_AGD_ADJUSTED_GIFT_OTHERPAYMETHOD_DESCRIPTION', 'Adjustment Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'VW_AGD_ADJUSTED_GIFT_OTHERPAYMETHOD_LONG_DISPLAY_NAME', 'Adjustment Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'VW_AGD_ADJUSTED_GIFT_OTHERPAYMETHOD_SHORT_DISPLAY_NAME', 'Adjustment Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'GIFT_OTHERPAYMETHOD_DESCRIPTION', 'Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'GIFT_OTHERPAYMETHOD_LONG_DISPLAY_NAME', 'Payment Information';

INSERT THEGURU_FIELD_FIELDGROUP_OVERRIDE
    (ALIAS_NAME, FIELD_GROUP_OVERRIDE)
SELECT
    'GIFT_OTHERPAYMETHOD_SHORT_DISPLAY_NAME', 'Payment Information';
