
-- Move V1 constituent & primary contact info view back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Constituents');

UPDATE REPORTDATASUBSOURCE 
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_CONSTITUENTS_PRIMARYCONTACTINFORMATION');

-- Add the new constituents & primary contact data source data sub-source
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Constituents');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Constituents & Primary Contact Information', 0, 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', 'Constituents and their primary addresses, email addresses and phone numbers');
 
 
-- VW_V2_TOUCHPOINTS
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION', 'Constituents & Primary Contact Information', 'VW_V2_CONSTITUENTS', TRUE, 'VW_V2_CONSTITUENTS', '', TRUE, 90, 'ADDRESS.ADDRESS_ID IS NOT NULL OR EMAIL.EMAIL_ID IS NOT NULL OR PHONE.PHONE_ID IS NOT NULL';

SET @VIEW_ID = LAST_INSERT_ID();


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1', TRUE, 1, 'Primary ';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', FALSE, 2;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1', TRUE, 3, 'Primary ';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', FALSE, 4;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1', TRUE, 5, 'Primary ';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', FALSE, 6;



-- Move V1 touch point views back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Touch Points');

UPDATE REPORTDATASUBSOURCE 
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_TOUCHPOINTS', 'VW_TOUCHPOINTS_CONSTITUENT_INFORMATION');

-- Add the new touch point data sub-source
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Touch Points');


INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME)
VALUES
	('Touch Points', 0, 'VW_V2_TOUCHPOINTS', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults');


-- VW_V2_TOUCHPOINTS
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_OVERRIDE)
SELECT
	'VW_V2_TOUCHPOINTS', 'Touch Points', 'COMMUNICATION_HISTORY', FALSE, 'COMMUNICATION_HISTORY', 'COMMUNICATION_HISTORY_', TRUE, 470, 'Touch Point Information';

SET @VIEW_ID = LAST_INSERT_ID();

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'Touch Point Reference Number', '${COLUMN_PREFIX}COMMUNICATION_HISTORY_ID', 'COMMUNICATION_HISTORY_ID', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'Communication Type', '${COLUMN_PREFIX}COMMUNICATION_TYPE', 'COMMUNICATION_TYPE', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'System Generated', '${COLUMN_PREFIX}SYSTEM_GENERATED', 'SYSTEM_GENERATED', 6;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'Create Date', '${COLUMN_PREFIX}CREATE_DATE', 'CREATE_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'Update Date', '${COLUMN_PREFIX}UPDATE_DATE', 'UPDATE_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'Account Number', 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)', 'ACCOUNT_NUMBER', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'Recorded By - Account Number', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(${COLUMN_PREFIX}COMMUNICATION_HISTORY_ID, ''communicationhistory'', ''recordedBy''))', 'RECORDEDBY_ACCOUNTNUMBER', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'COMMUNICATION_HISTORY', 'Touch Point Information', 'Recorded By - Account Name', 'GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(${COLUMN_PREFIX}COMMUNICATION_HISTORY_ID, ''communicationhistory'', ''recordedBy''))', 'RECORDEDBY_ACCOUNTNAME', 1;



SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Touch Points');


INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME)
VALUES
	('Touch Points & Constituent Information', 0, 'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults');


-- VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION', 'Touch Points & Constituent Information', 'VW_V2_TOUCHPOINTS', TRUE, 'VW_V2_TOUCHPOINTS', '', TRUE, 480;

SET @VIEW_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
    (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, PARENT_ENTITY_TYPE, SUB_FIELD_NAME)
SELECT
	@VIEW_ID, 'LEFT', 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION', TRUE, 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION', '', 'VW_V2_TOUCHPOINTS.COMMUNICATION_HISTORY_CONSTITUENT_ID = VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION.CONSTITUENT_CONSTITUENT_ID', TRUE, 1, '', '', '', '';


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'TOUCHPOINT_ADDRESS_', 'VW_V2_TOUCHPOINTS.COMMUNICATION_HISTORY_ADDRESS_ID = ADDRESS.ADDRESS_ID', TRUE, 2, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', FALSE, 3;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'TOUCHPOINT_EMAIL_', 'VW_V2_TOUCHPOINTS.COMMUNICATION_HISTORY_EMAIL_ID = EMAIL.EMAIL_ID', TRUE, 4, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', FALSE, 5;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'TOUCHPOINT_PHONE_', 'VW_V2_TOUCHPOINTS.COMMUNICATION_HISTORY_PHONE_ID = PHONE.PHONE_ID', TRUE, 6, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', FALSE, 7;

