
CREATE TABLE `REPORTCHARTSETTINGSSERIES` (
  `REPORTCHARTSETTINGS_SERIES_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REPORTCHARTSETTINGS_ID` bigint(20) NOT NULL,
  `SERIES` bigint(20) DEFAULT NULL,
  `OPERATION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REPORTCHARTSETTINGS_SERIES_ID`),
  FOREIGN KEY (`REPORTCHARTSETTINGS_ID`) REFERENCES `REPORTCHARTSETTINGS` (`REPORTCHARTSETTINGS_ID`))
ENGINE=InnoDB;
