UPDATE REPORTCUSTOMFILTERDEFINITION
SET SQL_TEXT = REPLACE(SQL_TEXT, 'TRANSACTION_DATE', 'DONATION_DATE')
WHERE DISPLAY_TEXT = 'Gift Totals - Account has given at least $[GIFTAMOUNT] in year [GIFTYEAR]'
AND SQL_TEXT LIKE '%TRANSACTION_DATE%';
