-- Orange Leap Zip Radius
INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 800000, 'Zip Radius - Constituent''s current address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].ADDRESS_CURRENT_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s current address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 800000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 800000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'ADDRESS_CURRENT_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 800000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 800000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 801000, 'Zip Radius - Constituent''s address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 801000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 801000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 801000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 801000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 802000, 'Zip Radius - Constituent''s gift adjustment payment address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].ADJUSTED_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s gift adjustment payment address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 802000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 802000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'ADJUSTED_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 802000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 801000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 803000, 'Zip Radius - Constituent''s gift payment address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s gift payment address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 803000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 803000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 803000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 803000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 804000, 'Zip Radius - Constituent''s payment address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].PAYMENT_SOURCE_ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s payment address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 804000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 804000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'PAYMENT_SOURCE_ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 804000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 804000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 805000, 'Zip Radius - Constituent''s recurring gift payment address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].RECURRING_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s recurring gift payment address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 805000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 805000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'RECURRING_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 805000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 805000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 806000, 'Zip Radius - Constituent''s touch point address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].TOUCHPOINT_ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s touch point address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 806000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 806000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'TOUCHPOINT_ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 806000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 806000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 807000, 'Zip Radius - Constituent''s adjusted gift payment address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].VW_AGD_ADJUSTED_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s adjusted gift payment address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 807000, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 807000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'VW_AGD_ADJUSTED_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 807000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 807000 + REPORTSUBSOURCE_ID)
;


INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT 808000, 'Zip Radius - Constituent''s recurring gift payment address is within [ZIPRADIUS] miles of zip code [ZIPCODE] in [COUNTRY]',
'[VIEWNAME].VW_RGD_RECURRING_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY IN ({lookupReferenceBean:orangeLeapPostalCodeRadius})',
'Zip Radius - Constituent''s recurring gift payment address is within <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/>miles of zip code <input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[1].criteria" value="{1}"/>in <select class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[2].criteria" populateSelectOptions="AJAX" requestType="PICKLISTITEMS" criteria1Name="PICKLISTNAME" criteria1Value="country" criteria2Name="DEFAULTVALUE" criteria2Value="{3}"><option value="{3}">Loading...</option></select>';

INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT 808000 REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, 808000 + REPORTSUBSOURCE_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME IN
(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CASE WHEN DATABASE() <> 'theguru' THEN REPLACE(DATABASE(), 'theguru', '') ELSE DATABASE() END
AND TABLE_NAME LIKE 'VW_%'
AND COLUMN_NAME LIKE 'VW_RGD_RECURRING_GIFT_PAYMENT_ADDRESS_POSTAL_CODE_KEY')
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 808000
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = 808000 + REPORTSUBSOURCE_ID)
;

