-- Add new Custom Reports data sub source

SET @REPORTDATASOURCE_ID = 
  (SELECT REPORTSOURCE_ID FROM REPORTDATASOURCE WHERE REPORT_NAME = 'Orange Leap - V2');
  
INSERT INTO REPORTDATASUBSOURCEGROUP
	(DESCRIPTION, DISPLAY_NAME, reportDataSource_REPORTSOURCE_ID)
VALUES
	('Custom Reports', 'Custom Reports', @REPORTDATASOURCE_ID);

-- Add the new constituents & primary contact data source data sub-source
SET @REPORTDATASUBSOURCEGROUP_ID = LAST_INSERT_ID();

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS SET COLUMN_NAME = '${COLUMN_PREFIX}DONOR_PROFILE' WHERE DISPLAY_NAME = 'Donor Profile';
UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS SET COLUMN_NAME = '${COLUMN_PREFIX}CONSTITUENT_ROLE' WHERE DISPLAY_NAME = 'Profile Type';

UPDATE THEGURU_TABLE_FIELD_EXCLUSIONS SET FIELD_NAME = REPLACE(FIELD_NAME, '_DESCRIPTION', '_DESC') WHERE FIELD_NAME LIKE '%_DESCRIPTION';
UPDATE THEGURU_TABLE_FIELD_EXCLUSIONS SET FIELD_NAME = REPLACE(FIELD_NAME, '_SHORT_DISPLAY_NAME', '_SDN') WHERE FIELD_NAME LIKE '%_SHORT_DISPLAY_NAME';
UPDATE THEGURU_TABLE_FIELD_EXCLUSIONS SET FIELD_NAME = REPLACE(FIELD_NAME, '_LONG_DISPLAY_NAME', '_LDN') WHERE FIELD_NAME LIKE '%_LONG_DISPLAY_NAME';

ALTER TABLE THEGURU_VIEW_JOIN ADD USE_PARENT_FIELD_GROUP_PREFIXES BIT DEFAULT 0;
