UPDATE THEGURU_VIEW
SET WHERE_CLAUSE =
  CASE
    WHEN WHERE_CLAUSE IS NULL THEN CONCAT(PRIMARY_TABLE_ALIAS, '.IS_DELETED = 0')
    ELSE CONCAT(WHERE_CLAUSE, ' AND ', PRIMARY_TABLE_ALIAS, '.IS_DELETED = 0')
  END
WHERE PRIMARY_TABLE IN
('ADDRESS',
'ATTACHMENT',
'ATTRIBUTE_HISTORY',
'CUSTOM_MODULE',
'CUSTOM_MODULE_COMPONENT',
'CUSTOM_QUERY',
'CUSTOM_QUERY_SCHED',
'CUSTOM_TABLE_ROW',
'EMAIL',
'FIELD_VALIDATION',
'JOB',
'PHONE',
'PICKLIST',
'SECTION_FIELD')
AND WHERE_CLAUSE NOT LIKE '%IS_DELETED = 0%';

UPDATE THEGURU_VIEW_JOIN
SET JOIN_CRITERIA = 
  CASE
    WHEN JOIN_CRITERIA IS NULL THEN CONCAT(JOIN_TABLE_ALIAS, '.IS_DELETED = 0')
    ELSE CONCAT(JOIN_CRITERIA, ' AND ', JOIN_TABLE_ALIAS, '.IS_DELETED = 0')
  END
WHERE JOIN_TABLE IN
('ADDRESS',
'ATTACHMENT',
'ATTRIBUTE_HISTORY',
'CUSTOM_MODULE',
'CUSTOM_MODULE_COMPONENT',
'CUSTOM_QUERY',
'CUSTOM_QUERY_SCHED',
'CUSTOM_TABLE_ROW',
'EMAIL',
'FIELD_VALIDATION',
'JOB',
'PHONE',
'PICKLIST',
'SECTION_FIELD')
AND JOIN_CRITERIA NOT LIKE '%IS_DELETED = 0%';
