START TRANSACTION;

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
(TABLE_NAME, FIELD_NAME)
SELECT 'PLEDGE', 'FIRST_PROJECT_CODE';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
(TABLE_NAME, FIELD_NAME)
SELECT 'PLEDGE', 'FIRST_MOTIVATION_CODE';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
(TABLE_NAME, FIELD_NAME)
SELECT 'GIFT', 'FIRST_PROJECT_CODE';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
(TABLE_NAME, FIELD_NAME)
SELECT 'GIFT', 'FIRST_MOTIVATION_CODE';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
(TABLE_NAME, FIELD_NAME)
SELECT 'RECURRING_GIFT', 'FIRST_PROJECT_CODE';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
(TABLE_NAME, FIELD_NAME)
SELECT 'RECURRING_GIFT', 'FIRST_MOTIVATION_CODE';

UPDATE THEGURU_VIEW_JOIN
SET SORT_ORDER = SORT_ORDER + 1
WHERE VIEW_ID = (SELECT VIEW_ID FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS')
AND JOIN_TABLE <> 'DISTRO_LINE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, 
  JOIN_CRITERIA, INCLUDE_ALL_FIELDS, FIELD_GROUP_OVERRIDE, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME)
SELECT
  VIEW_ID, 'LEFT', 'GIFT_IN_KIND_DETAIL', FALSE, 'GIFT_IN_KIND_DETAIL', 'GIFT_IN_KIND_DETAIL_',
  'GIFT_IN_KIND_DETAIL.PLEDGE_ID = PLEDGE.PLEDGE_ID',
  TRUE, 'Pledge Detail Information (Non-Monetary Pledges)', 2, 'pledge', 'details'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO', 'CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO_', 'CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO.FIELD_NAME = ''associatedPledgeId'' AND CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO.ENTITY_TYPE = ''distributionline'' AND PLEDGE.PLEDGE_ID = CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO.FIELD_NUMERIC_VALUE', '', '', FALSE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'DISTRO_LINE', FALSE, 'DISTRO_LINE_ASSOCIATED_GIFT', 'DISTRO_LINE_ASSOCIATED_GIFT_', 'DISTRO_LINE_ASSOCIATED_GIFT.DISTRO_LINE_ID = CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO.ENTITY_ID', '', '', FALSE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', 'gift', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'GIFT', FALSE, 'GIFT', 'GIFT_', 'GIFT.GIFT_ID = DISTRO_LINE_ASSOCIATED_GIFT.GIFT_ID AND GIFT.IS_DELETED = 0', 'Associated ', '', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', 'gift', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'PAYMENT_SOURCE', FALSE, 'PAYMENT_SOURCE', 'GIFT_PAYMENT_SOURCE_', 'GIFT.PAYMENT_SOURCE_ID = PAYMENT_SOURCE.PAYMENT_SOURCE_ID AND PAYMENT_SOURCE.IS_DELETED = 0', '', 'Associated Payment Information', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'GIFT_PAYMENT_ADDRESS', 'GIFT_PAYMENT_ADDRESS_', 'GIFT.ADDRESS_ID = GIFT_PAYMENT_ADDRESS.ADDRESS_ID AND GIFT_PAYMENT_ADDRESS.IS_DELETED = 0', 'Associated Payment ', '', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', 'addressManagerEdit', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'GIFT_PAYMENT_ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND GIFT_PAYMENT_ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', 'Associated Payment ', '', FALSE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'PHONE', FALSE, 'GIFT_PAYMENT_PHONE', 'GIFT_PAYMENT_PHONE_', 'GIFT.PHONE_ID = GIFT_PAYMENT_PHONE.PHONE_ID AND GIFT_PAYMENT_PHONE.IS_DELETED = 0', 'Associated Payment ', '', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', 'phoneManagerEdit', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'GIFT_PAYMENT_PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = GIFT_PAYMENT_PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', 'Associated Payment ', '', FALSE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'DISTRO_LINE', FALSE, 'PLEDGE_DISTRO_LINE', 'PLEDGE_DISTRO_LINE_', 'PLEDGE_DISTRO_LINE.GIFT_ID = GIFT.GIFT_ID', '', 'Associated Donation Distribution Information', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, 'gift', 'distributionLines', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'GIFT_PAYMENT_ADDRESS_AH', 'GIFT_PAYMENT_ADDRESS_AH_', 'GIFT_PAYMENT_ADDRESS_AH.ENTITY_TYPE = ''address'' AND GIFT_PAYMENT_ADDRESS_AH.ENTITY_ID = GIFT_PAYMENT_ADDRESS.ADDRESS_ID AND GIFT_PAYMENT_ADDRESS_AH.IS_DELETED = 0', 'Associated Donation Payment Address ', '', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'GIFT_PAYMENT_PHONE_AH', 'GIFT_PAYMENT_PHONE_AH_', 'GIFT_PAYMENT_PHONE_AH.ENTITY_TYPE = ''phone'' AND GIFT_PAYMENT_PHONE_AH.ENTITY_ID = GIFT_PAYMENT_PHONE.PHONE_ID AND GIFT_PAYMENT_PHONE_AH.IS_DELETED = 0', 'Associated Donation Payment Phone ', '', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, 'Associated Donation Payment ', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'GIFT_AH', 'GIFT_AH_', 'GIFT_AH.ENTITY_TYPE = ''gift'' AND GIFT_AH.ENTITY_ID = GIFT.GIFT_ID AND GIFT_AH.IS_DELETED = 0', 'Associated Donation ', '', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL', 'CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL_', 'CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL.FIELD_NAME = ''associatedPledgeId'' AND CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL.ENTITY_TYPE = ''giftinkinddetail'' AND PLEDGE.PLEDGE_ID = CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL.FIELD_NUMERIC_VALUE', '', '', FALSE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'GIFT_IN_KIND', FALSE, 'GIFT_IN_KIND', 'GIFT_IN_KIND_', 'GIFT_IN_KIND.GIFT_IN_KIND_ID IN (SELECT GIFT_IN_KIND_ID FROM GIFT_IN_KIND_DETAIL GIFT_IN_KIND_DETAIL_ASSOCIATED_GIFT WHERE GIFT_IN_KIND_DETAIL_ASSOCIATED_GIFT.GIK_DETAIL_ID = CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL.ENTITY_ID) AND GIFT_IN_KIND.IS_DELETED = 0', 'Associated Gift In Kind ', '', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, '', '', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'GIFT_IN_KIND_DETAIL', FALSE, 'PLEDGE_GIFT_IN_KIND_DETAIL', 'PLEDGE_GIFT_IN_KIND_DETAIL_', 'PLEDGE_GIFT_IN_KIND_DETAIL.GIFT_IN_KIND_ID = GIFT_IN_KIND.GIFT_IN_KIND_ID', '', 'Associated Gift In Kind Details', TRUE, (SELECT MAX(SORT_ORDER) FROM THEGURU_VIEW_JOIN WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID) + 1, 'giftInKind', 'details', '', FALSE
FROM THEGURU_VIEW WHERE PRIMARY_TABLE = 'PLEDGE';


-- Add exclusions for new gift fields
INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_PLEDGES_DISTRIBUTIONS', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_DESC';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_PLEDGES_DISTRIBUTIONS', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_LDN';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_PLEDGES_DISTRIBUTIONS', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_SDN';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_PLEDGES', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_DESC';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_PLEDGES', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_LDN';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_PLEDGES', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_SDN';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_CONSTITUENTS_PLEDGES', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_DESC';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_CONSTITUENTS_PLEDGES', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_LDN';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_CONSTITUENTS_PLEDGES', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_SDN';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_DESC';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_LDN';

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS', 'GIFT_PAYMENT_SOURCE_PAYMENT_TYPE_SDN';

CALL GENERATE_VIEWS('VW_V2_PLEDGES');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_PLEDGES');

CALL GENERATE_VIEWS('VW_V2_PLEDGES_DISTRIBUTIONS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_PLEDGES_DISTRIBUTIONS');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_PLEDGES');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_PLEDGES');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS');

COMMIT;