
-- Move V1 constituent and contact info view back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Constituents');


UPDATE REPORTDATASUBSOURCE
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_CONSTITUENTS_CONTACTINFORMATION');


-- Add new constituent & contact information data sub-source
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Constituents');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Constituents & Contact Information', 0, 'VW_V2_CONSTITUENTS_CONTACTINFORMATION', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', 'Constituents and their addresses, email addresses and phone numbers');



-- VW_V2_GIFTS_IN_KIND
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_CONSTITUENTS_CONTACTINFORMATION', 'Constituents & Contact Information', 'VW_V2_CONSTITUENTS', TRUE, 'VW_V2_CONSTITUENTS', 'VW_V2_CONSTITUENTS_', TRUE, 80, '';

SET @VIEW_ID = LAST_INSERT_ID();


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID', TRUE, 1, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', FALSE, 2;

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Address ', TRUE, 3;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID', TRUE, 4, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', FALSE, 5;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID', TRUE, 5, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', FALSE, 6;

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Phone ', TRUE, 7;


CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_CONTACTINFORMATION');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_CONTACTINFORMATION');
