UPDATE THEGURU_VIEW
SET WHERE_CLAUSE =
  CASE
    WHEN IFNULL(WHERE_CLAUSE, '') = '' THEN CONCAT(PRIMARY_TABLE_ALIAS, '.IS_DELETED = 0')
    ELSE CONCAT(WHERE_CLAUSE, ' AND ', PRIMARY_TABLE_ALIAS, '.IS_DELETED = 0')
  END
WHERE PRIMARY_TABLE IN
('CONSTITUENT',
'PAYMENT_SOURCE')
AND IFNULL(WHERE_CLAUSE, '') NOT LIKE '%IS_DELETED = 0%';

UPDATE THEGURU_VIEW_JOIN
SET JOIN_CRITERIA = 
  CASE
    WHEN IFNULL(JOIN_CRITERIA, '') = '' THEN CONCAT(JOIN_TABLE_ALIAS, '.IS_DELETED = 0')
    ELSE CONCAT(JOIN_CRITERIA, ' AND ', JOIN_TABLE_ALIAS, '.IS_DELETED = 0')
  END
WHERE JOIN_TABLE IN
('CONSTITUENT',
'PAYMENT_SOURCE')
AND IFNULL(JOIN_CRITERIA, '') NOT LIKE '%IS_DELETED = 0%';

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'CONSTITUENT', 'Contact Details', 'Inactive', '${COLUMN_PREFIX}INACTIVE', 'CONSTITUENT_INACTIVE', 6;
