START TRANSACTION;

UPDATE THEGURU_VIEW_JOIN
SET SORT_ORDER = SORT_ORDER + 4
WHERE VIEW_ID IN
(SELECT VIEW_ID FROM THEGURU_VIEW WHERE VIEW_NAME IN ('VW_V2_GIFTS', 'VW_V2_GIFTS_DISTRIBUTIONS'))
AND SORT_ORDER > 8;

DELETE FROM THEGURU_VIEW_JOIN
WHERE VIEW_ID IN
(SELECT VIEW_ID FROM THEGURU_VIEW WHERE VIEW_NAME IN ('VW_V2_GIFTS', 'VW_V2_GIFTS_DISTRIBUTIONS'))
AND SORT_ORDER = 8;

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'PLEDGE', FALSE, 'PLEDGE', 'PLEDGE_', 'PLEDGE.PLEDGE_ID = CUSTOM_FIELD_ASSOCIATEDPLEDGE.FIELD_VALUE', 'Associated ', '', TRUE, 8, '', '', 'pledge', TRUE
FROM THEGURU_VIEW
WHERE VIEW_NAME IN ('VW_V2_GIFTS', 'VW_V2_GIFTS_DISTRIBUTIONS');

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'DISTRO_LINE', FALSE, 'PLEDGE_DISTRO_LINE', 'PLEDGE_DISTRO_LINE_', 'PLEDGE.PLEDGE_ID = PLEDGE_DISTRO_LINE.PLEDGE_ID', '', 'Associated Pledge Distribution Information', TRUE, 9, 'pledge', 'distributionLines', '', FALSE
FROM THEGURU_VIEW
WHERE VIEW_NAME IN ('VW_V2_GIFTS', 'VW_V2_GIFTS_DISTRIBUTIONS');

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'SCHEDULED_ITEM', FALSE, 'SCHEDULED_ITEM', 'SCHEDULED_ITEM_', 'SCHEDULED_ITEM.SOURCE_ENTITY_ID = PLEDGE.PLEDGE_ID AND SCHEDULED_ITEM.SOURCE_ENTITY = ''pledge''', 'Associated Pledge Payment ', '', TRUE, 10, '', '', '', FALSE
FROM THEGURU_VIEW
WHERE VIEW_NAME IN ('VW_V2_GIFTS', 'VW_V2_GIFTS_DISTRIBUTIONS');

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'SCHEDULED_ITEM', FALSE, 'SCHEDULED_ITEM_REMINDER', 'SCHEDULED_ITEM_REMINDER_', 'SCHEDULED_ITEM_REMINDER.SOURCE_ENTITY_ID = SCHEDULED_ITEM.SCHEDULED_ITEM_ID AND SCHEDULED_ITEM_REMINDER.SOURCE_ENTITY = ''scheduleditem''', 'Associated Pledge Reminder ', '', TRUE, 11, '', '', '', FALSE
FROM THEGURU_VIEW
WHERE VIEW_NAME IN ('VW_V2_GIFTS', 'VW_V2_GIFTS_DISTRIBUTIONS');

INSERT THEGURU_VIEW_JOIN
  (VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX,
  FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES)
SELECT
  VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PLEDGE_AH', 'PLEDGE_AH_', 'PLEDGE_AH.ENTITY_TYPE = ''pledge'' AND PLEDGE_AH.ENTITY_ID = PLEDGE.PLEDGE_ID AND PLEDGE_AH.IS_DELETED = 0', 'Associated Pledge ', '', TRUE, 12, '', '', '', FALSE
FROM THEGURU_VIEW
WHERE VIEW_NAME IN ('VW_V2_GIFTS', 'VW_V2_GIFTS_DISTRIBUTIONS');

CALL GENERATE_VIEWS('VW_V2_GIFTS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_GIFTS');

CALL GENERATE_VIEWS('VW_V2_GIFTS_DISTRIBUTIONS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_GIFTS_DISTRIBUTIONS');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_GIFTS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_GIFTS');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS');

COMMIT;
