
-- Move V1 gift in kind views back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Transactions');

UPDATE REPORTDATASUBSOURCE
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_GIFTS_IN_KIND', 'VW_GIFTS_IN_KIND_DETAILS');


-- Move V1 constituent & gift in kind views back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Constituents & Transactions');

UPDATE REPORTDATASUBSOURCE
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_CONSTITUENTS_GIFTS_IN_KIND', 'VW_CONSTITUENTS_GIFTS_IN_KIND_DETAILS');


-- Add new gift in kind data sub-sources
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Transactions');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Gifts In Kind', 0, 'VW_V2_GIFTS_IN_KIND', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', NULL);

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Gifts In Kind & Details', 0, 'VW_V2_GIFTS_IN_KIND_DETAILS', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', NULL);


-- Add new constituent & gift in kind data sub-sources
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Constituents & Transactions');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Constituents & Gifts In Kind', 0, 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', NULL);

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Constituents & Gifts In Kind Details', 0, 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', NULL);


 
-- VW_V2_GIFTS_IN_KIND
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_GIFTS_IN_KIND', 'Gifts In Kind', 'GIFT_IN_KIND', FALSE, 'GIFT_IN_KIND', 'GIFT_IN_KIND_', TRUE, 200, '';


INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Gift In Kind Reference Number', '${COLUMN_PREFIX}GIFT_IN_KIND_ID', 'GIFT_IN_KIND_ID', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Account Number', 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)', 'ACCOUNT_NUMBER', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Account Name', 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)', 'ACCOUNT_NAME', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Transaction Date', '${COLUMN_PREFIX}TRANSACTION_DATE', 'TRANSACTION_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Gift Reference Number', '${COLUMN_PREFIX}GIFT_ID', 'GIFT_ID', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Create Date', '${COLUMN_PREFIX}CREATE_DATE', 'CREATE_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Update Date', '${COLUMN_PREFIX}UPDATE_DATE', 'UPDATE_DATE', 4;
    
INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'GIFT_IN_KIND', 'MOTIVATION_CODE';

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Motivation Short Display Name', 'IFNULL(GETPICKLISTDISPLAYVALUE(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE), ${COLUMN_PREFIX}OTHER_MOTIVATION)', 'MOTIVATION_CODE_SHORT_DISPLAY_NAME', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Motivation Long Display Name', 'GETPICKLISTLONGDESCRIPTION(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE)', 'MOTIVATION_CODE_LONG_DISPLAY_NAME', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND', 'Donation Information', 'Motivation Description', 'GETPICKLISTDETAIL(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE)', 'MOTIVATION_CODE_DESCRIPTION', 1;
    
    
-- VW_V2_GIFTS_IN_KIND
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_GIFTS_IN_KIND_DETAILS', 'Gifts In Kind & Details', 'GIFT_IN_KIND', FALSE, 'GIFT_IN_KIND', 'GIFT_IN_KIND_', TRUE, 210, '';

SET @VIEW_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME)
SELECT
	@VIEW_ID, 'LEFT', 'GIFT_IN_KIND_DETAIL', FALSE, 'GIFT_IN_KIND_DETAIL', 'GIFT_IN_KIND_DETAIL_', 'GIFT_IN_KIND_DETAIL.GIFT_IN_KIND_ID = GIFT_IN_KIND.GIFT_IN_KIND_ID', 'Gift In Kind Details', TRUE, 1, 'giftInKind', 'details';

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Gift In Kind Detail Reference Number', '${COLUMN_PREFIX}GIK_DETAIL_ID', 'GIK_DETAIL_ID', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Fair Market Value', '${COLUMN_PREFIX}FAIR_MARKET_VALUE', 'FAIR_MARKET_VALUE', 5;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Designation GL Part 1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''01-GLPART1'')', 'PROJECT_CODE_GLPART1', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Designation GL Part 2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''02-GLPART2'')', 'PROJECT_CODE_GLPART2', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Designation GL Part 3', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''03-GLPART3'')', 'PROJECT_CODE_GLPART3', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Designation GL Part 4', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''04-GLPART4'')', 'PROJECT_CODE_GLPART4', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Designation GL Account Code', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''GLAccountCode'')', 'PROJECT_CODE_GLACCOUNTCODE', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Designation GL Account String 1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''AccountString1'')', 'PROJECT_CODE_GLACCOUNTSTRING1', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Designation GL Account String 2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''AccountString2'')', 'PROJECT_CODE_GLACCOUNTSTRING2', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Category Short Display Name', 'GETPICKLISTDISPLAYVALUE(''gikCategory'', ${COLUMN_PREFIX}CATEGORY)', 'CATEGORY_SHORT_DISPLAY_NAME', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Category Long Display Name', 'GETPICKLISTLONGDESCRIPTION(''gikCategory'', ${COLUMN_PREFIX}CATEGORY)', 'CATEGORY_LONG_DISPLAY_NAME', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT_IN_KIND_DETAIL', 'Gift In Kind Details', 'Category Description', 'GETPICKLISTDETAIL(''gikCategory'', ${COLUMN_PREFIX}CATEGORY)', 'CATEGORY_DESCRIPTION', 1;

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
	(TABLE_NAME, FIELD_NAME)
SELECT
	'GIFT_IN_KIND_DETAIL', 'details.customFieldMap[onBehalfOfReadOnly]';


-- VW_V2_GIFTS_IN_KIND
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_CONSTITUENTS_GIFTS_IN_KIND', 'Constituents & Gifts In Kind', 'VW_V2_CONSTITUENTS', TRUE, 'VW_V2_CONSTITUENTS', 'VW_V2_CONSTITUENTS_', TRUE, 280, '';

SET @VIEW_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME)
SELECT
	@VIEW_ID, 'LEFT', 'VW_V2_GIFTS_IN_KIND', TRUE, 'VW_V2_GIFTS_IN_KIND', '', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_V2_GIFTS_IN_KIND.GIFT_IN_KIND_CONSTITUENT_ID', '', TRUE, 1, '', '';


-- VW_V2_GIFTS_IN_KIND_DETAILS
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS', 'Constituents & Gifts In Kind & Details', 'VW_V2_CONSTITUENTS', TRUE, 'VW_V2_CONSTITUENTS', 'VW_V2_CONSTITUENTS_', TRUE, 280, '';

SET @VIEW_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME)
SELECT
	@VIEW_ID, 'LEFT', 'VW_V2_GIFTS_IN_KIND_DETAILS', TRUE, 'VW_V2_GIFTS_IN_KIND_DETAILS', '', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_V2_GIFTS_IN_KIND_DETAILS.GIFT_IN_KIND_CONSTITUENT_ID', '', TRUE, 1, '', '';


CALL GENERATE_VIEWS('VW_V2_GIFTS_IN_KIND');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_GIFTS_IN_KIND');

CALL GENERATE_VIEWS('VW_V2_GIFTS_IN_KIND_DETAILS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_GIFTS_IN_KIND_DETAILS');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_GIFTS_IN_KIND');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_GIFTS_IN_KIND');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS');
