INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
  (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT DISTINCT
  'CONSTITUENT', 'Demographic Information', 'Age', 'AGE(CAST(GETCUSTOMDATEFIELD(${COLUMN_PREFIX}CONSTITUENT_ID, ''constituent'', ''individual.birthDate'') AS DATETIME), IFNULL(CAST(GETCUSTOMDATEFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.deceased'') AS DATETIME), CURDATE()))', 'AGE', 2
FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'CONSTITUENT'
AND DISPLAY_NAME = 'Age');

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
  (TABLE_NAME, FIELD_NAME)
SELECT DISTINCT
  'CONSTITUENT', 'customFieldMap[age:individual.birthDate]'
FROM THEGURU_TABLE_FIELD_EXCLUSIONS
WHERE NOT EXISTS 
(SELECT * FROM THEGURU_TABLE_FIELD_EXCLUSIONS
WHERE TABLE_NAME = 'CONSTITUENT'
AND FIELD_NAME = 'customFieldMap[age:individual.birthDate]');