START TRANSACTION;
--
-- Definition of table `REPORTCHARTSETTINGSSERIES`
--
DROP TABLE IF EXISTS `REPORTCHARTSETTINGS_REPORTCHARTSETTINGSSERIES`;
DROP TABLE IF EXISTS `REPORTCHARTSETTINGSSERIES`;
CREATE TABLE `REPORTCHARTSETTINGSSERIES` (
  `REPORTCHARTSETTINGS_SERIES_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OPERATION` varchar(255) DEFAULT NULL,
  `SERIES` bigint(20) DEFAULT NULL,
  `SERIES_LABEL` varchar(255) DEFAULT NULL,  
  PRIMARY KEY (`REPORTCHARTSETTINGS_SERIES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



-- JOIN TABLE

CREATE TABLE `REPORTCHARTSETTINGS_REPORTCHARTSETTINGSSERIES` (
  `REPORTCHARTSETTINGS_REPORTCHARTSETTINGS_ID` BIGINT(20) NOT NULL,
  `REPORTCHARTSETTINGSSERIES_REPORTCHARTSETTINGS_SERIES_ID` BIGINT(20) NOT NULL,
  `REPORTCHARTSETTINGS_SERIES_ID` INT(11) NOT NULL,
  PRIMARY KEY (`REPORTCHARTSETTINGS_REPORTCHARTSETTINGS_ID`,`REPORTCHARTSETTINGS_SERIES_ID`),
  UNIQUE KEY `REPORTCHARTSETTINGSSERIES_REPORTCHARTSETTINGS_SERIES_ID` (`REPORTCHARTSETTINGSSERIES_REPORTCHARTSETTINGS_SERIES_ID`),
  KEY `FK49E399521C41CB4B` (`REPORTCHARTSETTINGS_REPORTCHARTSETTINGS_ID`),
  KEY `FK49E3995264D9E2D9` (`REPORTCHARTSETTINGSSERIES_REPORTCHARTSETTINGS_SERIES_ID`),
  CONSTRAINT `FK49E3995264D9E2D9` FOREIGN KEY (`REPORTCHARTSETTINGSSERIES_REPORTCHARTSETTINGS_SERIES_ID`) REFERENCES `REPORTCHARTSETTINGSSERIES` (`REPORTCHARTSETTINGS_SERIES_ID`),
  CONSTRAINT `FK49E399521C41CB4B` FOREIGN KEY (`REPORTCHARTSETTINGS_REPORTCHARTSETTINGS_ID`) REFERENCES `REPORTCHARTSETTINGS` (`REPORTCHARTSETTINGS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

COMMIT;