ALTER TABLE REPORTDATASOURCE
ADD SORT_ORDER INT NOT NULL DEFAULT 999;

UPDATE REPORTDATASOURCE
SET SORT_ORDER = 10
WHERE REPORT_NAME = 'Orange Leap - V2';

UPDATE REPORTDATASOURCE
SET SORT_ORDER = 20
WHERE REPORT_NAME = 'Orange Leap';
