DELIMITER $$

DROP PROCEDURE IF EXISTS UPDATE_REPORTFIELD_FIELD_DEFINITIONS$$

CREATE PROCEDURE UPDATE_REPORTFIELD_FIELD_DEFINITIONS()
BEGIN
    DROP TABLE IF EXISTS THEGURU_FIELD_DEFINITIONS_COMPARISON;

    CREATE TABLE THEGURU_FIELD_DEFINITIONS_COMPARISON
    SELECT
        CAST(REPORTDATASUBSOURCE.VIEW_NAME AS CHAR(255)) AS VIEW_NAME,
        REPORTFIELDGROUP.NAME AS FIELD_GROUP,
        REPORTFIELD.REPORTFIELD_ID,
        REPORTFIELD.COLUMN_NAME,
        REPORTFIELD.ALIAS_NAME,
        REPORTFIELD.DISPLAY_NAME,
        REPORTFIELD.FIELD_TYPE,
        REPORTFIELD.PRIMARY_KEYS
    FROM REPORTDATASUBSOURCE
    JOIN REPORTFIELDGROUP_REPORTDATASUBSOURCE ON reportDataSubSource_REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
    JOIN REPORTFIELDGROUP ON REPORTFIELDGROUP_REPORTFIELDGROUP_ID = REPORTFIELDGROUP.REPORTFIELDGROUP_ID
    JOIN REPORTFIELD_REPORTFIELDGROUP ON REPORTFIELD_REPORTFIELDGROUP.reportFieldGroup_REPORTFIELDGROUP_ID = REPORTFIELDGROUP.REPORTFIELDGROUP_ID
    JOIN REPORTFIELD ON fields_REPORTFIELD_ID = REPORTFIELD.REPORTFIELD_ID
    WHERE REPORTDATASUBSOURCE.VIEW_NAME IN (SELECT VIEW_NAME FROM THEGURU_FIELD_DEFINITIONS)
    ORDER BY REPORTFIELDGROUP.NAME, REPORTFIELD.DISPLAY_NAME;

    ALTER TABLE THEGURU_FIELD_DEFINITIONS_COMPARISON ADD NEW_ALIAS_NAME VARCHAR(255);

    ALTER TABLE THEGURU_FIELD_DEFINITIONS_COMPARISON ADD TO_BE_DELETED BIT;

    ALTER TABLE THEGURU_FIELD_DEFINITIONS_COMPARISON ADD COLUMN THEGURU_FIELD_DEFINITIONS_COMPARISON_ID INT NOT NULL AUTO_INCREMENT,
    ADD PRIMARY KEY (THEGURU_FIELD_DEFINITIONS_COMPARISON_ID);

    CREATE INDEX IDX_THEGURU_FIELD_DEFINITIONS_COMPARISON_NEW_ALIAS_NAME ON THEGURU_FIELD_DEFINITIONS_COMPARISON(REPORTFIELD_ID);
    CREATE INDEX IDX_THEGURU_FIELD_DEFINITIONS_COMPARISON_SEARCH_VIEW_NAME ON THEGURU_FIELD_DEFINITIONS_COMPARISON (VIEW_NAME);
    CREATE INDEX IDX_THEGURU_FIELD_DEFINITIONS_COMPARISON_SEARCH_ALIAS_NAME ON THEGURU_FIELD_DEFINITIONS_COMPARISON (ALIAS_NAME);

   	-- Remove any extra exclusions based on view name
	DELETE FROM THEGURU_FIELD_DEFINITIONS
	WHERE EXISTS
	(SELECT * FROM THEGURU_TABLE_FIELD_EXCLUSIONS
	WHERE THEGURU_TABLE_FIELD_EXCLUSIONS.TABLE_NAME = THEGURU_FIELD_DEFINITIONS.VIEW_NAME
	AND THEGURU_TABLE_FIELD_EXCLUSIONS.FIELD_NAME = THEGURU_FIELD_DEFINITIONS.ALIAS_NAME);

    CALL UPDATE_THEGURU_FIELD_DEFINITIONS_COMPARISON();
    CALL UPDATE_REPORTFIELD_FROM_THEGURU_FIELD_DEFINITIONS_COMPARISON();

	DROP TABLE IF EXISTS THEGURU_FIELD_DEFINITIONS_COMPARISON;
END;$$