-- Move V1 views to V2 that have not been created in V2
DROP TABLE IF EXISTS TMP_REPORTDATASUBSOURCEUPDATE;

CREATE TABLE TMP_REPORTDATASUBSOURCEUPDATE
SELECT REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID,
(SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
WHERE DISPLAY_NAME =
(SELECT DISPLAY_NAME FROM REPORTDATASUBSOURCEGROUP WHERE REPORTDATASUBSOURCEGROUP.REPORTSUBSOURCEGROUP_ID = reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID)
AND REPORTSUBSOURCEGROUP_ID <> reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID) AS NEW_reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID
FROM REPORTDATASUBSOURCE
WHERE VIEW_NAME NOT LIKE 'VW_V2%'
AND NOT EXISTS
(SELECT * FROM REPORTDATASUBSOURCE B WHERE B.VIEW_NAME LIKE 'VW_V2%'
AND REPLACE(B.VIEW_NAME, 'V2_', '') = REPORTDATASUBSOURCE.VIEW_NAME);

UPDATE REPORTDATASUBSOURCE, TMP_REPORTDATASUBSOURCEUPDATE
SET REPORTDATASUBSOURCE.reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = NEW_reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID
WHERE TMP_REPORTDATASUBSOURCEUPDATE.REPORTSUBSOURCE_ID = REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID;

DROP TABLE IF EXISTS TMP_REPORTDATASUBSOURCEUPDATE;
