UPDATE THEGURU_TABLE_ADDITIONAL_FIELD
SET FIELD_TEXT = 'CONSTITUENT_ROLES.FIELD_VALUE'
WHERE TABLE_NAME = 'CONSTITUENT'
AND FIELD_ALIAS = 'CONSTITUENT_ROLE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD
SET FIELD_TEXT = 'DONOR_PROFILES.FIELD_VALUE'
WHERE TABLE_NAME = 'CONSTITUENT'
AND FIELD_ALIAS = 'DONOR_PROFILE';


UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS 
SET DISPLAY_NAME = 'Profile Type Short Display Name',
COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '' END, CONSTITUENT_ROLES.FIELD_VALUE)',
ALIAS_NAME = 'CONSTITUENT_ROLE_SDN'
WHERE TABLE_NAME = 'CONSTITUENT' AND DISPLAY_NAME = 'Profile Type';

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
VALUES
('CONSTITUENT', 'Contact Details', 'Profile Type Long Display Name',
'GETPICKLISTLONGDESCRIPTION(CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '' END, CONSTITUENT_ROLES.FIELD_VALUE)',
'CONSTITUENT_ROLE_LDN', 1);

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
VALUES
('CONSTITUENT', 'Contact Details', 'Profile Type Description',
'GETPICKLISTDETAIL(CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '' END, CONSTITUENT_ROLES.FIELD_VALUE)',
'CONSTITUENT_ROLE_DESC', 1);


UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS 
SET DISPLAY_NAME = 'Donor Profile Short Display Name',
COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''customFieldMap[donorProfiles]'', ${COLUMN_PREFIX}DONOR_PROFILE)',
ALIAS_NAME = 'DONOR_PROFILE_SDN'
WHERE TABLE_NAME = 'CONSTITUENT' AND DISPLAY_NAME = 'Donor Profile';

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
VALUES
('CONSTITUENT', 'Contact Details', 'Donor Profile Long Display Name',
'GETPICKLISTLONGDESCRIPTION(''customFieldMap[donorProfiles]'', ${COLUMN_PREFIX}DONOR_PROFILE)',
'DONOR_PROFILE_LDN', 1);

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
VALUES
('CONSTITUENT', 'Contact Details', 'Donor Profile Description',
'GETPICKLISTDETAIL(''customFieldMap[donorProfiles]'', ${COLUMN_PREFIX}DONOR_PROFILE)',
'DONOR_PROFILE_DESC', 1);
