DELETE FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE 
WHERE reportDataSubSource_REPORTSUBSOURCE_ID =
  (SELECT REPORTSUBSOURCE_ID FROM REPORTDATASUBSOURCE WHERE DISPLAY_NAME = 'Constituents & Relationship Details')
AND reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = 600000;
