DELIMITER $$

DROP PROCEDURE IF EXISTS ADDCOLUMN_UPDATESCRIPT$$
CREATE PROCEDURE ADDCOLUMN_UPDATESCRIPT() BEGIN
	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='CHART_TITLE' AND TABLE_NAME='REPORTCHARTSETTINGS' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTCHARTSETTINGS ADD COLUMN
		`CHART_TITLE` varchar(255) DEFAULT NULL;
	END IF;

	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='CHART_SUB_TITLE' AND TABLE_NAME='REPORTCHARTSETTINGS' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTCHARTSETTINGS ADD COLUMN
		`CHART_SUB_TITLE` varchar(255) DEFAULT NULL;
	END IF;

	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='CATEGORY_AXIS_LABEL' AND TABLE_NAME='REPORTCHARTSETTINGS' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTCHARTSETTINGS ADD COLUMN
		`CATEGORY_AXIS_LABEL` varchar(255) DEFAULT NULL;
	END IF;
	
	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='VALUE_AXIS_LABEL' AND TABLE_NAME='REPORTCHARTSETTINGS' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTCHARTSETTINGS ADD COLUMN
		`VALUE_AXIS_LABEL` varchar(255) DEFAULT NULL;
	END IF;
	
END;
$$

DELIMITER ;

CALL ADDCOLUMN_UPDATESCRIPT();

 DROP PROCEDURE ADDCOLUMN_UPDATESCRIPT;