START TRANSACTION;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'ADDRESS', 'Address Information', 'Zip/Postal Code Key', '${COLUMN_PREFIX}POSTAL_CODE_KEY', 'POSTAL_CODE_KEY', 1, '${COLUMN_PREFIX}POSTAL_CODE_KEY'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'ADDRESS'
AND COLUMN_NAME = '${COLUMN_PREFIX}POSTAL_CODE_KEY');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'ADDRESS', 'Address Information', 'Activation Status', '${COLUMN_PREFIX}ACTIVATION_STATUS', 'ACTIVATION_STATUS', 1, '${COLUMN_PREFIX}ACTIVATION_STATUS'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'ADDRESS'
AND COLUMN_NAME = '${COLUMN_PREFIX}ACTIVATION_STATUS');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'ADDRESS', 'Address Information', 'Seasonal Start Date (Date / Time)', '${COLUMN_PREFIX}SEASONAL_START_DATE', 'SEASONAL_START_DATE', 4, '${COLUMN_PREFIX}SEASONAL_START_DATE'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'ADDRESS'
AND COLUMN_NAME = '${COLUMN_PREFIX}SEASONAL_START_DATE');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'ADDRESS', 'Address Information', 'Seasonal End Date (Date / Time)', '${COLUMN_PREFIX}SEASONAL_END_DATE', 'SEASONAL_END_DATE', 4, '${COLUMN_PREFIX}SEASONAL_END_DATE'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'ADDRESS'
AND COLUMN_NAME = '${COLUMN_PREFIX}SEASONAL_END_DATE');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'PHONE', 'Phone Information', 'Activation Status', '${COLUMN_PREFIX}ACTIVATION_STATUS', 'ACTIVATION_STATUS', 1, '${COLUMN_PREFIX}ACTIVATION_STATUS'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'PHONE'
AND COLUMN_NAME = '${COLUMN_PREFIX}ACTIVATION_STATUS');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'PHONE', 'Phone Information', 'Seasonal Start Date (Date / Time)', '${COLUMN_PREFIX}SEASONAL_START_DATE', 'SEASONAL_START_DATE', 4, '${COLUMN_PREFIX}SEASONAL_START_DATE'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'PHONE'
AND COLUMN_NAME = '${COLUMN_PREFIX}SEASONAL_START_DATE');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'PHONE', 'Phone Information', 'Seasonal End Date (Date / Time)', '${COLUMN_PREFIX}SEASONAL_END_DATE', 'SEASONAL_END_DATE', 4, '${COLUMN_PREFIX}SEASONAL_END_DATE'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'PHONE'
AND COLUMN_NAME = '${COLUMN_PREFIX}SEASONAL_END_DATE');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'EMAIL', 'Email Information', 'Activation Status', '${COLUMN_PREFIX}ACTIVATION_STATUS', 'ACTIVATION_STATUS', 1, '${COLUMN_PREFIX}ACTIVATION_STATUS'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'EMAIL'
AND COLUMN_NAME = '${COLUMN_PREFIX}ACTIVATION_STATUS');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'EMAIL', 'Email Information', 'Seasonal Start Date (Date / Time)', '${COLUMN_PREFIX}SEASONAL_START_DATE', 'SEASONAL_START_DATE', 4, '${COLUMN_PREFIX}SEASONAL_START_DATE'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'EMAIL'
AND COLUMN_NAME = '${COLUMN_PREFIX}SEASONAL_START_DATE');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, SOURCE_COLUMN_NAME)
SELECT
'EMAIL', 'Email Information', 'Seasonal End Date (Date / Time)', '${COLUMN_PREFIX}SEASONAL_END_DATE', 'SEASONAL_END_DATE', 4, '${COLUMN_PREFIX}SEASONAL_END_DATE'
FROM (SELECT 1 AS A) A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'EMAIL'
AND COLUMN_NAME = '${COLUMN_PREFIX}SEASONAL_END_DATE');

UPDATE REPORTCUSTOMFILTERDEFINITION
SET SQL_TEXT = '(STR_TO_DATE(''{0}'', ''%m/%d/%Y'') BETWEEN CASE WHEN [VIEWNAME].ADDRESS_ACTIVATION_STATUS = ''temporary'' THEN [VIEWNAME].ADDRESS_TEMPORARY_START_DATE WHEN [VIEWNAME].ADDRESS_ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), [VIEWNAME].ADDRESS_SEASONAL_START_DATE, [VIEWNAME].ADDRESS_SEASONAL_END_DATE) = 1 THEN STR_TO_DATE(''{0}'', ''%m/%d/%Y'') WHEN [VIEWNAME].ADDRESS_ACTIVATION_STATUS = ''seasonal'' THEN ADDDATE(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), 1) WHEN [VIEWNAME].ADDRESS_ACTIVATION_STATUS = ''permanent'' AND [VIEWNAME].ADDRESS_EFFECTIVE_DATE IS NOT NULL THEN [VIEWNAME].ADDRESS_EFFECTIVE_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END AND CASE WHEN [VIEWNAME].ADDRESS_ACTIVATION_STATUS = ''temporary'' THEN [VIEWNAME].ADDRESS_TEMPORARY_END_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END)'
WHERE SQL_TEXT = '(STR_TO_DATE(''{0}'', ''%m/%d/%Y'') BETWEEN CASE WHEN ADDRESS_ACTIVATION_STATUS = ''temporary'' THEN ADDRESS_TEMPORARY_START_DATE WHEN ADDRESS_ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), ADDRESS_SEASONAL_START_DATE, ADDRESS_SEASONAL_END_DATE) = 1 THEN STR_TO_DATE(''{0}'', ''%m/%d/%Y'') WHEN ADDRESS_ACTIVATION_STATUS = ''seasonal'' THEN ADDDATE(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), 1) WHEN ADDRESS_ACTIVATION_STATUS = ''permanent'' AND ADDRESS_EFFECTIVE_DATE IS NOT NULL THEN ADDRESS_EFFECTIVE_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END AND CASE WHEN ADDRESS_ACTIVATION_STATUS = ''temporary'' THEN ADDRESS_TEMPORARY_END_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END)';

UPDATE REPORTCUSTOMFILTERDEFINITION
SET SQL_TEXT = '(STR_TO_DATE(''{0}'', ''%m/%d/%Y'') BETWEEN CASE WHEN [VIEWNAME].EMAIL_ACTIVATION_STATUS = ''temporary'' THEN [VIEWNAME].EMAIL_TEMPORARY_START_DATE WHEN [VIEWNAME].EMAIL_ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), [VIEWNAME].EMAIL_SEASONAL_START_DATE, [VIEWNAME].EMAIL_SEASONAL_END_DATE) = 1 THEN STR_TO_DATE(''{0}'', ''%m/%d/%Y'') WHEN [VIEWNAME].EMAIL_ACTIVATION_STATUS = ''seasonal'' THEN ADDDATE(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), 1) WHEN [VIEWNAME].EMAIL_ACTIVATION_STATUS = ''permanent'' AND [VIEWNAME].EMAIL_EFFECTIVE_DATE IS NOT NULL THEN [VIEWNAME].EMAIL_EFFECTIVE_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END AND CASE WHEN [VIEWNAME].EMAIL_ACTIVATION_STATUS = ''temporary'' THEN [VIEWNAME].EMAIL_TEMPORARY_END_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END)'
WHERE SQL_TEXT = '(STR_TO_DATE(''{0}'', ''%m/%d/%Y'') BETWEEN CASE WHEN EMAIL_ACTIVATION_STATUS = ''temporary'' THEN EMAIL_TEMPORARY_START_DATE WHEN EMAIL_ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), EMAIL_SEASONAL_START_DATE, EMAIL_SEASONAL_END_DATE) = 1 THEN STR_TO_DATE(''{0}'', ''%m/%d/%Y'') WHEN EMAIL_ACTIVATION_STATUS = ''seasonal'' THEN ADDDATE(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), 1) WHEN EMAIL_ACTIVATION_STATUS = ''permanent'' AND EMAIL_EFFECTIVE_DATE IS NOT NULL THEN EMAIL_EFFECTIVE_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END AND CASE WHEN EMAIL_ACTIVATION_STATUS = ''temporary'' THEN EMAIL_TEMPORARY_END_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END)';

UPDATE REPORTCUSTOMFILTERDEFINITION
SET SQL_TEXT = '(STR_TO_DATE(''{0}'', ''%m/%d/%Y'') BETWEEN CASE WHEN [VIEWNAME].PHONE_ACTIVATION_STATUS = ''temporary'' THEN [VIEWNAME].PHONE_TEMPORARY_START_DATE WHEN [VIEWNAME].PHONE_ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), [VIEWNAME].PHONE_SEASONAL_START_DATE, [VIEWNAME].PHONE_SEASONAL_END_DATE) = 1 THEN STR_TO_DATE(''{0}'', ''%m/%d/%Y'') WHEN [VIEWNAME].PHONE_ACTIVATION_STATUS = ''seasonal'' THEN ADDDATE(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), 1) WHEN [VIEWNAME].PHONE_ACTIVATION_STATUS = ''permanent'' AND [VIEWNAME].PHONE_EFFECTIVE_DATE IS NOT NULL THEN [VIEWNAME].PHONE_EFFECTIVE_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END AND CASE WHEN [VIEWNAME].PHONE_ACTIVATION_STATUS = ''temporary'' THEN [VIEWNAME].PHONE_TEMPORARY_END_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END)'
WHERE SQL_TEXT = '(STR_TO_DATE(''{0}'', ''%m/%d/%Y'') BETWEEN CASE WHEN PHONE_ACTIVATION_STATUS = ''temporary'' THEN PHONE_TEMPORARY_START_DATE WHEN PHONE_ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), PHONE_SEASONAL_START_DATE, PHONE_SEASONAL_END_DATE) = 1 THEN STR_TO_DATE(''{0}'', ''%m/%d/%Y'') WHEN PHONE_ACTIVATION_STATUS = ''seasonal'' THEN ADDDATE(STR_TO_DATE(''{0}'', ''%m/%d/%Y''), 1) WHEN PHONE_ACTIVATION_STATUS = ''permanent'' AND PHONE_EFFECTIVE_DATE IS NOT NULL THEN PHONE_EFFECTIVE_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END AND CASE WHEN PHONE_ACTIVATION_STATUS = ''temporary'' THEN PHONE_TEMPORARY_END_DATE ELSE STR_TO_DATE(''{0}'', ''%m/%d/%Y'') END)';

COMMIT;