START TRANSACTION;

INSERT REPORTSEGMENTATIONTYPE (COLUMN_NAME, SEGMENTATIONTYPE)
SELECT 'COMMUNICATION_HISTORY_CONSTITUENT_ID', 'Constituent Segmentation';

INSERT REPORTSEGMENTATIONTYPE (COLUMN_NAME, SEGMENTATIONTYPE)
SELECT 'COMMUNICATION_HISTORY_GIFT_ID', 'Gift Segmentation';

INSERT REPORTSEGMENTATIONTYPE (COLUMN_NAME, SEGMENTATIONTYPE)
SELECT 'COMMUNICATION_HISTORY_DISTRO_LINE_ID', 'Gift Distribution Segmentation';

INSERT REPORTSEGMENTATIONTYPE (COLUMN_NAME, SEGMENTATIONTYPE)
SELECT 'COMMUNICATION_HISTORY_ADJUSTED_GIFT_ID', 'Adjusted Gift Segmentation';

INSERT REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE
(reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID, reportDataSubSource_REPORTSUBSOURCE_ID,
REPORTSUBSOURCE_ID, REPORTSEGMENTATIONTYPE_ID)
SELECT REPORTSEGMENTATIONTYPE_ID, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTSEGMENTATIONTYPE_ID
FROM REPORTSEGMENTATIONTYPE, REPORTDATASUBSOURCE
WHERE COLUMN_NAME IN 
('COMMUNICATION_HISTORY_GIFT_ID', 'COMMUNICATION_HISTORY_ADJUSTED_GIFT_ID',
'COMMUNICATION_HISTORY_DISTRO_LINE_ID', 'COMMUNICATION_HISTORY_CONSTITUENT_ID')
AND VIEW_NAME IN ('VW_V2_TOUCHPOINTS', 'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION');

COMMIT;