DELIMITER $$

DROP PROCEDURE IF EXISTS UPDATE_THEGURU_FIELD_DEFINITIONS_COMPARISON$$

CREATE PROCEDURE UPDATE_THEGURU_FIELD_DEFINITIONS_COMPARISON()
BEGIN
	DECLARE CSR_END INT DEFAULT 0;

    -- THEGURU_FIELD_DEFINITIONS Variables
    DECLARE VAR_FIELD_ID INT;
    DECLARE VAR_VIEW_NAME VARCHAR(255);
    DECLARE VAR_FIELD_GROUP VARCHAR(255);
    DECLARE VAR_COLUMN_NAME VARCHAR(500);
    DECLARE VAR_ALIAS_NAME VARCHAR(255);
    DECLARE VAR_DISPLAY_TEXT VARCHAR(255);
    DECLARE VAR_FIELD_TYPE INT;
    DECLARE VAR_PRIMARY_KEY VARCHAR(255);
    DECLARE VAR_PICKLIST_NAME_ID VARCHAR(255);
    DECLARE VAR_PICKLIST_ITEM_NAME VARCHAR(255);
    DECLARE VAR_CUSTOM_FIELD_ENTITY_TYPE VARCHAR(255);
	DECLARE VAR_CUSTOM_FIELD_ENTITY_ID VARCHAR(255);
    DECLARE VAR_CUSTOM_FIELD_FIELD_NAME VARCHAR(255);
    DECLARE VAR_JOIN_ID BIGINT;
    DECLARE VAR_SOURCE_COLUMN_NAME VARCHAR(2000);
	DECLARE VAR_CONSTITUENT_JOIN_FIELD VARCHAR(255);
	DECLARE VAR_DYNAMIC_PRIMARY_KEY VARCHAR(255);
	DECLARE VAR_PICKLIST_CUSTOM_FIELD BIT;

	DECLARE CSR_VIEWS CURSOR FOR
        SELECT DISTINCT VIEW_NAME FROM THEGURU_FIELD_DEFINITIONS;

	DECLARE CSR_FIELDS CURSOR FOR
        SELECT FIELD_ID, FIELD_GROUP, COLUMN_NAME, ALIAS_NAME, DISPLAY_TEXT, FIELD_TYPE, PRIMARY_KEY,
        PICKLIST_NAME_ID, PICKLIST_ITEM_NAME, CUSTOM_FIELD_ENTITY_TYPE, CUSTOM_FIELD_ENTITY_ID, CUSTOM_FIELD_FIELD_NAME, JOIN_ID, SOURCE_COLUMN_NAME,
		CONSTITUENT_JOIN_FIELD, DYNAMIC_PRIMARY_KEY, PICKLIST_CUSTOM_FIELD
        FROM THEGURU_FIELD_DEFINITIONS
        WHERE VIEW_NAME = VAR_VIEW_NAME;

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET CSR_END = 1;


    -- Update the alias names for fields where the column name matches, but the alias is different
    -- This will handle some instances where the generated alias name is different than the original, but the field is the same
    UPDATE THEGURU_FIELD_DEFINITIONS_COMPARISON, THEGURU_FIELD_DEFINITIONS
    SET THEGURU_FIELD_DEFINITIONS_COMPARISON.NEW_ALIAS_NAME = THEGURU_FIELD_DEFINITIONS.ALIAS_NAME
    WHERE THEGURU_FIELD_DEFINITIONS.COLUMN_NAME = THEGURU_FIELD_DEFINITIONS_COMPARISON.COLUMN_NAME
    AND THEGURU_FIELD_DEFINITIONS.VIEW_NAME = THEGURU_FIELD_DEFINITIONS_COMPARISON.VIEW_NAME
    AND THEGURU_FIELD_DEFINITIONS.ALIAS_NAME <> THEGURU_FIELD_DEFINITIONS_COMPARISON.ALIAS_NAME
    AND THEGURU_FIELD_DEFINITIONS.ALIAS_NAME IS NOT NULL;

    UPDATE REPORTFIELD
    SET ALIAS_NAME = (SELECT NEW_ALIAS_NAME FROM THEGURU_FIELD_DEFINITIONS_COMPARISON WHERE REPORTFIELD.REPORTFIELD_ID = THEGURU_FIELD_DEFINITIONS_COMPARISON.REPORTFIELD_ID)
    WHERE REPORTFIELD_ID IN (SELECT REPORTFIELD_ID FROM THEGURU_FIELD_DEFINITIONS_COMPARISON WHERE NEW_ALIAS_NAME IS NOT NULL);

    UPDATE THEGURU_FIELD_DEFINITIONS_COMPARISON
    SET ALIAS_NAME = NEW_ALIAS_NAME
    WHERE NEW_ALIAS_NAME IS NOT NULL;


	OPEN CSR_VIEWS;
	VIEWS_LOOP: LOOP
		FETCH CSR_VIEWS INTO
			VAR_VIEW_NAME;

		IF CSR_END THEN
			LEAVE VIEWS_LOOP;
		END IF;

        -- Mark all the fields as to be deleted for this view and the process will reset the flag as it updates each field
        -- Those that don't get updated were not in the generated fields and should be deleted
        UPDATE THEGURU_FIELD_DEFINITIONS_COMPARISON
        SET TO_BE_DELETED = 1
        WHERE VIEW_NAME = VAR_VIEW_NAME;

        OPEN CSR_FIELDS;
        FIELDS_LOOP: LOOP
            FETCH CSR_FIELDS INTO
                VAR_FIELD_ID, VAR_FIELD_GROUP, VAR_COLUMN_NAME, VAR_ALIAS_NAME, VAR_DISPLAY_TEXT, VAR_FIELD_TYPE, VAR_PRIMARY_KEY,
                VAR_PICKLIST_NAME_ID, VAR_PICKLIST_ITEM_NAME, VAR_CUSTOM_FIELD_ENTITY_TYPE, VAR_CUSTOM_FIELD_ENTITY_ID, VAR_CUSTOM_FIELD_FIELD_NAME, VAR_JOIN_ID,
                VAR_SOURCE_COLUMN_NAME, VAR_CONSTITUENT_JOIN_FIELD, VAR_DYNAMIC_PRIMARY_KEY, VAR_PICKLIST_CUSTOM_FIELD;

            IF CSR_END THEN
                LEAVE FIELDS_LOOP;
            END IF;

            -- If the field exists in the comparison table based on the alias name, update it, if not, add it.
            IF EXISTS
            (SELECT * FROM THEGURU_FIELD_DEFINITIONS_COMPARISON
            WHERE VIEW_NAME = VAR_VIEW_NAME
            AND ALIAS_NAME = VAR_ALIAS_NAME) THEN
                UPDATE THEGURU_FIELD_DEFINITIONS_COMPARISON
                SET FIELD_GROUP = VAR_FIELD_GROUP,
                COLUMN_NAME = VAR_COLUMN_NAME,
                ALIAS_NAME = VAR_ALIAS_NAME,
                DISPLAY_NAME = VAR_DISPLAY_TEXT,
                FIELD_TYPE = VAR_FIELD_TYPE,
                PRIMARY_KEYS = VAR_PRIMARY_KEY,
                TO_BE_DELETED = 0,
                PICKLIST_NAME_ID = VAR_PICKLIST_NAME_ID,
                PICKLIST_ITEM_NAME = VAR_PICKLIST_ITEM_NAME,
                CUSTOM_FIELD_ENTITY_TYPE = VAR_CUSTOM_FIELD_ENTITY_TYPE,
				CUSTOM_FIELD_ENTITY_ID = VAR_CUSTOM_FIELD_ENTITY_ID,
                CUSTOM_FIELD_FIELD_NAME = VAR_CUSTOM_FIELD_FIELD_NAME,
                JOIN_ID = VAR_JOIN_ID,
                SOURCE_COLUMN_NAME = VAR_SOURCE_COLUMN_NAME,
				CONSTITUENT_JOIN_FIELD = VAR_CONSTITUENT_JOIN_FIELD,
				DYNAMIC_PRIMARY_KEYS = VAR_DYNAMIC_PRIMARY_KEY,
				PICKLIST_CUSTOM_FIELD = VAR_PICKLIST_CUSTOM_FIELD
                WHERE VIEW_NAME = VAR_VIEW_NAME
                AND ALIAS_NAME = VAR_ALIAS_NAME;
            ELSE
                INSERT THEGURU_FIELD_DEFINITIONS_COMPARISON
                    (VIEW_NAME, FIELD_GROUP, REPORTFIELD_ID, COLUMN_NAME, ALIAS_NAME, DISPLAY_NAME, FIELD_TYPE, PRIMARY_KEYS, TO_BE_DELETED,
                    PICKLIST_NAME_ID, PICKLIST_ITEM_NAME, CUSTOM_FIELD_ENTITY_TYPE, CUSTOM_FIELD_ENTITY_ID, CUSTOM_FIELD_FIELD_NAME, JOIN_ID,
					SOURCE_COLUMN_NAME, CONSTITUENT_JOIN_FIELD, DYNAMIC_PRIMARY_KEYS, PICKLIST_CUSTOM_FIELD)
                SELECT
                    VAR_VIEW_NAME, VAR_FIELD_GROUP, NULL, VAR_COLUMN_NAME, VAR_ALIAS_NAME, VAR_DISPLAY_TEXT, VAR_FIELD_TYPE, VAR_PRIMARY_KEY, 0,
                    VAR_PICKLIST_NAME_ID, VAR_PICKLIST_ITEM_NAME, VAR_CUSTOM_FIELD_ENTITY_TYPE, VAR_CUSTOM_FIELD_ENTITY_ID, VAR_CUSTOM_FIELD_FIELD_NAME, VAR_JOIN_ID, 
                    VAR_SOURCE_COLUMN_NAME, VAR_CONSTITUENT_JOIN_FIELD, VAR_DYNAMIC_PRIMARY_KEY, VAR_PICKLIST_CUSTOM_FIELD;
            END IF;
        END LOOP;
        CLOSE CSR_FIELDS;
        SET CSR_END = 0;

	END LOOP;
	CLOSE CSR_VIEWS;
	SET CSR_END = 0;
END;
$$
