INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT', 'Donation Information', 'Gift Create Date', '${COLUMN_PREFIX}CREATE_DATE', 'CREATE_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'GIFT', 'Donation Information', 'Gift Update Date', '${COLUMN_PREFIX}UPDATE_DATE', 'UPDATE_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PLEDGE', 'Pledge Information', 'Pledge Create Date', '${COLUMN_PREFIX}CREATE_DATE', 'CREATE_DATE', 4;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PLEDGE', 'Pledge Information', 'Pledge Update Date', '${COLUMN_PREFIX}UPDATE_DATE', 'UPDATE_DATE', 4;