START TRANSACTION;

INSERT THEGURU_TABLE_FIELD_EXCLUSIONS
(TABLE_NAME, FIELD_NAME)
SELECT
'ADJUSTED_GIFT', 'ADJUSTED_STATUS';

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
'ADJUSTED_GIFT', 'Adjustment Information', 'Adjustment Status Short Display Name', 'GETPICKLISTDISPLAYVALUE(''adjustedStatus'', ${COLUMN_PREFIX}ADJUSTED_STATUS)', 'ADJUSTED_STATUS_SDN', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
'ADJUSTED_GIFT', 'Adjustment Information', 'Adjustment Status Long Display Name', 'GETPICKLISTLONGDESCRIPTION(''adjustedStatus'', ${COLUMN_PREFIX}ADJUSTED_STATUS)', 'ADJUSTED_STATUS_LDN', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
'ADJUSTED_GIFT', 'Adjustment Information', 'Adjustment Status Description', 'GETPICKLISTDETAIL(''adjustedStatus'', ${COLUMN_PREFIX}ADJUSTED_STATUS)', 'ADJUSTED_STATUS_DESC', 1;

CALL GENERATE_VIEWS('VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_GIFTS');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_GIFTS');

COMMIT;