START TRANSACTION;

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET PICKLIST_CUSTOM_FIELD = TRUE
WHERE DISPLAY_NAME LIKE '% GL %'
AND DISPLAY_NAME NOT LIKE '%GL Account String%';

UPDATE REPORTFIELD
SET ALIAS_NAME = REPLACE(ALIAS_NAME, 'PROJECT_CODE', 'PROJECTCODE')
WHERE DISPLAY_NAME LIKE '% GL %';

UPDATE REPORTFIELD
SET ALIAS_NAME = REPLACE(ALIAS_NAME, '_GLPART1', '_01GLPART1')
WHERE DISPLAY_NAME LIKE '% GL %';

UPDATE REPORTFIELD
SET ALIAS_NAME = REPLACE(ALIAS_NAME, '_GLPART2', '_02GLPART2')
WHERE DISPLAY_NAME LIKE '% GL %';

UPDATE REPORTFIELD
SET ALIAS_NAME = REPLACE(ALIAS_NAME, '_GLPART3', '_03GLPART3')
WHERE DISPLAY_NAME LIKE '% GL %';

UPDATE REPORTFIELD
SET ALIAS_NAME = REPLACE(ALIAS_NAME, '_GLPART4', '_04GLPART4')
WHERE DISPLAY_NAME LIKE '% GL %';

COMMIT