START TRANSACTION;

UPDATE THEGURU_VIEW
SET WHERE_CLAUSE = CONCAT(WHERE_CLAUSE, ' AND VW_V2_GIFTS.GIFT_TYPE = ''MONETARY_GIFT''')
WHERE PRIMARY_TABLE = 'GIFT'
AND WHERE_CLAUSE NOT LIKE '%VW_V2_GIFTS.GIFT_TYPE = ''MONETARY_GIFT''%';

UPDATE THEGURU_VIEW_JOIN
SET JOIN_CRITERIA = CONCAT(JOIN_CRITERIA, ' AND GIFT.GIFT_TYPE = ''MONETARY_GIFT''')
WHERE JOIN_TABLE = 'GIFT'
AND JOIN_CRITERIA NOT LIKE '%GIFT.GIFT_TYPE = ''MONETARY_GIFT''%';

COMMIT;