START TRANSACTION;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, PICKLIST_CUSTOM_FIELD, PICKLIST_NAME_ID, PICKLIST_ITEM_NAME, CUSTOM_FIELD_ENTITY_TYPE, CUSTOM_FIELD_ENTITY_ID, CUSTOM_FIELD_FIELD_NAME, SOURCE_COLUMN_NAME, CONSTITUENT_JOIN_FIELD)
SELECT 'COMMUNICATION_HISTORY', 'Touch Point Information', 'Constituent ID', '${COLUMN_PREFIX}CONSTITUENT_ID', 'CONSTITUENT_ID', '2', FALSE, NULL, NULL, NULL, NULL, NULL, '${COLUMN_PREFIX}CONSTITUENT_ID', NULL
FROM (SELECT 1 AS A) AS A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'COMMUNICATION_HISTORY'
AND COLUMN_NAME = '${COLUMN_PREFIX}CONSTITUENT_ID');

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
(TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE, PICKLIST_CUSTOM_FIELD, PICKLIST_NAME_ID, PICKLIST_ITEM_NAME, CUSTOM_FIELD_ENTITY_TYPE, CUSTOM_FIELD_ENTITY_ID, CUSTOM_FIELD_FIELD_NAME, SOURCE_COLUMN_NAME, CONSTITUENT_JOIN_FIELD)
SELECT 'COMMUNICATION_HISTORY', 'Touch Point Information', 'Gift Distribution ID', '${COLUMN_PREFIX}DISTRO_LINE_ID', 'DISTRO_LINE_ID', '2', FALSE, NULL, NULL, NULL, NULL, NULL, '${COLUMN_PREFIX}DISTRO_LINE_ID', NULL
FROM (SELECT 1 AS A) AS A
WHERE NOT EXISTS
(SELECT * FROM THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
WHERE TABLE_NAME = 'COMMUNICATION_HISTORY'
AND COLUMN_NAME = '${COLUMN_PREFIX}DISTRO_LINE_ID');

COMMIT;