START TRANSACTION;

INSERT INTO REPORTCUSTOMFILTERDEFINITION
(REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
SELECT
REPORTCUSTOMFILTERDEFINITION_ID + 50,
'Gift Totals - Account has given at least $[GIFTAMOUNT] in deductible gifts in the [DATE_PERIOD]',
REPLACE(REPLACE(SQL_TEXT, 'SUM(ADJUSTED_AMOUNT)', 'SUM(ADJUSTED_DEDUCTIBLE_AMOUNT)'), 'AND YEAR(DONATION_DATE) = {1}', '{1}'),
'Gift Totals - Account has given at least $<input class="customCriteria" objectname="reportFilters[INDEXREPLACEMENT].reportCustomFilter.reportCustomFilterCriteria[0].criteria" value="{0}"/> in deductible gifts in the {lookupReferenceBean:datePeriodList}'
FROM REPORTCUSTOMFILTERDEFINITION
WHERE DISPLAY_TEXT = 'Gift Totals - Account has given at least $[GIFTAMOUNT] in year [GIFTYEAR]';


INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
(reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION_ID)
SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION.REPORTCUSTOMFILTERDEFINITION_ID + 50, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTCUSTOMFILTERDEFINITION.REPORTCUSTOMFILTERDEFINITION_ID + 50
FROM REPORTCUSTOMFILTERDEFINITION
JOIN REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE ON reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = REPORTCUSTOMFILTERDEFINITION.REPORTCUSTOMFILTERDEFINITION_ID
WHERE DISPLAY_TEXT = 'Gift Totals - Account has given at least $[GIFTAMOUNT] in year [GIFTYEAR]'
AND NOT EXISTS 
(SELECT * FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE B 
WHERE B.reportCustomFilterDefinitions_REPORTCUSTOMFILTERDEFINITION_ID = REPORTCUSTOMFILTERDEFINITION.REPORTCUSTOMFILTERDEFINITION_ID + 50
AND B.reportDataSubSource_REPORTSUBSOURCE_ID = REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE.reportDataSubSource_REPORTSUBSOURCE_ID
AND B.REPORTSUBSOURCE_ID = REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID
AND B.REPORTCUSTOMFILTERDEFINITION_ID = REPORTCUSTOMFILTERDEFINITION.REPORTCUSTOMFILTERDEFINITION_ID + 50)
;

COMMIT;