START TRANSACTION;

-- Move V1 gift in kind views back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Transactions');

UPDATE REPORTDATASUBSOURCE
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_PAYMENTHISTORY');


-- Move V1 constituent & gift in kind views back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Constituents & Transactions');

UPDATE REPORTDATASUBSOURCE
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_CONSTITUENTS_PAYMENTHISTORY');


-- Add new payment history data sub-sources
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Transactions');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Payment History', 0, 'VW_V2_PAYMENTHISTORY', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', NULL);


-- Add new constituent & payment history data sub-source
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Constituents & Transactions');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Constituents & Payment History', 0, 'VW_V2_CONSTITUENTS_PAYMENTHISTORY', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', NULL);


 
-- VW_V2_PAYMENTHISTORY
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_PAYMENTHISTORY', 'Payment History', 'PAYMENT_HISTORY', FALSE, 'PAYMENT_HISTORY', 'PAYMENT_HISTORY_', 'Payment History', TRUE, 220, '';

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PAYMENT_HISTORY', 'Payment History', 'Payment History ID', '${COLUMN_PREFIX}PAYMENT_HISTORY_ID', 'PAYMENT_HISTORY_ID', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PAYMENT_HISTORY', 'Payment History', 'Account Number', 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)', 'ACCOUNT_NUMBER', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PAYMENT_HISTORY', 'Payment History', 'Account Name', 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)', 'ACCOUNT_NAME', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PAYMENT_HISTORY', 'Payment History', 'Payment History Type', 'CASE ${COLUMN_PREFIX}PAYMENT_HISTORY_TYPE WHEN ''UNSPECIFIED'' THEN ''Unspecified'' WHEN ''GIFT'' THEN ''Gift'' WHEN ''ADJUSTED_GIFT'' THEN ''Adjusted Gift'' WHEN ''MEMBERSHIP'' THEN ''Membership'' WHEN ''ORDER'' THEN ''Order'' Else ${COLUMN_PREFIX}PAYMENT_HISTORY_TYPE END', 'PAYMENT_HISTORY_TYPE', 1;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PAYMENT_HISTORY', 'Payment History', 'Gift ID', '${COLUMN_PREFIX}GIFT_ID', 'GIFT_ID', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PAYMENT_HISTORY', 'Payment History', 'Adjusted Gift ID', '${COLUMN_PREFIX}ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ID', 2;

INSERT THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
    (TABLE_NAME, FIELD_GROUP, DISPLAY_NAME, COLUMN_NAME, ALIAS_NAME, FIELD_TYPE)
SELECT
    'PAYMENT_HISTORY', 'Payment History', 'Description', '${COLUMN_PREFIX}PAYMENT_DESC', 'PAYMENT_DESC', 1;


-- VW_V2_CONSTITUENTS_PAYMENTHISTORY
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_CONSTITUENTS_PAYMENTHISTORY', 'Constituents & Payment History', 'VW_V2_CONSTITUENTS', TRUE, 'VW_V2_CONSTITUENTS', 'VW_V2_CONSTITUENTS_', TRUE, 300, '';

SET @VIEW_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME)
SELECT
	@VIEW_ID, 'LEFT', 'VW_V2_PAYMENTHISTORY', TRUE, 'VW_V2_PAYMENTHISTORY', '', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = VW_V2_PAYMENTHISTORY.PAYMENT_HISTORY_CONSTITUENT_ID', '', TRUE, 1, '', '';


CALL GENERATE_VIEWS('VW_V2_PAYMENTHISTORY');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_PAYMENTHISTORY');

CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_PAYMENTHISTORY');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_PAYMENTHISTORY');

COMMIT;