START TRANSACTION;

-- Move V1 constituent & undeliverable contact info view back to the V1 group
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap'
    AND DISPLAY_NAME = 'Constituents');

UPDATE REPORTDATASUBSOURCE 
SET reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID = @REPORTDATASUBSOURCEGROUP_ID
WHERE VIEW_NAME IN ('VW_CONSTITUENTS_UNDELIVERABLECONTACTINFORMATION');

-- Add the new constituents & primary contact data source data sub-source
SET @REPORTDATASUBSOURCEGROUP_ID =
    (SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
    JOIN REPORTDATASOURCE ON REPORTSOURCE_ID = reportDataSource_REPORTSOURCE_ID
    WHERE REPORT_NAME = 'Orange Leap - V2'
    AND DISPLAY_NAME = 'Constituents');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME, DESCRIPTION)
VALUES
	('Constituents & Undeliverable Contact Information', 0, 'VW_V2_CONSTITUENTS_UNDELIVERABLECONTACTINFORMATION', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults', 'Constituents and their undeliverable addresses, email addresses and phone numbers');
 
 
-- VW_V2_CONSTITUENTS_UNDELIVERABLECONTACTINFORMATION
INSERT THEGURU_VIEW
	(VIEW_NAME, VIEW_DISPLAY_TEXT, PRIMARY_TABLE, PRIMARY_TABLE_IS_VIEW, PRIMARY_TABLE_ALIAS, PRIMARY_TABLE_COLUMN_PREFIX, INCLUDE_ALL_FIELDS, SORT_ORDER, WHERE_CLAUSE)
SELECT
	'VW_V2_CONSTITUENTS_UNDELIVERABLECONTACTINFORMATION', 'Constituents & Undeliverable Contact Information', 'VW_V2_CONSTITUENTS', TRUE, 'VW_V2_CONSTITUENTS', '', TRUE, 90, 'ADDRESS.ADDRESS_ID IS NOT NULL OR EMAIL.EMAIL_ID IS NOT NULL OR PHONE.PHONE_ID IS NOT NULL';

SET @VIEW_ID = LAST_INSERT_ID();


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.UNDELIVERABLE, 0) = 1', TRUE, 1, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', FALSE, 2;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.UNDELIVERABLE, 0) = 1', TRUE, 3, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', FALSE, 4;


INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER, FIELD_GROUP_PREFIX)
SELECT
	@VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.UNDELIVERABLE, 0) = 1', TRUE, 5, '';

INSERT THEGURU_VIEW_JOIN
	(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, INCLUDE_ALL_FIELDS, SORT_ORDER)
SELECT
	@VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', FALSE, 6;


CALL GENERATE_VIEWS('VW_V2_CONSTITUENTS_UNDELIVERABLECONTACTINFORMATION');
CALL GENERATE_FIELD_DEFINITIONS('VW_V2_CONSTITUENTS_UNDELIVERABLECONTACTINFORMATION');

COMMIT;