START TRANSACTION;

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET COLUMN_NAME = REPLACE(COLUMN_NAME, '(CONSTITUENT_CONSTITUENT_ID', '(${COLUMN_PREFIX}CONSTITUENT_ID')
WHERE DISPLAY_NAME = 'Age';

UPDATE REPORTFIELD
SET COLUMN_NAME =
REPLACE(COLUMN_NAME, '(CONSTITUENT_CONSTITUENT_ID',
CONCAT('(', REPLACE(REPLACE(COLUMN_NAME, 
'AGE(CAST(GETCUSTOMDATEFIELD(', ''),
', ''constituent'', ''individual.birthDate'') AS DATETIME), IFNULL(CAST(GETCUSTOMDATEFIELD(CONSTITUENT_CONSTITUENT_ID, ''constituent'', ''individual.deceased'') AS DATETIME), CURDATE()))', '')))
WHERE DISPLAY_NAME = 'Age'
AND COLUMN_NAME LIKE '%(CONSTITUENT_CONSTITUENT_ID%';

COMMIT;