-- Select * From THEGURU_VIEW WHERE PRIMARY_TABLE = 'VW_V2_CONSTITUENTS' ORDER BY SORT_ORDER

ALTER TABLE THEGURU_GENERATED_VIEWS MODIFY VIEW_TEXT LONGTEXT;

START TRANSACTION;

-- VW_V2_CONSTITUENTS_GIFTS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS';



-- VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS';




-- VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_ADJUSTED_GIFTS_DISTRIBUTIONS';




-- VW_V2_CONSTITUENTS_GIFTS_IN_KIND
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND';




-- VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS_IN_KIND_DETAILS';




-- VW_V2_CONSTITUENTS_PAYMENTHISTORY
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTHISTORY';




-- VW_V2_CONSTITUENTS_PAYMENTMETHODS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PAYMENTMETHODS';




-- VW_V2_CONSTITUENTS_PLEDGES
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES';




-- VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_PLEDGES_DISTRIBUTIONS';




-- VW_V2_CONSTITUENTS_RECURRINGGIFTS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS';




-- VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_RECURRINGGIFTS_DISTRIBUTIONS';




-- VW_V2_CONSTITUENTS_GIFTSUMMARIES
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES';




-- VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS
INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ADDRESS', FALSE, 'ADDRESS', 'ADDRESS_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = ADDRESS.CONSTITUENT_ID AND IFNULL(ADDRESS.IS_PRIMARY, 0) = 1 AND ADDRESS.IS_DELETED = 0', 'Primary ', NULL, TRUE, '1', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'ADDRESS_TYPE', 'ADDRESS_', 'ADDRESS_TYPE.ENTITY_TYPE = ''address'' AND ADDRESS.ADDRESS_ID = ADDRESS_TYPE.ENTITY_ID AND ADDRESS_TYPE.FIELD_NAME = ''addressType''', NULL, NULL, False, '2', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'ADDRESS_AH', 'ADDRESS_AH_', 'ADDRESS_AH.ENTITY_TYPE = ''address'' AND ADDRESS_AH.ENTITY_ID = ADDRESS.ADDRESS_ID AND ADDRESS_AH.IS_DELETED = 0', 'Primary Address ', NULL, TRUE, '7', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'EMAIL', FALSE, 'EMAIL', 'EMAIL_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = EMAIL.CONSTITUENT_ID AND IFNULL(EMAIL.IS_PRIMARY, 0) = 1 AND EMAIL.IS_DELETED = 0', 'Primary ', NULL, TRUE, '3', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'EMAIL_TYPE', 'EMAIL_', 'EMAIL_TYPE.ENTITY_TYPE = ''email'' AND EMAIL_TYPE.ENTITY_ID = EMAIL.EMAIL_ID AND EMAIL_TYPE.FIELD_NAME = ''emailType''', NULL, NULL, FALSE, '4', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'PHONE', FALSE, 'PHONE', 'PHONE_', 'VW_V2_CONSTITUENTS.CONSTITUENT_CONSTITUENT_ID = PHONE.CONSTITUENT_ID AND IFNULL(PHONE.IS_PRIMARY, 0) = 1 AND PHONE.IS_DELETED = 0', 'Primary ', NULL, TRUE, '5', NULL, NULL, NULL, FALSE, '0'
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

SET @VIEW_JOIN_ID = LAST_INSERT_ID();

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'CUSTOM_FIELD', FALSE, 'PHONE_TYPE', 'PHONE_', 'PHONE_TYPE.ENTITY_TYPE = ''phone'' AND PHONE_TYPE.ENTITY_ID = PHONE.PHONE_ID AND PHONE_TYPE.FIELD_NAME = ''phoneType''', NULL, NULL, FALSE, '6', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

INSERT THEGURU_VIEW_JOIN
(VIEW_ID, JOIN_TYPE, JOIN_TABLE, JOIN_TABLE_IS_VIEW, JOIN_TABLE_ALIAS, JOIN_TABLE_COLUMN_PREFIX, JOIN_CRITERIA, FIELD_GROUP_PREFIX, FIELD_GROUP_OVERRIDE, INCLUDE_ALL_FIELDS, SORT_ORDER, PARENT_ENTITY_TYPE, SUB_FIELD_NAME, DEFAULT_PAGE_TYPE, USE_PARENT_FIELD_GROUP_PREFIXES, REQUIRES_JOIN_ID)
SELECT VIEW_ID, 'LEFT', 'ATTRIBUTE_HISTORY', FALSE, 'PHONE_AH', 'PHONE_AH_', 'PHONE_AH.ENTITY_TYPE = ''phone'' AND PHONE_AH.ENTITY_ID = PHONE.PHONE_ID AND PHONE_AH.IS_DELETED = 0', 'Primary Phone ', NULL, TRUE, '8', NULL, NULL, NULL, FALSE, @VIEW_JOIN_ID
FROM THEGURU_VIEW WHERE VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';


COMMIT;