DELIMITER $$

DROP PROCEDURE IF EXISTS INSERTREPORTFIELDWITHALIAS$$

CREATE PROCEDURE INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS VARCHAR(255), ALIASNAME VARCHAR(255), COLUMNNAME VARCHAR(500), DISPLAYNAME VARCHAR(255), ISDEFAULT BIT, FIELDTYPE INT, FIELDGROUPID BIGINT,
PICKLISTNAMEID VARCHAR(255), SOURCECOLUMNNAME VARCHAR(2000), PICKLISTITEMNAME VARCHAR(255), CUSTOMFIELDENTITYTYPE VARCHAR(255), CUSTOMFIELDENTITYID VARCHAR(255), 
CUSTOMFIELDFIELDNAME VARCHAR(255), CONSTITUENTJOINFIELD VARCHAR(255), JOINID BIGINT, DYNAMICPRIMARYKEYS VARCHAR(255), PICKLISTCUSTOMFIELD BIT)
BEGIN
	INSERT INTO REPORTFIELD
	(AVERAGE, CAN_BE_SUMMARIZED, COLUMN_NAME, ALIAS_NAME, DISPLAY_NAME, IS_DEFAULT, IS_SUMMARIZED, LARGEST_VALUE, PERFORMSUMMARY,
	IS_SELECTED, SMALLEST_VALUE, FIELD_TYPE, RECORD_COUNT, PRIMARY_KEYS, PICKLIST_NAME_ID, PICKLIST_ITEM_NAME, JOIN_ID, SOURCE_COLUMN_NAME,
	CUSTOM_FIELD_ENTITY_TYPE, CUSTOM_FIELD_ENTITY_ID, CUSTOM_FIELD_FIELD_NAME, CONSTITUENT_JOIN_FIELD, DYNAMIC_PRIMARY_KEYS, PICKLIST_CUSTOM_FIELD)
	VALUES
	(b'0', b'0', COLUMNNAME, ALIASNAME, DISPLAYNAME, ISDEFAULT, b'0', b'0', b'0', b'0', b'0', FIELDTYPE, b'0', PRIMARYKEYS,
	PICKLISTNAMEID, PICKLISTITEMNAME, JOINID, SOURCECOLUMNNAME, CUSTOMFIELDENTITYTYPE, CUSTOMFIELDENTITYID, CUSTOMFIELDFIELDNAME, CONSTITUENTJOINFIELD,
	DYNAMICPRIMARYKEYS, PICKLISTCUSTOMFIELD);

	SET @REPORTFIELD_ID = LAST_INSERT_ID();
  
	INSERT REPORTFIELD_REPORTFIELDGROUP
	(FIELDS_REPORTFIELD_ID, REPORTFIELDGROUP_ID, REPORTFIELDGROUP_REPORTFIELDGROUP_ID, REPORTFIELD_ID)
	VALUES (@REPORTFIELD_ID, FIELDGROUPID, FIELDGROUPID ,@REPORTFIELD_ID);
END $$