ALTER TABLE REPORTDATASUBSOURCE
ADD COLUMN ALLOW_DYNAMIC_SQL_GENERATION BIT DEFAULT 0;

ALTER TABLE REPORTWIZARD
ADD COLUMN USE_DYNAMIC_SQL_GENERATION BIT DEFAULT 0;

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN PICKLIST_NAME_ID VARCHAR(255);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN PICKLIST_ITEM_NAME VARCHAR(255);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN CUSTOM_FIELD_ENTITY_TYPE VARCHAR(255);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN CUSTOM_FIELD_ENTITY_ID VARCHAR(255);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN CUSTOM_FIELD_FIELD_NAME VARCHAR(255);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN JOIN_ID BIGINT DEFAULT 0;

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN SOURCE_COLUMN_NAME VARCHAR(2000);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN CONSTITUENT_JOIN_FIELD VARCHAR(255);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN DYNAMIC_PRIMARY_KEY VARCHAR(255);

ALTER TABLE THEGURU_FIELD_DEFINITIONS
ADD COLUMN PICKLIST_CUSTOM_FIELD BIT DEFAULT 0;

ALTER TABLE REPORTFIELD
ADD COLUMN PICKLIST_ITEM_NAME VARCHAR(255);

ALTER TABLE REPORTFIELD
ADD COLUMN CUSTOM_FIELD_ENTITY_TYPE VARCHAR(255);

ALTER TABLE REPORTFIELD
ADD COLUMN CUSTOM_FIELD_ENTITY_ID VARCHAR(255);

ALTER TABLE REPORTFIELD
ADD COLUMN CUSTOM_FIELD_FIELD_NAME VARCHAR(255);

ALTER TABLE REPORTFIELD
ADD COLUMN JOIN_ID BIGINT DEFAULT 0;

ALTER TABLE REPORTFIELD
ADD COLUMN SOURCE_COLUMN_NAME VARCHAR(2000);

ALTER TABLE REPORTFIELD
ADD COLUMN CONSTITUENT_JOIN_FIELD VARCHAR(255);

ALTER TABLE REPORTFIELD
ADD COLUMN DYNAMIC_PRIMARY_KEYS VARCHAR(255);

ALTER TABLE REPORTFIELD
ADD COLUMN PICKLIST_CUSTOM_FIELD BIT DEFAULT 0;


ALTER TABLE THEGURU_VIEW_JOIN
ADD COLUMN REQUIRES_JOIN_ID BIGINT DEFAULT 0;


ALTER TABLE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
ADD COLUMN PICKLIST_NAME_ID VARCHAR(255);

ALTER TABLE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
ADD COLUMN PICKLIST_ITEM_NAME VARCHAR(255);

ALTER TABLE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
ADD COLUMN CUSTOM_FIELD_ENTITY_TYPE VARCHAR(255);

ALTER TABLE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
ADD COLUMN CUSTOM_FIELD_ENTITY_ID VARCHAR(255);

ALTER TABLE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
ADD COLUMN CUSTOM_FIELD_FIELD_NAME VARCHAR(255);

ALTER TABLE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
ADD COLUMN SOURCE_COLUMN_NAME VARCHAR(2000);

ALTER TABLE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
ADD COLUMN CONSTITUENT_JOIN_FIELD VARCHAR(255);


CREATE TABLE TEMP_THEGURU_VIEW_JOIN
SELECT * FROM THEGURU_VIEW_JOIN;

START TRANSACTION;

UPDATE THEGURU_VIEW_JOIN SET SORT_ORDER = 1 WHERE SORT_ORDER IS NULL;

UPDATE REPORTDATASUBSOURCE
SET ALLOW_DYNAMIC_SQL_GENERATION = 0;

UPDATE REPORTDATASUBSOURCE
SET ALLOW_DYNAMIC_SQL_GENERATION = 1
WHERE VIEW_NAME IN
(SELECT VIEW_NAME FROM THEGURU_VIEW WHERE IFNULL(SQL_OVERRIDE, '') = '' AND PRIMARY_TABLE NOT LIKE '(select%');

UPDATE REPORTWIZARD
SET USE_DYNAMIC_SQL_GENERATION = 0;

UPDATE THEGURU_VIEW
SET WHERE_CLAUSE = 'ADDRESS_CURRENT.UNDELIVERABLE = ''0'' AND ADDRESS_CURRENT.INACTIVE= ''0'' AND ((ADDRESS_CURRENT.ACTIVATION_STATUS = ''temporary'' AND ADDRESS_CURRENT.TEMPORARY_START_DATE <= NOW() AND ADDRESS_CURRENT.TEMPORARY_END_DATE >= NOW()) OR (ADDRESS_CURRENT.ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(now(), ADDRESS_CURRENT.SEASONAL_START_DATE, ADDRESS_CURRENT.SEASONAL_END_DATE)) OR (ADDRESS_CURRENT.ACTIVATION_STATUS = ''permanent'' AND ADDRESS_CURRENT.EFFECTIVE_DATE <= NOW())) AND ADDRESS_CURRENT.IS_DELETED = 0'
WHERE VIEW_NAME = 'VW_V2_ADDRESSES_CURRENT'
AND WHERE_CLAUSE = 'ADDRESS_CURRENT.UNDELIVERABLE = ''0'' AND ADDRESS_CURRENT.INACTIVE= ''0'' AND ((ADDRESS_CURRENT.ACTIVATION_STATUS = ''temporary'' AND ADDRESS_CURRENT.TEMPORARY_START_DATE <= NOW() AND ADDRESS_CURRENT.TEMPORARY_END_DATE >= NOW()) OR (ADDRESS_CURRENT.ACTIVATION_STATUS = ''seasonal'' AND IS_IN_SEASON(now(), SEASONAL_START_DATE, SEASONAL_END_DATE)) OR (ADDRESS_CURRENT.ACTIVATION_STATUS = ''permanent'' AND ADDRESS_CURRENT.EFFECTIVE_DATE <= NOW())) AND ADDRESS_CURRENT.IS_DELETED = 0';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADJUSTED_GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADJUSTED_GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADJUSTED_GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'AGP_ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADJUSTED_GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'AGP_PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_ADDRESSES'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_ADDRESSES'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_CONTACTINFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_CONTACTINFORMATION'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'EMAIL')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_CONTACTINFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'EMAIL_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_CONTACTINFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_CONTACTINFORMATION'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'EMAIL')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_EMAILS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'EMAIL_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'VW_V2_GIFTS_DISTRIBUTIONS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTDISTRIBUTIONS'
AND JOIN_TABLE = 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE_ALIAS = 'VW_V2_AGD';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'VW_V2_GIFTS_DISTRIBUTIONS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_GIFTS'
AND JOIN_TABLE = 'VW_V2_ADJUSTED_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE_ALIAS = 'VW_V2_AGD';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_PHONENUMBERS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = '')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_PHONENUMBERS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'EMAIL')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'EMAIL_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_CONSTITUENTS_PRIMARYCONTACTINFORMATION'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'DISTRO_LINE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDPLEDGE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDPLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'PLEDGE'
AND JOIN_TABLE_ALIAS = 'PLEDGE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'DISTRO_LINE'
AND JOIN_TABLE_ALIAS = 'PLEDGE_DISTRO_LINE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'SCHEDULED_ITEM'
AND JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'SCHEDULED_ITEM'
AND JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM_REMINDER';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PLEDGE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'DISTRO_LINE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDRECURRINGGIFT';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDRECURRINGGIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'VW_V2_RECURRINGGIFTS_DISTRIBUTIONS'
AND JOIN_TABLE_ALIAS = 'VW_V2_RECURRINGGIFTS_DISTRIBUTIONS';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'DISTRO_LINE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDPLEDGE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDPLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'PLEDGE'
AND JOIN_TABLE_ALIAS = 'PLEDGE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'DISTRO_LINE'
AND JOIN_TABLE_ALIAS = 'PLEDGE_DISTRO_LINE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'SCHEDULED_ITEM'
AND JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'SCHEDULED_ITEM'
AND JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM_REMINDER';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PLEDGE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PLEDGE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'DISTRO_LINE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDRECURRINGGIFT';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDRECURRINGGIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'VW_V2_RECURRINGGIFTS_DISTRIBUTIONS'
AND JOIN_TABLE_ALIAS = 'VW_V2_RECURRINGGIFTS_DISTRIBUTIONS';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_GIFTS_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PAYMENTMETHOD_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PAYMENTMETHODS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PAYMENTMETHOD_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PAYMENTMETHODS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PAYMENTMETHOD_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PAYMENTMETHODS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PAYMENTMETHOD_ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PAYMENTMETHOD_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PAYMENTMETHODS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PAYMENTMETHOD_PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PICKLIST_ITEM')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PICKLISTS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PICKLIST_ITEM_CUSTOM_FIELD';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'SCHEDULED_ITEM'
AND JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM_REMINDER';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'DISTRO_LINE'
AND JOIN_TABLE_ALIAS = 'DISTRO_LINE_ASSOCIATED_GIFT';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'DISTRO_LINE_ASSOCIATED_GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'GIFT'
AND JOIN_TABLE_ALIAS = 'GIFT';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'PAYMENT_SOURCE'
AND JOIN_TABLE_ALIAS = 'PAYMENT_SOURCE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'ADDRESS'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'PHONE'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'DISTRO_LINE'
AND JOIN_TABLE_ALIAS = 'PLEDGE_DISTRO_LINE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'GIFT_IN_KIND'
AND JOIN_TABLE_ALIAS = 'GIFT_IN_KIND';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_IN_KIND')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES'
AND JOIN_TABLE = 'GIFT_IN_KIND_DETAIL'
AND JOIN_TABLE_ALIAS = 'PLEDGE_GIFT_IN_KIND_DETAIL';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'SCHEDULED_ITEM'
AND JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM_REMINDER';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDGIFTDISTRO')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'DISTRO_LINE'
AND JOIN_TABLE_ALIAS = 'DISTRO_LINE_ASSOCIATED_GIFT';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'DISTRO_LINE_ASSOCIATED_GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'GIFT'
AND JOIN_TABLE_ALIAS = 'GIFT';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'PAYMENT_SOURCE'
AND JOIN_TABLE_ALIAS = 'PAYMENT_SOURCE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'ADDRESS'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'PHONE'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'DISTRO_LINE'
AND JOIN_TABLE_ALIAS = 'PLEDGE_DISTRO_LINE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_PAYMENT_PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'GIFT_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'CUSTOM_FIELD_ASSOCIATEDGIFTINKINDDETAIL')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'GIFT_IN_KIND'
AND JOIN_TABLE_ALIAS = 'GIFT_IN_KIND';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'GIFT_IN_KIND')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_PLEDGES_DISTRIBUTIONS'
AND JOIN_TABLE = 'GIFT_IN_KIND_DETAIL'
AND JOIN_TABLE_ALIAS = 'PLEDGE_GIFT_IN_KIND_DETAIL';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'RECURRING_GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_RECURRINGGIFTS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'RECURRING_GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_RECURRINGGIFTS'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_RECURRINGGIFTS'
AND JOIN_TABLE = 'SCHEDULED_ITEM'
AND JOIN_TABLE_ALIAS = 'SCHEDULED_ITEM_REMINDER';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'RECURRING_GIFT_PAYMENT_ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_RECURRINGGIFTS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'RGP_ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'RECURRING_GIFT_PAYMENT_PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_RECURRINGGIFTS'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'RGP_PHONE_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'ADDRESS_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'EMAIL')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'EMAIL_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION'
AND JOIN_TABLE = 'CUSTOM_FIELD'
AND JOIN_TABLE_ALIAS = 'PHONE_TYPE';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'ADDRESS')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'ADDRESS_AH';

UPDATE THEGURU_VIEW_JOIN, THEGURU_VIEW
SET REQUIRES_JOIN_ID = (SELECT JOIN_ID FROM TEMP_THEGURU_VIEW_JOIN B
WHERE B.VIEW_ID = THEGURU_VIEW_JOIN.VIEW_ID
AND B.JOIN_TABLE_ALIAS = 'PHONE')
WHERE THEGURU_VIEW_JOIN.VIEW_ID = THEGURU_VIEW.VIEW_ID
AND VIEW_NAME = 'VW_V2_TOUCHPOINTS_CONSTITUENT_INFORMATION'
AND JOIN_TABLE = 'ATTRIBUTE_HISTORY'
AND JOIN_TABLE_ALIAS = 'PHONE_AH';

UPDATE THEGURU_VIEW_JOIN
SET REQUIRES_JOIN_ID = 0
WHERE REQUIRES_JOIN_ID IS NULL;



-- THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS Updates

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_NAME',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = 'picklist',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ID',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = '${COLUMN_PREFIX}CUSTOM_FIELD_FIELD_NAME'
AND TABLE_NAME = 'PICKLIST';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = 'picklist',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ID',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = '${COLUMN_PREFIX}CUSTOM_FIELD_FIELD_VALUE'
AND TABLE_NAME = 'PICKLIST';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_NAME',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = 'picklistitem',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ID',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = '${COLUMN_PREFIX}CUSTOM_FIELD_FIELD_NAME'
AND TABLE_NAME = 'PICKLIST_ITEM';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = 'picklistitem',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ID',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = '${COLUMN_PREFIX}CUSTOM_FIELD_FIELD_VALUE'
AND TABLE_NAME = 'PICKLIST_ITEM';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'customFieldMap[addressType]',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'address',
CUSTOM_FIELD_ENTITY_ID = 'ADDRESS_ID',
CUSTOM_FIELD_FIELD_NAME = 'addressType',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''customFieldMap[addressType]'', ${COLUMN_PREFIX}ADDRESS_TYPE)'
AND TABLE_NAME = 'ADDRESS';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '''' END',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'constituent',
CUSTOM_FIELD_ENTITY_ID = 'CONSTITUENT_ID',
CUSTOM_FIELD_FIELD_NAME = 'constituentIndividualRoles',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '''' END, ${COLUMN_PREFIX}CONSTITUENT_ROLE)'
AND TABLE_NAME = 'CONSTITUENT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'customFieldMap[donorProfiles]',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'constituent',
CUSTOM_FIELD_ENTITY_ID = 'CONSTITUENT_ID',
CUSTOM_FIELD_FIELD_NAME = 'donorProfiles',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''customFieldMap[donorProfiles]'', ${COLUMN_PREFIX}DONOR_PROFILE)'
AND TABLE_NAME = 'CONSTITUENT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'customFieldMap[phoneType]',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'phone',
CUSTOM_FIELD_ENTITY_ID = 'PHONE_ID',
CUSTOM_FIELD_FIELD_NAME = 'phoneType',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''customFieldMap[phoneType]'', ${COLUMN_PREFIX}PHONE_TYPE)'
AND TABLE_NAME = 'PHONE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'PLEDGE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'PLEDGE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'RECURRING_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'RECURRING_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'PAYMENT_SOURCE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'PAYMENT_SOURCE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'posted',
PICKLIST_ITEM_NAME = 'CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''posted'', CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END)'
AND TABLE_NAME = 'GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'posted',
PICKLIST_ITEM_NAME = 'CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(''posted'', CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END)'
AND TABLE_NAME = 'GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'posted',
PICKLIST_ITEM_NAME = 'CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(''posted'', CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END)'
AND TABLE_NAME = 'GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'IFNULL(${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE, ${COLUMN_PREFIX}OTHER_MOTIVATION)',
PICKLIST_NAME_ID = 'motivationCode',
PICKLIST_ITEM_NAME = 'MOTIVATION_CODE',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'IFNULL(GETPICKLISTDISPLAYVALUE(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE), ${COLUMN_PREFIX}OTHER_MOTIVATION)'
AND TABLE_NAME = 'DISTRO_LINE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'motivationCode',
PICKLIST_ITEM_NAME = 'MOTIVATION_CODE',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE)'
AND TABLE_NAME = 'DISTRO_LINE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'motivationCode',
PICKLIST_ITEM_NAME = 'MOTIVATION_CODE',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE)'
AND TABLE_NAME = 'DISTRO_LINE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
PICKLIST_NAME_ID = 'projectCode',
PICKLIST_ITEM_NAME = 'PROJECT_CODE',
CUSTOM_FIELD_ENTITY_TYPE = 'picklistItem',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ITEM_ID',
CUSTOM_FIELD_FIELD_NAME = 'AccountString1',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''AccountString1'')'
AND TABLE_NAME = 'DISTRO_LINE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
PICKLIST_NAME_ID = 'projectCode',
PICKLIST_ITEM_NAME = 'PROJECT_CODE',
CUSTOM_FIELD_ENTITY_TYPE = 'picklistItem',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ITEM_ID',
CUSTOM_FIELD_FIELD_NAME = 'AccountString2',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''AccountString2'')'
AND TABLE_NAME = 'DISTRO_LINE';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'posted',
PICKLIST_ITEM_NAME = 'CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''posted'', CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'posted',
PICKLIST_ITEM_NAME = 'CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(''posted'', CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'posted',
PICKLIST_ITEM_NAME = 'CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(''posted'', CASE WHEN ${COLUMN_PREFIX}POSTED = 1 THEN ''true'' WHEN ${COLUMN_PREFIX}POSTED = 0 THEN ''false'' ELSE NULL END)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'GROUP_BY_VALUE'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}GROUP_BY_VALUE)'
AND TABLE_NAME = 'VW_V2_GIFTSUMMARIES';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'GROUP_BY_VALUE'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}GROUP_BY_VALUE)'
AND TABLE_NAME = 'VW_V2_GIFTSUMMARIES';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'customFieldMap[emailType]',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'email',
CUSTOM_FIELD_ENTITY_ID = 'EMAIL_ID',
CUSTOM_FIELD_FIELD_NAME = 'emailType',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''customFieldMap[emailType]'', ${COLUMN_PREFIX}EMAIL_TYPE)'
AND TABLE_NAME = 'EMAIL';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'GROUP_BY_VALUE'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}GROUP_BY_VALUE)'
AND TABLE_NAME = 'VW_V2_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'GROUP_BY_VALUE'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}GROUP_BY_VALUE)'
AND TABLE_NAME = 'VW_V2_GIFTSUMMARIES_EXCLUDINGSOFTGIFTS';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'COMMUNICATION_HISTORY';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = 'communicationhistory',
CUSTOM_FIELD_ENTITY_ID = 'COMMUNICATION_HISTORY_ID',
CUSTOM_FIELD_FIELD_NAME = 'recordedBy',
CONSTITUENT_JOIN_FIELD = '${CUSTOM_FIELD}.FIELD_NUMERIC_VALUE'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(${COLUMN_PREFIX}COMMUNICATION_HISTORY_ID, ''communicationhistory'', ''recordedBy''))'
AND TABLE_NAME = 'COMMUNICATION_HISTORY';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(${COLUMN_PREFIX}COMMUNICATION_HISTORY_ID, ''communicationhistory'', ''recordedBy''))'
AND TABLE_NAME = 'COMMUNICATION_HISTORY';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '''' END',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'constituent',
CUSTOM_FIELD_ENTITY_ID = 'CONSTITUENT_ID',
CUSTOM_FIELD_FIELD_NAME = 'CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''constituentIndividualRoles'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''constituentOrganizationRoles'' ELSE '''' END',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '''' END, ${COLUMN_PREFIX}CONSTITUENT_ROLE)'
AND TABLE_NAME = 'CONSTITUENT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '''' END',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'constituent',
CUSTOM_FIELD_ENTITY_ID = 'CONSTITUENT_ID',
CUSTOM_FIELD_FIELD_NAME = 'CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''constituentIndividualRoles'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''constituentOrganizationRoles'' ELSE '''' END',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(CASE WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''individual'' THEN ''customFieldMap[constituentIndividualRoles]'' WHEN ${COLUMN_PREFIX}CONSTITUENT_TYPE = ''organization'' THEN ''customFieldMap[constituentOrganizationRoles]'' ELSE '''' END, ${COLUMN_PREFIX}CONSTITUENT_ROLE)'
AND TABLE_NAME = 'CONSTITUENT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'customFieldMap[donorProfiles]',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'constituent',
CUSTOM_FIELD_ENTITY_ID = 'CONSTITUENT_ID',
CUSTOM_FIELD_FIELD_NAME = 'donorProfiles',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(''customFieldMap[donorProfiles]'', ${COLUMN_PREFIX}DONOR_PROFILE)'
AND TABLE_NAME = 'CONSTITUENT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'customFieldMap[donorProfiles]',
PICKLIST_ITEM_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
CUSTOM_FIELD_ENTITY_TYPE = 'constituent',
CUSTOM_FIELD_ENTITY_ID = 'CONSTITUENT_ID',
CUSTOM_FIELD_FIELD_NAME = 'donorProfiles',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(''customFieldMap[donorProfiles]'', ${COLUMN_PREFIX}DONOR_PROFILE)'
AND TABLE_NAME = 'CONSTITUENT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'GIFT_IN_KIND';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = '${COLUMN_PREFIX}CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'GIFT_IN_KIND';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'IFNULL(${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE, ${COLUMN_PREFIX}OTHER_MOTIVATION)',
PICKLIST_NAME_ID = 'motivationCode',
PICKLIST_ITEM_NAME = 'MOTIVATION_CODE',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'IFNULL(GETPICKLISTDISPLAYVALUE(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE), ${COLUMN_PREFIX}OTHER_MOTIVATION)'
AND TABLE_NAME = 'GIFT_IN_KIND';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'motivationCode',
PICKLIST_ITEM_NAME = 'MOTIVATION_CODE',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE)'
AND TABLE_NAME = 'GIFT_IN_KIND';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'motivationCode',
PICKLIST_ITEM_NAME = 'MOTIVATION_CODE',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(''motivationCode'', ${COLUMN_PREFIX}MOTIVATION_CODE)'
AND TABLE_NAME = 'GIFT_IN_KIND';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
PICKLIST_NAME_ID = 'projectCode',
PICKLIST_ITEM_NAME = 'PROJECT_CODE',
CUSTOM_FIELD_ENTITY_TYPE = 'picklistItem',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ITEM_ID',
CUSTOM_FIELD_FIELD_NAME = 'AccountString1',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''AccountString1'')'
AND TABLE_NAME = 'GIFT_IN_KIND_DETAIL';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CUSTOM_FIELD}.FIELD_VALUE',
PICKLIST_NAME_ID = 'projectCode',
PICKLIST_ITEM_NAME = 'PROJECT_CODE',
CUSTOM_FIELD_ENTITY_TYPE = 'picklistItem',
CUSTOM_FIELD_ENTITY_ID = 'PICKLIST_ITEM_ID',
CUSTOM_FIELD_FIELD_NAME = 'AccountString2',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', ${COLUMN_PREFIX}PROJECT_CODE), ''picklistItem'', ''AccountString2'')'
AND TABLE_NAME = 'GIFT_IN_KIND_DETAIL';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'gikCategory',
PICKLIST_ITEM_NAME = 'CATEGORY',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''gikCategory'', ${COLUMN_PREFIX}CATEGORY)'
AND TABLE_NAME = 'GIFT_IN_KIND_DETAIL';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'gikCategory',
PICKLIST_ITEM_NAME = 'CATEGORY',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(''gikCategory'', ${COLUMN_PREFIX}CATEGORY)'
AND TABLE_NAME = 'GIFT_IN_KIND_DETAIL';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'gikCategory',
PICKLIST_ITEM_NAME = 'CATEGORY',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(''gikCategory'', ${COLUMN_PREFIX}CATEGORY)'
AND TABLE_NAME = 'GIFT_IN_KIND_DETAIL';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'AGE(${CUSTOM_FIELD}.FIELD_DATE_VALUE, IFNULL(GETCUSTOMDATEFIELD(${COLUMN_PREFIX}CONSTITUENT_ID, ''constituent'', ''individual.deceased''), CURDATE()))',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = 'constituent',
CUSTOM_FIELD_ENTITY_ID = 'CONSTITUENT_ID',
CUSTOM_FIELD_FIELD_NAME = 'individual.birthDate',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'AGE(CAST(GETCUSTOMDATEFIELD(${COLUMN_PREFIX}CONSTITUENT_ID, ''constituent'', ''individual.birthDate'') AS DATETIME), IFNULL(CAST(GETCUSTOMDATEFIELD(${COLUMN_PREFIX}CONSTITUENT_ID, ''constituent'', ''individual.deceased'') AS DATETIME), CURDATE()))'
AND TABLE_NAME = 'CONSTITUENT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${CONSTITUENT_TABLE}.ACCOUNT_NUMBER',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTACCOUNTNUMBER(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'PAYMENT_HISTORY';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = 'CASE WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''individual'' THEN CONCAT_WS('', '', ${CONSTITUENT_TABLE}.LAST_NAME, ${CONSTITUENT_TABLE}.FIRST_NAME) WHEN ${CONSTITUENT_TABLE}.CONSTITUENT_TYPE = ''organization'' THEN ${CONSTITUENT_TABLE}.ORGANIZATION_NAME ELSE ${CONSTITUENT_TABLE}.CONSTITUENT_ID END',
PICKLIST_NAME_ID = '',
PICKLIST_ITEM_NAME = '',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = 'CONSTITUENT_ID'
WHERE COLUMN_NAME = 'GETCONSTITUENTDISPLAYNAME(${COLUMN_PREFIX}CONSTITUENT_ID)'
AND TABLE_NAME = 'PAYMENT_HISTORY';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DEFAULT_DISPLAY_VALUE',
PICKLIST_NAME_ID = 'adjustedStatus',
PICKLIST_ITEM_NAME = 'ADJUSTED_STATUS',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDISPLAYVALUE(''adjustedStatus'', ${COLUMN_PREFIX}ADJUSTED_STATUS)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.LONG_DESCRIPTION',
PICKLIST_NAME_ID = 'adjustedStatus',
PICKLIST_ITEM_NAME = 'ADJUSTED_STATUS',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTLONGDESCRIPTION(''adjustedStatus'', ${COLUMN_PREFIX}ADJUSTED_STATUS)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = '${PICKLIST_ITEM}.DETAIL',
PICKLIST_NAME_ID = 'adjustedStatus',
PICKLIST_ITEM_NAME = 'ADJUSTED_STATUS',
CUSTOM_FIELD_ENTITY_TYPE = '',
CUSTOM_FIELD_ENTITY_ID = '',
CUSTOM_FIELD_FIELD_NAME = '',
CONSTITUENT_JOIN_FIELD = ''
WHERE COLUMN_NAME = 'GETPICKLISTDETAIL(''adjustedStatus'', ${COLUMN_PREFIX}ADJUSTED_STATUS)'
AND TABLE_NAME = 'ADJUSTED_GIFT';

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET SOURCE_COLUMN_NAME = COLUMN_NAME
WHERE SOURCE_COLUMN_NAME IS NULL;

UPDATE THEGURU_TABLE_ADDITIONAL_FIELD_DEFINITIONS
SET PICKLIST_CUSTOM_FIELD = 1
WHERE DISPLAY_NAME IN ('Designation GL Account String 1', 'Designation GL Account String 2');

COMMIT;

DROP TABLE TEMP_THEGURU_VIEW_JOIN;