package com.mpower.ws.orangeleapV3.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.4
 * Thu Jul 08 13:32:47 CDT 2010
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", name = "OrangeLeap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrangeLeap {

    @WebResult(name = "ListCustomTableFieldsResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "ListCustomTableFieldsResponse")
    @WebMethod(operationName = "ListCustomTableFields")
    public ListCustomTableFieldsResponse listCustomTableFields(
        @WebParam(partName = "ListCustomTableFieldsRequest", name = "ListCustomTableFieldsRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        ListCustomTableFieldsRequest listCustomTableFieldsRequest
    );

    @WebResult(name = "GetCustomTableRowsResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetCustomTableRowsResponse")
    @WebMethod(operationName = "GetCustomTableRows")
    public GetCustomTableRowsResponse getCustomTableRows(
        @WebParam(partName = "GetCustomTableRowsRequest", name = "GetCustomTableRowsRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetCustomTableRowsRequest getCustomTableRowsRequest
    );

    @WebResult(name = "GetCustomTableRowCountResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetCustomTableRowCountResponse")
    @WebMethod(operationName = "GetCustomTableRowCount")
    public GetCustomTableRowCountResponse getCustomTableRowCount(
        @WebParam(partName = "GetCustomTableRowCountRequest", name = "GetCustomTableRowCountRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetCustomTableRowCountRequest getCustomTableRowCountRequest
    );

    @WebResult(name = "GetCustomTableTitleFieldResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetCustomTableTitleFieldResponse")
    @WebMethod(operationName = "GetCustomTableTitleField")
    public GetCustomTableTitleFieldResponse getCustomTableTitleField(
        @WebParam(partName = "GetCustomTableTitleFieldRequest", name = "GetCustomTableTitleFieldRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetCustomTableTitleFieldRequest getCustomTableTitleFieldRequest
    );

    @WebResult(name = "GetCustomTableConstituentContextFieldResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetCustomTableConstituentContextFieldResponse")
    @WebMethod(operationName = "GetCustomTableConstituentContextField")
    public GetCustomTableConstituentContextFieldResponse getCustomTableConstituentContextField(
        @WebParam(partName = "GetCustomTableConstituentContextFieldRequest", name = "GetCustomTableConstituentContextFieldRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetCustomTableConstituentContextFieldRequest getCustomTableConstituentContextFieldRequest
    );

    @WebResult(name = "ReadCustomTableRowResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "ReadCustomTableRowResponse")
    @WebMethod(operationName = "ReadCustomTableRow")
    public ReadCustomTableRowResponse readCustomTableRow(
        @WebParam(partName = "ReadCustomTableRowRequest", name = "ReadCustomTableRowRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        ReadCustomTableRowRequest readCustomTableRowRequest
    );

    @WebResult(name = "GetListMasterCustomTablesResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetListMasterCustomTablesResponse")
    @WebMethod(operationName = "GetListMasterCustomTables")
    public GetListMasterCustomTablesResponse getListMasterCustomTables(
        @WebParam(partName = "GetListMasterCustomTablesRequest", name = "GetListMasterCustomTablesRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetListMasterCustomTablesRequest getListMasterCustomTablesRequest
    );

    @WebResult(name = "GetListDetailCustomTablesResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetListDetailCustomTablesResponse")
    @WebMethod(operationName = "GetListDetailCustomTables")
    public GetListDetailCustomTablesResponse getListDetailCustomTables(
        @WebParam(partName = "GetListDetailCustomTablesRequest", name = "GetListDetailCustomTablesRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetListDetailCustomTablesRequest getListDetailCustomTablesRequest
    );

    @WebResult(name = "ReadCustomTableByIdResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "ReadCustomTableByIdResponse")
    @WebMethod(operationName = "ReadCustomTableById")
    public ReadCustomTableByIdResponse readCustomTableById(
        @WebParam(partName = "ReadCustomTableByIdRequest", name = "ReadCustomTableByIdRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        ReadCustomTableByIdRequest readCustomTableByIdRequest
    );

    @WebResult(name = "ListCustomTablesResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "ListCustomTablesResponse")
    @WebMethod(operationName = "ListCustomTables")
    public ListCustomTablesResponse listCustomTables(
        @WebParam(partName = "ListCustomTablesRequest", name = "ListCustomTablesRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        ListCustomTablesRequest listCustomTablesRequest
    );

    @Oneway
    @WebMethod(operationName = "GetListEntityeRelatedCustomTables")
    public void getListEntityeRelatedCustomTables(
        @WebParam(partName = "GetListEntityeRelatedCustomTablesRequest", name = "GetListEntityeRelatedCustomTablesRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetListEntityeRelatedCustomTablesRequest getListEntityeRelatedCustomTablesRequest
    );

    @WebResult(name = "GetPostalCodesByRadiusResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetPostalCodesByRadiusResponse")
    @WebMethod(operationName = "GetPostalCodesByRadius")
    public GetPostalCodesByRadiusResponse getPostalCodesByRadius(
        @WebParam(partName = "GetPostalCodesByRadiusRequest", name = "GetPostalCodesByRadiusRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetPostalCodesByRadiusRequest getPostalCodesByRadiusRequest
    );

    @WebResult(name = "SaveOrUpdateCustomTableRowResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "SaveOrUpdateCustomTableRowResponse")
    @WebMethod(operationName = "SaveOrUpdateCustomTableRow")
    public SaveOrUpdateCustomTableRowResponse saveOrUpdateCustomTableRow(
        @WebParam(partName = "SaveOrUpdateCustomTableRowRequest", name = "SaveOrUpdateCustomTableRowRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        SaveOrUpdateCustomTableRowRequest saveOrUpdateCustomTableRowRequest
    );

    @WebResult(name = "ReadCustomTableFieldByIdResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "ReadCustomTableFieldByIdResponse")
    @WebMethod(operationName = "ReadCustomTableFieldById")
    public ReadCustomTableFieldByIdResponse readCustomTableFieldById(
        @WebParam(partName = "ReadCustomTableFieldByIdRequest", name = "ReadCustomTableFieldByIdRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        ReadCustomTableFieldByIdRequest readCustomTableFieldByIdRequest
    );

    @WebResult(name = "ReadCustomTableByNameResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "ReadCustomTableByNameResponse")
    @WebMethod(operationName = "ReadCustomTableByName")
    public ReadCustomTableByNameResponse readCustomTableByName(
        @WebParam(partName = "ReadCustomTableByNameRequest", name = "ReadCustomTableByNameRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        ReadCustomTableByNameRequest readCustomTableByNameRequest
    );

    @WebResult(name = "GetDetailCustomTableRowsResponse", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/", partName = "GetDetailCustomTableRowsResponse")
    @WebMethod(operationName = "GetDetailCustomTableRows")
    public GetDetailCustomTableRowsResponse getDetailCustomTableRows(
        @WebParam(partName = "GetDetailCustomTableRowsRequest", name = "GetDetailCustomTableRowsRequest", targetNamespace = "http://www.orangeleap.com/orangeleap/services3.0/")
        GetDetailCustomTableRowsRequest getDetailCustomTableRowsRequest
    );
}
