
package com.mpower.ws.orangeleapV2.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.4
 * Thu Jul 01 13:12:06 CDT 2010
 * Generated source version: 2.2.4
 * 
 */

public final class OrangeLeap_OrangeLeapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.orangeleap.com/orangeleap/services2.0/", "OrangeLeapService");

    private OrangeLeap_OrangeLeapPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = OrangeLeapService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrangeLeapService ss = new OrangeLeapService(wsdlURL, SERVICE_NAME);
        OrangeLeap port = ss.getOrangeLeapPort();  
        
        {
        System.out.println("Invoking getPickLists...");
        com.mpower.ws.orangeleapV2.client.GetPickListsRequest _getPickLists_getPickListsRequest = null;
        com.mpower.ws.orangeleapV2.client.GetPickListsResponse _getPickLists__return = port.getPickLists(_getPickLists_getPickListsRequest);
        System.out.println("getPickLists.result=" + _getPickLists__return);


        }
        {
        System.out.println("Invoking getConstituentRecurringGiftCount...");
        com.mpower.ws.orangeleapV2.client.GetConstituentRecurringGiftCountRequest _getConstituentRecurringGiftCount_getConstituentRecurringGiftCountRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentRecurringGiftCountResponse _getConstituentRecurringGiftCount__return = port.getConstituentRecurringGiftCount(_getConstituentRecurringGiftCount_getConstituentRecurringGiftCountRequest);
        System.out.println("getConstituentRecurringGiftCount.result=" + _getConstituentRecurringGiftCount__return);


        }
        {
        System.out.println("Invoking getConstituentGiftCount...");
        com.mpower.ws.orangeleapV2.client.GetConstituentGiftCountRequest _getConstituentGiftCount_getConstituentGiftCountRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentGiftCountResponse _getConstituentGiftCount__return = port.getConstituentGiftCount(_getConstituentGiftCount_getConstituentGiftCountRequest);
        System.out.println("getConstituentGiftCount.result=" + _getConstituentGiftCount__return);


        }
        {
        System.out.println("Invoking getConstituentByListId...");
        com.mpower.ws.orangeleapV2.client.GetConstituentByListIdRequest _getConstituentByListId_getConstituentByListIdRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentByListIdResponse _getConstituentByListId__return = port.getConstituentByListId(_getConstituentByListId_getConstituentByListIdRequest);
        System.out.println("getConstituentByListId.result=" + _getConstituentByListId__return);


        }
        {
        System.out.println("Invoking getConstituentPledge...");
        com.mpower.ws.orangeleapV2.client.GetConstituentPledgeRequest _getConstituentPledge_getConstituentPledgeRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentPledgeResponse _getConstituentPledge__return = port.getConstituentPledge(_getConstituentPledge_getConstituentPledgeRequest);
        System.out.println("getConstituentPledge.result=" + _getConstituentPledge__return);


        }
        {
        System.out.println("Invoking saveOrUpdateGift...");
        com.mpower.ws.orangeleapV2.client.SaveOrUpdateGiftRequest _saveOrUpdateGift_saveOrUpdateGiftRequest = null;
        com.mpower.ws.orangeleapV2.client.SaveOrUpdateGiftResponse _saveOrUpdateGift__return = port.saveOrUpdateGift(_saveOrUpdateGift_saveOrUpdateGiftRequest);
        System.out.println("saveOrUpdateGift.result=" + _saveOrUpdateGift__return);


        }
        {
        System.out.println("Invoking getSegmentationList...");
        com.mpower.ws.orangeleapV2.client.GetSegmentationListRequest _getSegmentationList_getSegmentationListRequest = null;
        com.mpower.ws.orangeleapV2.client.GetSegmentationListResponse _getSegmentationList__return = port.getSegmentationList(_getSegmentationList_getSegmentationListRequest);
        System.out.println("getSegmentationList.result=" + _getSegmentationList__return);


        }
        {
        System.out.println("Invoking getSegmentationById...");
        com.mpower.ws.orangeleapV2.client.GetSegmentationByIdRequest _getSegmentationById_getSegmentationByIdRequest = null;
        com.mpower.ws.orangeleapV2.client.GetSegmentationByIdResponse _getSegmentationById__return = port.getSegmentationById(_getSegmentationById_getSegmentationByIdRequest);
        System.out.println("getSegmentationById.result=" + _getSegmentationById__return);


        }
        {
        System.out.println("Invoking getSegmentationListCount...");
        com.mpower.ws.orangeleapV2.client.GetSegmentationListCountRequest _getSegmentationListCount_getSegmentationListCountRequest = null;
        com.mpower.ws.orangeleapV2.client.GetSegmentationListCountResponse _getSegmentationListCount__return = port.getSegmentationListCount(_getSegmentationListCount_getSegmentationListCountRequest);
        System.out.println("getSegmentationListCount.result=" + _getSegmentationListCount__return);


        }
        {
        System.out.println("Invoking getPickListByName...");
        com.mpower.ws.orangeleapV2.client.GetPickListByNameRequest _getPickListByName_getPickListByNameRequest = null;
        com.mpower.ws.orangeleapV2.client.GetPickListByNameResponse _getPickListByName__return = port.getPickListByName(_getPickListByName_getPickListByNameRequest);
        System.out.println("getPickListByName.result=" + _getPickListByName__return);


        }
        {
        System.out.println("Invoking searchConstituents...");
        com.mpower.ws.orangeleapV2.client.SearchConstituentsRequest _searchConstituents_searchConstituentsRequest = null;
        com.mpower.ws.orangeleapV2.client.SearchConstituentsResponse _searchConstituents__return = port.searchConstituents(_searchConstituents_searchConstituentsRequest);
        System.out.println("searchConstituents.result=" + _searchConstituents__return);


        }
        {
        System.out.println("Invoking addPickListItemByName...");
        com.mpower.ws.orangeleapV2.client.AddPickListItemByNameRequest _addPickListItemByName_addPickListItemByNameRequest = null;
        com.mpower.ws.orangeleapV2.client.AddPickListItemByNameResponse _addPickListItemByName__return = port.addPickListItemByName(_addPickListItemByName_addPickListItemByNameRequest);
        System.out.println("addPickListItemByName.result=" + _addPickListItemByName__return);


        }
        {
        System.out.println("Invoking getConstituentRecurringGift...");
        com.mpower.ws.orangeleapV2.client.GetConstituentRecurringGiftRequest _getConstituentRecurringGift_getConstituentRecurringGiftRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentRecurringGiftResponse _getConstituentRecurringGift__return = port.getConstituentRecurringGift(_getConstituentRecurringGift_getConstituentRecurringGiftRequest);
        System.out.println("getConstituentRecurringGift.result=" + _getConstituentRecurringGift__return);


        }
        {
        System.out.println("Invoking createDefaultConstituent...");
        com.mpower.ws.orangeleapV2.client.CreateDefaultConstituentRequest _createDefaultConstituent_createDefaultConstituentRequest = null;
        com.mpower.ws.orangeleapV2.client.CreateDefaultConstituentResponse _createDefaultConstituent__return = port.createDefaultConstituent(_createDefaultConstituent_createDefaultConstituentRequest);
        System.out.println("createDefaultConstituent.result=" + _createDefaultConstituent__return);


        }
        {
        System.out.println("Invoking getConstituentById...");
        com.mpower.ws.orangeleapV2.client.GetConstituentByIdRequest _getConstituentById_getConstituentByIdRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentByIdResponse _getConstituentById__return = port.getConstituentById(_getConstituentById_getConstituentByIdRequest);
        System.out.println("getConstituentById.result=" + _getConstituentById__return);


        }
        {
        System.out.println("Invoking getSegmentationListByTypeCount...");
        com.mpower.ws.orangeleapV2.client.GetSegmentationListByTypeCountRequest _getSegmentationListByTypeCount_getSegmentationListByTypeCountRequest = null;
        com.mpower.ws.orangeleapV2.client.GetSegmentationListByTypeCountResponse _getSegmentationListByTypeCount__return = port.getSegmentationListByTypeCount(_getSegmentationListByTypeCount_getSegmentationListByTypeCountRequest);
        System.out.println("getSegmentationListByTypeCount.result=" + _getSegmentationListByTypeCount__return);


        }
        {
        System.out.println("Invoking getPaymentSourcesByConstituentId...");
        com.mpower.ws.orangeleapV2.client.GetPaymentSourcesByConstituentIdRequest _getPaymentSourcesByConstituentId_getPaymentSourcesByConstituentIdRequest = null;
        com.mpower.ws.orangeleapV2.client.GetPaymentSourcesByConstituentIdResponse _getPaymentSourcesByConstituentId__return = port.getPaymentSourcesByConstituentId(_getPaymentSourcesByConstituentId_getPaymentSourcesByConstituentIdRequest);
        System.out.println("getPaymentSourcesByConstituentId.result=" + _getPaymentSourcesByConstituentId__return);


        }
        {
        System.out.println("Invoking getConstituentPledgeCount...");
        com.mpower.ws.orangeleapV2.client.GetConstituentPledgeCountRequest _getConstituentPledgeCount_getConstituentPledgeCountRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentPledgeCountResponse _getConstituentPledgeCount__return = port.getConstituentPledgeCount(_getConstituentPledgeCount_getConstituentPledgeCountRequest);
        System.out.println("getConstituentPledgeCount.result=" + _getConstituentPledgeCount__return);


        }
        {
        System.out.println("Invoking saveOrUpdateConstituent...");
        com.mpower.ws.orangeleapV2.client.SaveOrUpdateConstituentRequest _saveOrUpdateConstituent_saveOrUpdateConstituentRequest = null;
        com.mpower.ws.orangeleapV2.client.SaveOrUpdateConstituentResponse _saveOrUpdateConstituent__return = port.saveOrUpdateConstituent(_saveOrUpdateConstituent_saveOrUpdateConstituentRequest);
        System.out.println("saveOrUpdateConstituent.result=" + _saveOrUpdateConstituent__return);


        }
        {
        System.out.println("Invoking getConstituentGift...");
        com.mpower.ws.orangeleapV2.client.GetConstituentGiftRequest _getConstituentGift_getConstituentGiftRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentGiftResponse _getConstituentGift__return = port.getConstituentGift(_getConstituentGift_getConstituentGiftRequest);
        System.out.println("getConstituentGift.result=" + _getConstituentGift__return);


        }
        {
        System.out.println("Invoking findConstituents...");
        com.mpower.ws.orangeleapV2.client.FindConstituentsRequest _findConstituents_findConstituentsRequest = null;
        com.mpower.ws.orangeleapV2.client.FindConstituentsResponse _findConstituents__return = port.findConstituents(_findConstituents_findConstituentsRequest);
        System.out.println("findConstituents.result=" + _findConstituents__return);


        }
        {
        System.out.println("Invoking addCommunicationHistory...");
        com.mpower.ws.orangeleapV2.client.AddCommunicationHistoryRequest _addCommunicationHistory_addCommunicationHistoryRequest = null;
        com.mpower.ws.orangeleapV2.client.AddCommunicationHistoryResponse _addCommunicationHistory__return = port.addCommunicationHistory(_addCommunicationHistory_addCommunicationHistoryRequest);
        System.out.println("addCommunicationHistory.result=" + _addCommunicationHistory__return);


        }
        {
        System.out.println("Invoking getCommunicationHistory...");
        com.mpower.ws.orangeleapV2.client.GetCommunicationHistoryRequest _getCommunicationHistory_getCommunicationHistoryRequest = null;
        com.mpower.ws.orangeleapV2.client.GetCommunicationHistoryResponse _getCommunicationHistory__return = port.getCommunicationHistory(_getCommunicationHistory_getCommunicationHistoryRequest);
        System.out.println("getCommunicationHistory.result=" + _getCommunicationHistory__return);


        }
        {
        System.out.println("Invoking getSegmentationListByType...");
        com.mpower.ws.orangeleapV2.client.GetSegmentationListByTypeRequest _getSegmentationListByType_getSegmentationListByTypeRequest = null;
        com.mpower.ws.orangeleapV2.client.GetSegmentationListByTypeResponse _getSegmentationListByType__return = port.getSegmentationListByType(_getSegmentationListByType_getSegmentationListByTypeRequest);
        System.out.println("getSegmentationListByType.result=" + _getSegmentationListByType__return);


        }
        {
        System.out.println("Invoking saveOrUpdateRecurringGift...");
        com.mpower.ws.orangeleapV2.client.SaveOrUpdateRecurringGiftRequest _saveOrUpdateRecurringGift_saveOrUpdateRecurringGiftRequest = null;
        com.mpower.ws.orangeleapV2.client.SaveOrUpdateRecurringGiftResponse _saveOrUpdateRecurringGift__return = port.saveOrUpdateRecurringGift(_saveOrUpdateRecurringGift_saveOrUpdateRecurringGiftRequest);
        System.out.println("saveOrUpdateRecurringGift.result=" + _saveOrUpdateRecurringGift__return);


        }
        {
        System.out.println("Invoking getConstituentByPaymentSource...");
        com.mpower.ws.orangeleapV2.client.GetConstituentByPaymentSourceRequest _getConstituentByPaymentSource_getConstituentByPaymentSourceRequest = null;
        com.mpower.ws.orangeleapV2.client.GetConstituentByPaymentSourceResponse _getConstituentByPaymentSource__return = port.getConstituentByPaymentSource(_getConstituentByPaymentSource_getConstituentByPaymentSourceRequest);
        System.out.println("getConstituentByPaymentSource.result=" + _getConstituentByPaymentSource__return);


        }
        {
        System.out.println("Invoking bulkAddCommunicationHistory...");
        com.mpower.ws.orangeleapV2.client.BulkAddCommunicationHistoryRequest _bulkAddCommunicationHistory_bulkAddCommunicationHistoryRequest = null;
        com.mpower.ws.orangeleapV2.client.BulkAddCommunicationHistoryResponse _bulkAddCommunicationHistory__return = port.bulkAddCommunicationHistory(_bulkAddCommunicationHistory_bulkAddCommunicationHistoryRequest);
        System.out.println("bulkAddCommunicationHistory.result=" + _bulkAddCommunicationHistory__return);


        }
        {
        System.out.println("Invoking getPickListsCount...");
        com.mpower.ws.orangeleapV2.client.GetPickListsCountRequest _getPickListsCount_getPickListsCountRequest = null;
        com.mpower.ws.orangeleapV2.client.GetPickListsCountResponse _getPickListsCount__return = port.getPickListsCount(_getPickListsCount_getPickListsCountRequest);
        System.out.println("getPickListsCount.result=" + _getPickListsCount__return);


        }
        {
        System.out.println("Invoking getSegmentationByName...");
        com.mpower.ws.orangeleapV2.client.GetSegmentationByNameRequest _getSegmentationByName_getSegmentationByNameRequest = null;
        com.mpower.ws.orangeleapV2.client.GetSegmentationByNameResponse _getSegmentationByName__return = port.getSegmentationByName(_getSegmentationByName_getSegmentationByNameRequest);
        System.out.println("getSegmentationByName.result=" + _getSegmentationByName__return);


        }
        {
        System.out.println("Invoking getCommunicationHistoryCount...");
        com.mpower.ws.orangeleapV2.client.GetCommunicationHistoryCountRequest _getCommunicationHistoryCount_getCommunicationHistoryCountRequest = null;
        com.mpower.ws.orangeleapV2.client.GetCommunicationHistoryCountResponse _getCommunicationHistoryCount__return = port.getCommunicationHistoryCount(_getCommunicationHistoryCount_getCommunicationHistoryCountRequest);
        System.out.println("getCommunicationHistoryCount.result=" + _getCommunicationHistoryCount__return);


        }
        {
        System.out.println("Invoking saveOrUpdatePledge...");
        com.mpower.ws.orangeleapV2.client.SaveOrUpdatePledgeRequest _saveOrUpdatePledge_saveOrUpdatePledgeRequest = null;
        com.mpower.ws.orangeleapV2.client.SaveOrUpdatePledgeResponse _saveOrUpdatePledge__return = port.saveOrUpdatePledge(_saveOrUpdatePledge_saveOrUpdatePledgeRequest);
        System.out.println("saveOrUpdatePledge.result=" + _saveOrUpdatePledge__return);


        }

        System.exit(0);
    }

}
