SET @REPORTSUBSOURCE_ID = (SELECT MAX(REPORTSUBSOURCE_ID) FROM REPORTDATASUBSOURCE WHERE VIEW_NAME = 'VW_TOUCHPOINTS_CONSTITUENT_INFORMATION');

-- ***********************************************************************
-- Address Information Field Group
-- ***********************************************************************
CALL INSERTREPORTFIELDGROUP('Contact''s Primary Address Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

-- Address ID
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_ADDRESS_ID', 'Address ID', b'0', 2, @REPORTFIELDGROUP_ID);

-- Address Type
CALL INSERTREPORTFIELDWITHALIAS('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_ADDRESS_TYPE', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(ADDRESS_ADDRESS_ID, ''address'', ''addressType'', ''customFieldMap[addressType]'')', 'Address Type', b'0', 1, @REPORTFIELDGROUP_ID);

-- Address Status
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_ACTIVATION_STATUS', 'Address Status', b'0', 1, @REPORTFIELDGROUP_ID);

-- Effective Date
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_EFFECTIVE_DATE', 'Address Effective Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Seasonal Start Date
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_SEASONAL_START_DATE_DISPLAY', 'Seasonal Start Date', b'0', 1, @REPORTFIELDGROUP_ID);

-- Seasonal End Date
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_SEASONAL_END_DATE_DISPLAY', 'Seasonal End Date', b'0', 1, @REPORTFIELDGROUP_ID);

-- Temporary Start Date
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_TEMPORARY_START_DATE', 'Temporary Start Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Temporary End Date
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_TEMPORARY_END_DATE', 'Temporary End Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Address Line 1
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_ADDRESS_LINE_1', 'Address Line 1', b'0', 1, @REPORTFIELDGROUP_ID);

-- Address Line 2
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_ADDRESS_LINE_2', 'Address Line 2', b'0', 1, @REPORTFIELDGROUP_ID);

-- Address Line 3
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_ADDRESS_LINE_3', 'Address Line 3', b'0', 1, @REPORTFIELDGROUP_ID);

-- City
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_CITY', 'City', b'0', 1, @REPORTFIELDGROUP_ID);

-- State/Province
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_STATE_PROVINCE', 'State/Province', b'0', 1, @REPORTFIELDGROUP_ID);

-- Country
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_COUNTRY', 'Country', b'0', 1, @REPORTFIELDGROUP_ID);

-- Zip/Postal Code
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_POSTAL_CODE', 'Zip/Postal Code', b'0', 1, @REPORTFIELDGROUP_ID);

-- Receive Correspondence
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_RECEIVE_CORRESPONDENCE', 'Receive Correspondence', b'0', 6, @REPORTFIELDGROUP_ID);

-- Comments
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_COMMENT', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);

-- Address Create Date
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_CREATE_DATE', 'Address Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Address Update Date
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_UPDATE_DATE', 'Address Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Primary Address
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_IS_PRIMARY', 'Primary Address', b'0', 6, @REPORTFIELDGROUP_ID);

-- Address Undeliverable
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_UNDELIVERABLE', 'Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);

-- Address Inactive
CALL INSERTREPORTFIELD('ADDRESS_PRIMARY_ADDRESS_ID', 'ADDRESS_PRIMARY_INACTIVE', 'Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Email Information Field Group
-- ***********************************************************************
CALL INSERTREPORTFIELDGROUP('Contact''s Primary Email Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

-- Email Address ID
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_EMAIL_ID', 'Email Address ID', b'0', 2, @REPORTFIELDGROUP_ID);

-- Email Type
CALL INSERTREPORTFIELDWITHALIAS('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_EMAIL_TYPE', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(EMAIL_EMAIL_ID, ''email'', ''emailType'', ''customFieldMap[emailType]'')', 'Email Type', b'0', 1, @REPORTFIELDGROUP_ID);

-- Email Status
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_ACTIVATION_STATUS', 'Email Status', b'0', 1, @REPORTFIELDGROUP_ID);

-- Effective Date
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_EFFECTIVE_DATE', 'Effective Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Seasonal Start Date
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_SEASONAL_START_DATE_DISPLAY', 'Seasonal Start Date', b'0', 1, @REPORTFIELDGROUP_ID);

-- Seasonal End Date
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_SEASONAL_END_DATE_DISPLAY', 'Seasonal End Date', b'0', 1, @REPORTFIELDGROUP_ID);

-- Temporary Start Date
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_TEMPORARY_START_DATE', 'Temporary Start Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Temporary End Date
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_TEMPORARY_END_DATE', 'Temporary End Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Email Address
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_EMAIL_ADDRESS', 'Email Address', b'0', 1, @REPORTFIELDGROUP_ID);

-- Email Display
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_EMAIL_DISPLAY', 'Email Display', b'0', 1, @REPORTFIELDGROUP_ID);

-- Receive Correspondence
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_RECEIVE_CORRESPONDENCE', 'Receive Correspondence', b'0', 6, @REPORTFIELDGROUP_ID);

-- Comments
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_COMMENT', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);

-- Email Address Create Date
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_CREATE_DATE', 'Email Address Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Email Address Update Date
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_UPDATE_DATE', 'Email Address Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Primary Email Address
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_IS_PRIMARY', 'Primary Email Address', b'0', 6, @REPORTFIELDGROUP_ID);

-- Email Address Undeliverable
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_UNDELIVERABLE', 'Email Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);

-- Email Address Inactive
CALL INSERTREPORTFIELD('EMAIL_PRIMARY_EMAIL_ID', 'EMAIL_PRIMARY_INACTIVE', 'Email Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Phone Number Information Field Group
-- ***********************************************************************
CALL INSERTREPORTFIELDGROUP('Contact''s Primary Phone Number Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

-- Phone Number ID
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_PHONE_ID', 'Phone Number ID', b'0', 2, @REPORTFIELDGROUP_ID);

-- Phone Type
CALL INSERTREPORTFIELDWITHALIAS('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_PHONE_TYPE', 'GETCUSTOMFIELDDISPLAYVALUECONCATENATED(PHONE_PHONE_ID, ''phone'', ''phoneType'', ''customFieldMap[phoneType]'')', 'Phone Type', b'0', 1, @REPORTFIELDGROUP_ID);

-- Phone Status
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_ACTIVATION_STATUS', 'Phone Status', b'0', 1, @REPORTFIELDGROUP_ID);

-- Effective Date
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_EFFECTIVE_DATE', 'Effective Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Seasonal Start Date
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_SEASONAL_START_DATE_DISPLAY', 'Seasonal Start Date', b'0', 1, @REPORTFIELDGROUP_ID);

-- Seasonal End Date
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_SEASONAL_END_DATE_DISPLAY', 'Seasonal End Date', b'0', 1, @REPORTFIELDGROUP_ID);

-- Temporary Start Date
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_TEMPORARY_START_DATE', 'Temporary Start Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Temporary End Date
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_TEMPORARY_END_DATE', 'Temporary End Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Phone Number
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_NUMBER', 'Phone Number', b'0', 1, @REPORTFIELDGROUP_ID);

-- Provider
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_PROVIDER', 'Provider', b'0', 1, @REPORTFIELDGROUP_ID);

-- SMS
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_SMS', 'SMS', b'0', 1, @REPORTFIELDGROUP_ID);

-- Receive Correspondence - Call
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_RECEIVE_CORRESPONDENCE', 'Receive Correspondence - Call', b'0', 6, @REPORTFIELDGROUP_ID);

-- Receive Correspondence - Text
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_RECEIVE_CORRESPONDENCE_TEXT', 'Receive Correspondence - Text', b'0', 6, @REPORTFIELDGROUP_ID);

-- Phone Comments
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_COMMENT', 'Phone Comments', b'0', 1, @REPORTFIELDGROUP_ID);

-- Phone Create Date
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_CREATE_DATE', 'Phone Create Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Phone Update Date
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_UPDATE_DATE', 'Phone Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- Primary Phone
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_IS_PRIMARY', 'Primary Phone', b'0', 6, @REPORTFIELDGROUP_ID);

-- Phone Undeliverable
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_UNDELIVERABLE', 'Phone Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);

-- Phone Inactive Status
CALL INSERTREPORTFIELD('PHONE_PRIMARY_PHONE_ID', 'PHONE_PRIMARY_INACTIVE', 'Phone Inactive Status', b'0', 6, @REPORTFIELDGROUP_ID);
