CREATE TABLE IF NOT EXISTS REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE
  (reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID BIGINT NOT NULL,
  reportDataSubSource_REPORTSUBSOURCE_ID BIGINT NOT NULL,
  REPORTSUBSOURCE_ID INTEGER NOT NULL,
  REPORTSEGMENTATIONTYPE_ID INTEGER NOT NULL,
  PRIMARY KEY (reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID, REPORTSUBSOURCE_ID))
ENGINE=InnoDB;

ALTER TABLE REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE ADD INDEX FKC3ABA16E53A8E03F (reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID), ADD CONSTRAINT FKC3ABA16E53A8E03F FOREIGN KEY (reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID) REFERENCES REPORTSEGMENTATIONTYPE (REPORTSEGMENTATIONTYPE_ID);
ALTER TABLE REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE ADD INDEX FKC3ABA16EA9997991 (reportDataSubSource_REPORTSUBSOURCE_ID), ADD CONSTRAINT FKC3ABA16EA9997991 FOREIGN KEY (reportDataSubSource_REPORTSUBSOURCE_ID) REFERENCES REPORTDATASUBSOURCE (REPORTSUBSOURCE_ID);
