INSERT REPORTSEGMENTATIONTYPE
  (COLUMN_NAME, SEGMENTATIONTYPE)
SELECT
  'CONSTITUENT_CONSTITUENT_ID', 'Constituent Segmentation';

SET @REPORTSEGMENTATIONTYPEID = LAST_INSERT_ID();

INSERT REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE
  (reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTSEGMENTATIONTYPE_ID)
SELECT DISTINCT
  @REPORTSEGMENTATIONTYPEID, REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID, @REPORTSEGMENTATIONTYPEID
FROM REPORTDATASUBSOURCE
JOIN REPORTFIELDGROUP_REPORTDATASUBSOURCE ON REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID = REPORTFIELDGROUP_REPORTDATASUBSOURCE.reportDataSubSource_REPORTSUBSOURCE_ID
JOIN REPORTFIELD_REPORTFIELDGROUP ON REPORTFIELDGROUP_REPORTDATASUBSOURCE.REPORTFIELDGROUP_REPORTFIELDGROUP_ID = REPORTFIELD_REPORTFIELDGROUP.reportFieldGroup_REPORTFIELDGROUP_ID
JOIN REPORTFIELD ON REPORTFIELD_REPORTFIELDGROUP.fields_REPORTFIELD_ID = REPORTFIELD.REPORTFIELD_ID
WHERE COLUMN_NAME = 'CONSTITUENT_CONSTITUENT_ID' OR PRIMARY_KEYS LIKE '%CONSTITUENT_CONSTITUENT_ID';

INSERT REPORTSEGMENTATIONTYPE
  (COLUMN_NAME, SEGMENTATIONTYPE)
SELECT
  'GIFT_GIFT_ID', 'Gift Segmentation';

SET @REPORTSEGMENTATIONTYPEID = LAST_INSERT_ID();

INSERT REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE
  (reportSegmentationTypes_REPORTSEGMENTATIONTYPE_ID, reportDataSubSource_REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTSEGMENTATIONTYPE_ID)
SELECT DISTINCT
  @REPORTSEGMENTATIONTYPEID, REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID, REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID, @REPORTSEGMENTATIONTYPEID
FROM REPORTDATASUBSOURCE
JOIN REPORTFIELDGROUP_REPORTDATASUBSOURCE ON REPORTDATASUBSOURCE.REPORTSUBSOURCE_ID = REPORTFIELDGROUP_REPORTDATASUBSOURCE.reportDataSubSource_REPORTSUBSOURCE_ID
JOIN REPORTFIELD_REPORTFIELDGROUP ON REPORTFIELDGROUP_REPORTDATASUBSOURCE.REPORTFIELDGROUP_REPORTFIELDGROUP_ID = REPORTFIELD_REPORTFIELDGROUP.reportFieldGroup_REPORTFIELDGROUP_ID
JOIN REPORTFIELD ON REPORTFIELD_REPORTFIELDGROUP.fields_REPORTFIELD_ID = REPORTFIELD.REPORTFIELD_ID
WHERE COLUMN_NAME = 'GIFT_GIFT_ID' OR PRIMARY_KEYS LIKE '%GIFT_GIFT_ID';
