DELIMITER $$

DROP PROCEDURE IF EXISTS ADDCOLUMN_UPDATESCRIPT$$

CREATE PROCEDURE ADDCOLUMN_UPDATESCRIPT() BEGIN
	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='URL' AND TABLE_NAME='REPORTFIELD' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTFIELD
		ADD COLUMN `URL` varchar(255) default NULL;
	END IF;

	IF NOT EXISTS
		(SELECT * FROM INFORMATION_SCHEMA.COLUMNS
		WHERE COLUMN_NAME='TOOLTIP' AND TABLE_NAME='REPORTFIELD' AND TABLE_SCHEMA = DATABASE())
	THEN
		ALTER TABLE REPORTFIELD
		ADD COLUMN `TOOLTIP` varchar(255) default NULL;
	END IF;

END;
$$

DELIMITER ;

CALL ADDCOLUMN_UPDATESCRIPT();

DROP PROCEDURE ADDCOLUMN_UPDATESCRIPT;


ALTER TABLE REPORTFIELD


UPDATE REPORTFIELD set URL="\"http://localhost:8080/orangeleap/constituent.htm?constituentId=\" + $F{CONSTITUENT_CONSTITUENT_ID}",TOOLTIP="\"Show Constiuent in Orange Leap\"" where PRIMARY_KEYS="CONSTITUENT_CONSTITUENT_ID";