
-- ***********************************************************************
-- Journal Field Groups
-- ***********************************************************************

SET @REPORTDATASUBSOURCEGROUP_ID = (SELECT MAX(REPORTSUBSOURCEGROUP_ID) FROM REPORTDATASUBSOURCEGROUP WHERE DISPLAY_NAME = 'Transactions');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME)
VALUES
	('Journals', 0, 'VW_JOURNAL', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults');

SET @REPORTSUBSOURCE_ID = LAST_INSERT_ID();
-- insert report field group
CALL INSERTREPORTFIELDGROUP('Journal', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
-- insert report fields
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_JOURNAL_ID', 'Journal ID', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_POST_BATCH', 'Post Batch Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ENTITY', 'Entity', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ENTITY_ID', 'Entity Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_MASTER_ENTITY', 'Master Entity', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_MASTER_ENTITY_ID', 'Master Entity Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ORIG_ENTITY', 'Original Entity', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL__ORIG_ENTITY_ID', 'Original Entity Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_CODE', 'Journal Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_GL_CODE', 'GL Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_GL_ACCOUNT_1', 'GL Account 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_GL_ACCOUNT_2', 'GL Account 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_AMOUNT', 'Journal Amount', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_JE_TYPE', 'Journal Entry Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_PAYMENT_METHOD', 'Payment Method', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_CC_TYPE', 'Credit Card Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_DESCRIPTION', 'Journal Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_DONATION_DATE', 'Donation Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ADJUSTMENT_DATE', 'Adjustment Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_POSTED_DATE', 'Posted Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_EXPORT_DATE', 'Export Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_CREATE_DATE', 'Journal Create Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_UPDATE_DATE', 'Journal Update Date', b'0', 4, @REPORTFIELDGROUP_ID);


-- ***********************************************************************
-- Journals, Gifts & Adjusted Gifts  Field Groups
-- ***********************************************************************

SET @REPORTDATASUBSOURCEGROUP_ID = (SELECT MAX(REPORTSUBSOURCEGROUP_ID) FROM REPORTDATASUBSOURCEGROUP WHERE DISPLAY_NAME = 'Transactions');

INSERT INTO REPORTDATASUBSOURCE
	(DISPLAY_NAME, DATABASE_TYPE, VIEW_NAME, reportDataSubSourceGroup_REPORTSUBSOURCEGROUP_ID, REPORT_FORMAT_TYPE, JASPER_DATASOURCE_NAME, SEGMENTATION_RESULTS_DATASOURCE_NAME)
VALUES
	('Journals, Gifts & Adjusted Gifts', 0, 'VW_JOURNAL_GIFTS_ADJUSTED_GIFTS', @REPORTDATASUBSOURCEGROUP_ID, 0, '/datasources/ReportWizardJdbcDS', '/datasources/ReportWizardJdbcDSSegmentationResults');

SET @REPORTSUBSOURCE_ID = LAST_INSERT_ID();
-- insert report field group
CALL INSERTREPORTFIELDGROUP('Journal', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
-- insert report fields
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_JOURNAL_ID', 'Journal ID', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_POST_BATCH', 'Post Batch Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ENTITY', 'Entity', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ENTITY_ID', 'Entity Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_MASTER_ENTITY', 'Master Entity', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_MASTER_ENTITY_ID', 'Master Entity Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ORIG_ENTITY', 'Original Entity', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL__ORIG_ENTITY_ID', 'Original Entity Id', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_CODE', 'Journal Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_GL_CODE', 'GL Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_GL_ACCOUNT_1', 'GL Account 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_GL_ACCOUNT_2', 'GL Account 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_AMOUNT', 'Journal Amount', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_JE_TYPE', 'Journal Entry Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_PAYMENT_METHOD', 'Payment Method', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_CC_TYPE', 'Credit Card Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_DESCRIPTION', 'Journal Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_DONATION_DATE', 'Donation Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_ADJUSTMENT_DATE', 'Adjustment Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_POSTED_DATE', 'Posted Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_EXPORT_DATE', 'Export Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_CREATE_DATE', 'Journal Create Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('JOURNAL_JOURNAL_ID', 'JOURNAL_UPDATE_DATE', 'Journal Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Gift Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Gift Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('GIFT_GIFT_ID', 'GIFT_ACCOUNT_NUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GIFT_CONSTITUENT_ID)', 'Account Number', b'1', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('GIFT_GIFT_ID', 'ACCOUNT_NAME', 'GETCONSTITUENTDISPLAYNAME(GIFT_CONSTITUENT_ID)', 'Account Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_GIFT_ID', 'Gift Reference Number', b'1', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_AMOUNT', 'Gift Amount', b'1', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_CURRENCY_CODE', 'Currency Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('GIFT_GIFT_ID', 'GIFT_STATUS_DISPLAYVALUE', 'GETPICKLISTDISPLAYVALUE(''giftStatus'', GIFT_GIFT_STATUS)', 'Gift Status', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('GIFT_GIFT_ID', 'GIFT_BANK', 'GETPICKLISTDISPLAYVALUE(''customFieldMap[bank]'', GETCUSTOMFIELD(GIFT_GIFT_ID, ''gift'', ''bank''))', 'Bank', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_POSTED', 'Posted', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_POSTED_DATE', 'Posted Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_DONATION_DATE', 'Donation Date', b'1', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_POSTMARK_DATE', 'Postmark Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('GIFT_GIFT_ID', 'GIFT_SOURCE', 'GETPICKLISTDISPLAYVALUE(''customFieldMap[source]'', GETCUSTOMFIELD(GIFT_GIFT_ID, ''gift'', ''source''))', 'Source', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_COMMENTS', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_TRANSACTIONDATE', 'Transaction Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Payment Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Payment Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION', 'Payment Profile Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_INACTIVE', 'Payment Method Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_TYPE', 'Payment Method', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE', 'Credit Card Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME', 'Credit Card Holder Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION', 'Credit Card Expiration', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE', 'Credit Card Expiration (Date / Time)', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME', 'ACH Holder Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER', 'ACH Routing Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_SOURCE_LAST_FOUR_DIGITS', 'Credit Card / ACH Account Number - Last 4 Digits', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_CHECK_NUMBER', 'Check Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1', 'Address Line 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2', 'Address Line 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3', 'Address Line 3', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_CITY', 'City', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_STATE_PROVINCE', 'State/Province', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_POSTAL_CODE', 'Zip/Postal Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_COUNTRY', 'Country', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_IS_PRIMARY', 'Primary Address', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_UNDELIVERABLE', 'Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_ADDRESS_INACTIVE', 'Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_PHONE_NUMBER', 'Phone Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_PHONE_IS_PRIMARY', 'Primary Phone', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_PHONE_UNDELIVERABLE', 'Phone Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_PHONE_INACTIVE', 'Phone Inactive', b'0', 6, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Payment Status Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Payment Status Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_STATUS', 'Payment Status', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_MESSAGE', 'Payment Message', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_PAYMENT_TXREFNUM', 'Payment Reference Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_AUTH_CODE', 'Authorization Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('GIFT_GIFT_ID', 'GIFT_AVS_MESSAGE', 'AVS Message', b'0', 1, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Pledge Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Associated Pledge Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'Pledge ID', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_ACCOUNT_NUMBER', 'GETCONSTITUENTACCOUNTNUMBER(VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_CONSTITUENT_ID)', 'Account Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_AMOUNT_PER_GIFT', 'Amount Per Gift', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_AMOUNT_TOTAL', 'Amount Total', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_CURRENCY_CODE', 'Currency Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_STATUS', 'Status', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_FREQUENCY', 'Frequency', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_PLEDGE_DATE', 'Pledge Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_PROJECTED_DATE', 'Projected Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_START_DATE', 'Start Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_END_DATE', 'End Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMITMENT_ID', 'VW_PLEDGES_DISTRIBUTIONS_COMMITMENT_COMMENTS', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);


-- ***********************************************************************
-- Journal Pledge Distribution Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Associated Pledge Distribution Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'Pledge Distribution Reference Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_AMOUNT', 'Pledge Distribution Amount', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PERCENTAGE', 'Percentage', b'0', 3, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE', 'Designation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE)', 'Designation Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_GLPART1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''01-GLPART1'')', 'Designation GL Part 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_GLPART2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''02-GLPART2'')', 'Designation GL Part 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_GLPART3', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''03-GLPART3'')', 'Designation GL Part 3', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_GLPART4', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''04-GLPART4'')', 'Designation GL Part 4', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_GLACCOUNTCODE', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''GLAccountCode'')', 'Designation GL Account Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString1'')', 'Designation GL Account String 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString2'')', 'Designation GL Account String 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_MOTIVATION_CODE', 'Motivation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_DISTRO_LINE_ID', 'VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''motivationCode'', VW_PLEDGES_DISTRIBUTIONS_DISTRO_LINE_MOTIVATION_CODE)', 'Motivation Description', b'0', 1, @REPORTFIELDGROUP_ID);


-- ***********************************************************************
-- Journal Associated Recurring Gift Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Associated Recurring Gift Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_COMMITMENT_ID', 'Recurring Gift ID', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_ACCOUNT_NUMBER', 'GETCONSTITUENTACCOUNTNUMBER(VW_RGD_COMMITMENT_CONSTITUENT_ID)', 'Account Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_COMMITMENT_COMMITMENT_ID', 'ACCOUNT_NAME', 'GETCONSTITUENTDISPLAYNAME(VW_RGD_COMMITMENT_CONSTITUENT_ID)', 'Account Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_AUTO_PAY', 'Auto Pay', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_AMOUNT_PER_GIFT', 'Amount Per Gift', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_AMOUNT_TOTAL', 'Amount Total', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_CURRENCY_CODE', 'Currency Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_FREQUENCY', 'Frequency', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_START_DATE', 'Start Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_END_DATE', 'End Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_STATUS', 'Status', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_COMMENTS', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_LAST_ENTRY_DATE', 'Last Entry Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_CREATE_DATE', 'Recurring Gift Create Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_UPDATE_DATE', 'Recurring Gift Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Associated Recurring Gift Payment Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Associated Recurring Gift Payment Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION', 'Payment Profile Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_INACTIVE', 'Payment Method Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_TYPE', 'Payment Method', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_TYPE', 'Credit Card Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME', 'Credit Card Holder Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION', 'Credit Card Expiration', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE', 'Credit Card Expiration (Date / Time)', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_ACH_HOLDER_NAME', 'ACH Holder Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER', 'ACH Routing Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_SOURCE_LAST_FOUR_DIGITS', 'Credit Card / ACH Account Number - Last 4 Digits', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_CHECK_NUMBER', 'Check Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_1', 'Address Line 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_2', 'Address Line 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_ADDRESS_LINE_3', 'Address Line 3', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_CITY', 'City', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_STATE_PROVINCE', 'State/Province', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_POSTAL_CODE', 'Zip/Postal Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_COUNTRY', 'Country', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_IS_PRIMARY', 'Primary Address', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_UNDELIVERABLE', 'Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_ADDRESS_INACTIVE', 'Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_PHONE_NUMBER', 'Phone Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_PHONE_IS_PRIMARY', 'Primary Phone', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_PHONE_UNDELIVERABLE', 'Phone Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_COMMITMENT_COMMITMENT_ID', 'VW_RGD_COMMITMENT_PAYMENT_PHONE_INACTIVE', 'Phone Inactive', b'0', 6, @REPORTFIELDGROUP_ID);


-- ***********************************************************************
-- Journal Gift Distribution Information Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Associated Recurring Gift Distribution', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'Gift Distribution Reference Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_AMOUNT', 'Gift Distribution Amount', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PERCENTAGE', 'Percentage', b'0', 3, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE', 'Designation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE)', 'Designation Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_GLPART1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''01-GLPART1'')', 'Designation GL Part 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_GLPART2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''02-GLPART2'')', 'Designation GL Part 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_GLPART3', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''03-GLPART3'')', 'Designation GL Part 3', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_GLPART4', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''04-GLPART4'')', 'Designation GL Part 4', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_GLACCOUNTCODE', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''GLAccountCode'')', 'Designation GL Account Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString1'')', 'Designation GL Account String 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', VW_RGD_DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString2'')', 'Designation GL Account String 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_MOTIVATION_CODE', 'Motivation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'VW_RGD_DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''motivationCode'', VW_RGD_DISTRO_LINE_MOTIVATION_CODE)', 'Motivation Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'REFERENCE_ACCOUNT_NUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(VW_RGD_DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''reference''))', 'Reference Account Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('VW_RGD_DISTRO_LINE_DISTRO_LINE_ID', 'REFERENCE_ACCOUNT_NAME', 'IFNULL(GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(VW_RGD_DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''reference'')), GETCUSTOMFIELD(VW_RGD_DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''other_reference''))', 'Reference Account Name', b'0', 1, @REPORTFIELDGROUP_ID);


-- ***********************************************************************
--  Journal Gift Distribution Field Group
-- ***********************************************************************

CALL INSERTREPORTFIELDGROUP('Gift Distribution', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_DISTRO_LINE_ID', 'Gift Distribution Reference Number', b'1', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_AMOUNT', 'Gift Distribution Amount', b'1', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PERCENTAGE', 'Percentage', b'0', 3, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE', 'Designation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE)', 'Designation Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''01-GLPART1'')', 'Designation GL Part 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''02-GLPART2'')', 'Designation GL Part 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART3', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''03-GLPART3'')', 'Designation GL Part 3', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART4', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''04-GLPART4'')', 'Designation GL Part 4', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLACCOUNTCODE', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''GLAccountCode'')', 'Designation GL Account Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString1'')', 'Designation GL Account String 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString2'')', 'Designation GL Account String 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_MOTIVATION_CODE', 'Motivation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''motivationCode'', DISTRO_LINE_MOTIVATION_CODE)', 'Motivation Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'REFERENCE_ACCOUNT_NUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''reference''))', 'Reference Account Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'REFERENCE_ACCOUNT_NAME', 'IFNULL(GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''reference'')), GETCUSTOMFIELD(DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''other_reference''))', 'Reference Account Name', b'0', 1, @REPORTFIELDGROUP_ID);




-- ***********************************************************************
-- Journal Gift Adjustment Information Field Group
-- ***********************************************************************
CALL INSERTREPORTFIELDGROUP('Gift Adjustment Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'Gift Adjustment Reference Number', b'1', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_CONSTITUENT_ACCOUNT_NUMBER', 'GETCONSTITUENTACCOUNTNUMBER(ADJUSTED_GIFT_CONSTITUENT_ID)', 'Account Number', b'1', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_CONSTITUENT_ACCOUNT_NAME', 'GETCONSTITUENTDISPLAYNAME(ADJUSTED_GIFT_CONSTITUENT_ID)', 'Account Name', b'1', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_GIFT_ID', 'Gift Reference Number', b'1', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_AMOUNT_TOTAL', 'Current Total Adjustment Amount', b'0', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_AMOUNT', 'Adjustment Amount', b'1', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_TRANSACTION_DATE', 'Adjustment Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_REASON', 'Adjustment Reason', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_TYPE', 'Adjustment Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_STATUS', 'Adjustment Status', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_POSTED', 'Posted', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_POSTED_DATE', 'Posted Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_BANK', 'GETPICKLISTDISPLAYVALUE(''customFieldMap[bank]'', GETCUSTOMFIELD(ADJUSTED_GIFT_ADJUSTED_GIFT_ID, ''adjustedgift'', ''bank''))', 'Bank', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_COMMENTS', 'Comments', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_CREATE_DATE', 'Adjustment Create Date', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_UPDATE_DATE', 'Adjustment Update Date', b'0', 4, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Gift Adjustment Payment Information Field Group
-- ***********************************************************************
CALL INSERTREPORTFIELDGROUP('Gift Adjustment Payment Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_ID', 'Gift Adjustment Payment Source Reference Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_PAYMENT_REQUIRED', 'Payment Required', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_ADJUSTED_PAYMENT_TO', 'Payment To', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_TYPE', 'Payment Method', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_CREDIT_CARD_TYPE', 'Credit Card Type', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_CREDIT_CARD_HOLDER_NAME', 'Credit Card Holder Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION', 'Credit Card Expiration', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_CREDIT_CARD_EXPIRATION_DATE', 'Credit Card Expiration (Date / Time)', b'0', 4, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_ACH_HOLDER_NAME', 'ACH Holder Name', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_ACH_ROUTING_NUMBER', 'ACH Routing Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_LAST_FOUR_DIGITS', 'Credit Card / ACH Account Number - Last 4 Digits', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_AUTH_CODE', 'Adjustment Authorization Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_CHECK_NUMBER', 'Check Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_PAYMENT_PROFILE_DESCRIPTION', 'Payment Profile Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_SOURCE_INACTIVE', 'Payment Method Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_1', 'Address Line 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_2', 'Address Line 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_ADDRESS_LINE_3', 'Address Line 3', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_CITY', 'City', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_STATE_PROVINCE', 'State/Province', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_POSTAL_CODE', 'Zip/Postal Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_IS_PRIMARY', 'Primary Address', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_UNDELIVERABLE', 'Address Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_INACTIVE', 'Address Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_ADDRESS_COUNTRY', 'Country', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_PHONE_NUMBER', 'Phone Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_PHONE_IS_PRIMARY', 'Primary Phone', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_PHONE_UNDELIVERABLE', 'Phone Undeliverable', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_PHONE_INACTIVE', 'Phone Inactive', b'0', 6, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_MESSAGE', 'Payment Message', b'0', 1, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Payment Status Information Field Group
-- ***********************************************************************
CALL INSERTREPORTFIELDGROUP('Payment Status Information', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_STATUS', 'Payment Status', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_MESSAGE', 'Payment Message', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_PAYMENT_TXREFNUM', 'Payment Reference Number', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('ADJUSTED_GIFT_ADJUSTED_GIFT_ID', 'ADJUSTED_GIFT_AUTH_CODE', 'Authorization Code', b'0', 1, @REPORTFIELDGROUP_ID);

-- ***********************************************************************
-- Journal Adjusted Gift Distribution Field Group
-- ***********************************************************************
CALL INSERTREPORTFIELDGROUP('Gift Adjustment Distribution', @REPORTSUBSOURCE_ID, @REPORTFIELDGROUP_ID);

CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_DISTRO_LINE_ID', 'Gift Distribution Reference Number', b'1', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_AMOUNT', 'Gift Distribution Amount', b'1', 5, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PERCENTAGE', 'Percentage', b'0', 3, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE', 'Designation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE)', 'Designation Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''01-GLPART1'')', 'Designation GL Part 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''02-GLPART2'')', 'Designation GL Part 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART3', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''03-GLPART3'')', 'Designation GL Part 3', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLPART4', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''04-GLPART4'')', 'Designation GL Part 4', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLACCOUNTCODE', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''GLAccountCode'')', 'Designation GL Account Code', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING1', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString1'')', 'Designation GL Account String 1', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_PROJECT_CODE_GLACCOUNTSTRING2', 'GETCUSTOMFIELD(GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE(''projectCode'', DISTRO_LINE_PROJECT_CODE), ''picklistItem'', ''AccountString2'')', 'Designation GL Account String 2', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELD('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_MOTIVATION_CODE', 'Motivation', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'DISTRO_LINE_MOTIVATION_CODE_DESCRIPTION', 'GETPICKLISTDISPLAYVALUE(''motivationCode'', DISTRO_LINE_MOTIVATION_CODE)', 'Motivation Description', b'0', 1, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'REFERENCE_ACCOUNT_NUMBER', 'GETCONSTITUENTACCOUNTNUMBER(GETCUSTOMFIELD(DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''reference''))', 'Reference Account Number', b'0', 2, @REPORTFIELDGROUP_ID);
CALL INSERTREPORTFIELDWITHALIAS('DISTRO_LINE_DISTRO_LINE_ID', 'REFERENCE_ACCOUNT_NAME', 'IFNULL(GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''reference'')), GETCUSTOMFIELD(DISTRO_LINE_DISTRO_LINE_ID, ''distributionline'', ''other_reference''))', 'Reference Account Name', b'0', 1, @REPORTFIELDGROUP_ID);

