-- Clementine-473

-- Correct Designation accounting information fields
UPDATE REPORTFIELD
SET COLUMN_NAME = REPLACE(COLUMN_NAME, 'GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE', 'GETPICKLISTITEMIDBYITEMNAME')
WHERE COLUMN_NAME LIKE '%GETPICKLISTITEMIDBYDEFAULTDISPLAYVALUE%';

-- Correct designation description fields
UPDATE REPORTFIELD
SET COLUMN_NAME = REPLACE(COLUMN_NAME, 'GETPICKLISTDISPLAYVALUE', 'GETPICKLISTLONGDESCRIPTION')
WHERE DISPLAY_NAME = 'Designation Description'
AND COLUMN_NAME LIKE 'GETPICKLISTDISPLAYVALUE%';

-- Correct designation fields
UPDATE REPORTFIELD
SET COLUMN_NAME = CONCAT('GETPICKLISTDISPLAYVALUE(''projectCode'', ', COLUMN_NAME, ')')
WHERE DISPLAY_NAME = 'Designation';

-- Correct motivation code fields
UPDATE REPORTFIELD
SET COLUMN_NAME = CONCAT('IFNULL(GETPICKLISTDISPLAYVALUE(''motivationCode'', ', COLUMN_NAME, '), ', COLUMN_NAME, ')')
WHERE DISPLAY_NAME = 'Motivation';

-- Correct motivation description fields
UPDATE REPORTFIELD
SET COLUMN_NAME = REPLACE(COLUMN_NAME, 'GETPICKLISTDISPLAYVALUE', 'GETPICKLISTLONGDESCRIPTION')
WHERE DISPLAY_NAME = 'Motivation Description'
AND COLUMN_NAME LIKE 'GETPICKLISTDISPLAYVALUE%';