CREATE TABLE IF NOT EXISTS REPORTSEGMENTATIONTYPE
  (REPORTSEGMENTATIONTYPE_ID BIGINT NOT NULL AUTO_INCREMENT,
  COLUMN_NAME VARCHAR(255),
  SEGMENTATIONTYPE VARCHAR(255),
  PRIMARY KEY (REPORTSEGMENTATIONTYPE_ID))
ENGINE=InnoDB;
