DELIMITER $$

DROP PROCEDURE IF EXISTS `INSERTCUSTOMFIELDDEFINITION_UPDATESCRIPT`$$

CREATE PROCEDURE INSERTCUSTOMFIELDDEFINITION_UPDATESCRIPT()
BEGIN
  DECLARE CSR_END INT DEFAULT 0;
  DECLARE REPORTFIELDGROUPID BIGINT DEFAULT 0;
  DECLARE PRIMARYKEYS VARCHAR(255) DEFAULT '';

  DECLARE CSR_FIELDGROUPS CURSOR FOR
    SELECT DISTINCT REPORTFIELDGROUP_REPORTFIELDGROUP_ID, PRIMARY_KEYS FROM REPORTFIELD_REPORTFIELDGROUP
    JOIN REPORTFIELD ON REPORTFIELD_REPORTFIELDGROUP.REPORTFIELD_ID = REPORTFIELD.REPORTFIELD_ID
    WHERE COLUMN_NAME LIKE '%DISTRO_LINE_ID%';

  DECLARE CONTINUE HANDLER FOR NOT FOUND SET CSR_END = 1;

  IF NOT EXISTS
    (SELECT * FROM VERSIONLOG
    WHERE SCRIPT = '20091008_01_DU_ReportField_DistroLineFields.sql')
  THEN
    OPEN CSR_FIELDGROUPS;

    FIELDGROUPS_LOOP: LOOP
      FETCH CSR_FIELDGROUPS INTO REPORTFIELDGROUPID, PRIMARYKEYS;

      IF CSR_END THEN
        LEAVE FIELDGROUPS_LOOP;
      END IF;


      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_TRIBUTE_TYPE'),
        CONCAT('GETPICKLISTDISPLAYVALUE(''customFieldMap[tribute]'', GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''tribute''))'),
        'Tribute Type', b'0', 1, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_TRIBUTE_REFERENCE'),
        CONCAT('IFNULL(GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''tributeReference'')), GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''other_tributeReference''))'),
        'Tribute Reference', b'0', 1, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_TRIBUTE_OCCASION'),
        CONCAT('GETPICKLISTDISPLAYVALUE(''customFieldMap[tributeOccasion]'', GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''tributeOccasion''))'),
        'Tribute Occasion', b'0', 1, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_ON_BEHALF_OF'),
        CONCAT('IFNULL(GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''onBehalfOf'')), GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''other_onBehalfOf''))'),
        'On Behalf Of', b'0', 1, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_ANONYMOUS'),
        CONCAT('IFNULL(GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''anonymous''), ''false'')'),
        'Anonymous', b'0', 6, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_RECOGNITION_NAME'),
        CONCAT('GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''recognitionName'')'),
        'Recognition Name', b'0', 1, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_TO_BE_NOTIFIED'),
        CONCAT('IFNULL(GETCONSTITUENTDISPLAYNAME(GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''notified'')), GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''other_notified''))'),
        'To Be Notified', b'0', 1, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_MESSAGE'),
        CONCAT('GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''message'')'),
        'Message', b'0', 1, REPORTFIELDGROUPID);

      CALL INSERTREPORTFIELDWITHALIAS(PRIMARYKEYS, REPLACE(PRIMARYKEYS, '_DISTRO_LINE_ID', '_TAX_DEDUCTIBLE'),
        CONCAT('GETCUSTOMFIELD(', PRIMARYKEYS, ', ''distributionline'', ''taxDeductible'')'),
        'Tax Deductible', b'0', 6, REPORTFIELDGROUPID);

      END LOOP;
    SET CSR_END = 0;
    CLOSE CSR_FIELDGROUPS;
  END IF;
END$$

DELIMITER ;

CALL INSERTCUSTOMFIELDDEFINITION_UPDATESCRIPT();
