DELIMITER $$

DROP PROCEDURE IF EXISTS ADDREPORTFIELDS$$

CREATE PROCEDURE ADDREPORTFIELDS()
BEGIN
	IF NOT EXISTS
		(SELECT * FROM REPORTCUSTOMFILTERDEFINITION
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 620000)
	THEN
		-- Gift Distribution is in a segmentation
		INSERT INTO REPORTCUSTOMFILTERDEFINITION (REPORTCUSTOMFILTERDEFINITION_ID, DISPLAY_TEXT, SQL_TEXT, DISPLAY_HTML)
		SELECT 620000, 'Segmentation - Gift Distribution is in segmentation / report',
		'EXISTS (SELECT * FROM THEGURU_SEGMENTATION_RESULT SEGTABLE WHERE SEGTABLE.REPORT_ID = {0} AND SEGTABLE.ENTITY_ID = [VIEWNAME].GIFT_GIFT_ID)',
		'Segmentation - Gift Distribution is in segmentation / report <br> {lookupReferenceBean:orangeLeapGiftDistributionSegmentationList}';

		INSERT REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
		SELECT DISTINCT REPORTCUSTOMFILTERDEFINITION_ID, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID, REPORTSUBSOURCE_ID + REPORTCUSTOMFILTERDEFINITION_ID
		FROM REPORTDATASUBSOURCE
		JOIN REPORTCUSTOMFILTERDEFINITION ON 1 = 1
		WHERE REPORTCUSTOMFILTERDEFINITION_ID = 620000
		AND REPORTDATASUBSOURCE.VIEW_NAME IN ('VW_GIFTS_DISTRIBUTIONS', 'VW_CONSTITUENTS_GIFTDISTRIBUTIONS', 'VW_CONSTITUENTS_RELATIONSHIPS_GIFTDISTRIBUTIONS');
	END IF;
END;
$$

DELIMITER ;

CALL ADDREPORTFIELDS();

DROP PROCEDURE ADDREPORTFIELDS;