
CREATE TABLE TMPREPORTDATASOURCE (REPORTSOURCE_ID BIGINT);
CREATE TABLE TMPREPORTDATASUBSOURCEGROUP (REPORTSUBSOURCEGROUP_ID BIGINT);
CREATE TABLE TMPREPORTDATASUBSOURCE (REPORTSUBSOURCE_ID BIGINT);
CREATE TABLE TMPREPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE (REPORTCUSTOMFILTERDEFINITION_ID BIGINT);
CREATE TABLE TMPREPORTFIELDGROUP_REPORTDATASUBSOURCE (REPORTFIELDGROUP_REPORTFIELDGROUP_ID BIGINT);
CREATE TABLE TMPREPORTFIELDGROUP (REPORTFIELDGROUP_ID BIGINT);
CREATE TABLE TMPREPORTFIELD_REPORTFIELDGROUP (FIELDS_REPORTFIELD_ID BIGINT);
CREATE TABLE TMPREPORTWIZARD(REPORTWIZARD_ID BIGINT);
CREATE TABLE TMPREPORTWIZARD_REPORTCHARTSETTINGS (REPORTCHARTSETTINGS_REPORTCHARTSETTINGS_ID BIGINT);
CREATE TABLE TMPREPORTWIZARD_REPORTFILTER (REPORTFILTERS_REPORTFILTER_ID BIGINT);
CREATE TABLE TMPREPORTWIZARD_REPORTSELECTEDFIELD (REPORTSELECTEDFIELDS_REPORTSELECTEDFIELD_ID BIGINT);


INSERT TMPREPORTDATASOURCE
SELECT REPORTSOURCE_ID FROM REPORTDATASOURCE
WHERE REPORT_NAME IN ('ORANGELEAP', 'ORANGE LEAP - SANDBOX');

INSERT TMPREPORTDATASUBSOURCEGROUP
SELECT REPORTSUBSOURCEGROUP_ID FROM REPORTDATASUBSOURCEGROUP
WHERE REPORTDATASOURCE_REPORTSOURCE_ID IN (SELECT REPORTSOURCE_ID FROM TMPREPORTDATASOURCE);

INSERT TMPREPORTDATASUBSOURCE
SELECT REPORTSUBSOURCE_ID FROM REPORTDATASUBSOURCE
WHERE REPORTDATASUBSOURCEGROUP_REPORTSUBSOURCEGROUP_ID IN (SELECT REPORTSUBSOURCEGROUP_ID FROM TMPREPORTDATASUBSOURCEGROUP);

INSERT TMPREPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
SELECT REPORTCUSTOMFILTERDEFINITIONS_REPORTCUSTOMFILTERDEFINITION_ID FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
WHERE REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID IN (SELECT REPORTSUBSOURCE_ID FROM TMPREPORTDATASUBSOURCE);

INSERT TMPREPORTFIELDGROUP_REPORTDATASUBSOURCE
SELECT REPORTFIELDGROUP_REPORTFIELDGROUP_ID FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
WHERE REPORTSUBSOURCE_ID IN (SELECT REPORTSUBSOURCE_ID FROM TMPREPORTDATASUBSOURCE);

INSERT TMPREPORTFIELDGROUP
SELECT REPORTFIELDGROUP_ID FROM REPORTFIELDGROUP
WHERE REPORTFIELDGROUP_ID IN (SELECT REPORTFIELDGROUP_REPORTFIELDGROUP_ID FROM TMPREPORTFIELDGROUP_REPORTDATASUBSOURCE);

INSERT TMPREPORTFIELD_REPORTFIELDGROUP
SELECT FIELDS_REPORTFIELD_ID FROM REPORTFIELD_REPORTFIELDGROUP
WHERE REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN (SELECT REPORTFIELDGROUP_ID FROM TMPREPORTFIELDGROUP);

INSERT TMPREPORTWIZARD
SELECT REPORTWIZARD_ID FROM REPORTWIZARD
WHERE REPORTSUBSOURCE_ID IN (SELECT REPORTSUBSOURCE_ID FROM TMPREPORTDATASUBSOURCE);

INSERT TMPREPORTWIZARD_REPORTCHARTSETTINGS
SELECT REPORTCHARTSETTINGS_REPORTCHARTSETTINGS_ID FROM REPORTWIZARD_REPORTCHARTSETTINGS
WHERE REPORTWIZARD_REPORTWIZARD_ID IN (SELECT REPORTWIZARD_ID FROM TMPREPORTWIZARD);

INSERT TMPREPORTWIZARD_REPORTFILTER
SELECT REPORTFILTERS_REPORTFILTER_ID FROM REPORTWIZARD_REPORTFILTER
WHERE REPORTWIZARD_REPORTWIZARD_ID IN (SELECT REPORTWIZARD_ID FROM TMPREPORTWIZARD);

INSERT TMPREPORTWIZARD_REPORTSELECTEDFIELD
SELECT REPORTSELECTEDFIELDS_REPORTSELECTEDFIELD_ID FROM REPORTWIZARD_REPORTSELECTEDFIELD
WHERE REPORTWIZARD_REPORTWIZARD_ID IN (SELECT REPORTWIZARD_ID FROM TMPREPORTWIZARD);



DELETE FROM REPORTWIZARD_REPORTSELECTEDFIELD
WHERE REPORTWIZARD_REPORTWIZARD_ID IN (SELECT REPORTWIZARD_ID FROM TMPREPORTWIZARD);

DELETE FROM REPORTSELECTEDFIELD
WHERE REPORTSELECTEDFIELD_ID IN (SELECT REPORTSELECTEDFIELDS_REPORTSELECTEDFIELD_ID FROM TMPREPORTWIZARD_REPORTSELECTEDFIELD);

DELETE FROM REPORTWIZARD_REPORTFILTER
WHERE REPORTWIZARD_REPORTWIZARD_ID IN (SELECT REPORTWIZARD_ID FROM TMPREPORTWIZARD);

DELETE FROM REPORTFILTER
WHERE REPORTFILTER_ID IN (SELECT REPORTFILTERS_REPORTFILTER_ID FROM TMPREPORTWIZARD_REPORTFILTER);

DELETE FROM REPORTWIZARD_REPORTCHARTSETTINGS
WHERE REPORTWIZARD_REPORTWIZARD_ID IN (SELECT REPORTWIZARD_ID FROM TMPREPORTWIZARD);

DELETE FROM REPORTCHARTSETTINGS
WHERE REPORTCHARTSETTINGS_ID IN (SELECT REPORTCHARTSETTINGS_REPORTCHARTSETTINGS_ID FROM TMPREPORTWIZARD_REPORTCHARTSETTINGS);

DELETE FROM REPORTWIZARD
WHERE REPORTSUBSOURCE_ID IN (SELECT REPORTSUBSOURCE_ID FROM TMPREPORTDATASUBSOURCE);

DELETE FROM REPORTFIELD_REPORTFIELDGROUP
WHERE REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN (SELECT REPORTFIELDGROUP_ID FROM TMPREPORTFIELDGROUP);

DELETE FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
WHERE REPORTFIELDGROUP_REPORTFIELDGROUP_ID IN (SELECT REPORTFIELDGROUP_REPORTFIELDGROUP_ID FROM TMPREPORTFIELDGROUP_REPORTDATASUBSOURCE);

DELETE FROM REPORTFIELDGROUP_REPORTDATASUBSOURCE
WHERE REPORTDATASUBSOURCE_REPORTSUBSOURCE_ID IN (SELECT REPORTSUBSOURCE_ID FROM TMPREPORTDATASUBSOURCE);

DELETE FROM REPORTFIELDGROUP
WHERE REPORTFIELDGROUP_ID IN (SELECT REPORTFIELDGROUP_REPORTFIELDGROUP_ID FROM TMPREPORTFIELDGROUP_REPORTDATASUBSOURCE);

DELETE FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE
WHERE REPORTSUBSOURCE_ID IN (SELECT REPORTSUBSOURCE_ID FROM TMPREPORTDATASUBSOURCE);

DELETE FROM REPORTSEGMENTATIONTYPE_REPORTDATASUBSOURCE
WHERE REPORTSUBSOURCE_ID IN (SELECT REPORTSUBSOURCE_ID FROM TMPREPORTDATASUBSOURCE);

DELETE FROM REPORTCUSTOMFILTERDEFINITION
WHERE REPORTCUSTOMFILTERDEFINITION_ID NOT IN (SELECT REPORTCUSTOMFILTERDEFINITIONS_REPORTCUSTOMFILTERDEFINITION_ID FROM REPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE);

DELETE FROM REPORTDATASUBSOURCE
WHERE REPORTDATASUBSOURCEGROUP_REPORTSUBSOURCEGROUP_ID IN (SELECT REPORTSUBSOURCEGROUP_ID FROM TMPREPORTDATASUBSOURCEGROUP);

DELETE FROM REPORTDATASUBSOURCEGROUP
WHERE REPORTDATASOURCE_REPORTSOURCE_ID IN (SELECT REPORTSOURCE_ID FROM TMPREPORTDATASOURCE);

DELETE FROM REPORTDATASOURCE
WHERE REPORTSOURCE_ID IN (SELECT REPORTSOURCE_ID FROM TMPREPORTDATASOURCE);


DROP TABLE TMPREPORTDATASOURCE;
DROP TABLE TMPREPORTDATASUBSOURCEGROUP;
DROP TABLE TMPREPORTDATASUBSOURCE;
DROP TABLE TMPREPORTCUSTOMFILTERDEFINITION_REPORTDATASUBSOURCE;
DROP TABLE TMPREPORTFIELDGROUP_REPORTDATASUBSOURCE;
DROP TABLE TMPREPORTFIELDGROUP;
DROP TABLE TMPREPORTFIELD_REPORTFIELDGROUP;
DROP TABLE TMPREPORTWIZARD;
DROP TABLE TMPREPORTWIZARD_REPORTCHARTSETTINGS;
DROP TABLE TMPREPORTWIZARD_REPORTFILTER;
DROP TABLE TMPREPORTWIZARD_REPORTSELECTEDFIELD;
