DELIMITER $$

DROP PROCEDURE IF EXISTS CALL_GENERATE_VIEWS;$$

CREATE PROCEDURE CALL_GENERATE_VIEWS() BEGIN
	IF (DATABASE() <> 'theguru')
	THEN
		CALL GENERATE_VIEWS(NULL);
	END IF;
END;$$

DELIMITER ;

CALL CALL_GENERATE_VIEWS();

DROP PROCEDURE CALL_GENERATE_VIEWS;