package com.mpower.dao;

import java.sql.SQLException;
import java.util.List;

import com.mpower.domain.ReportSegmentationResult;
import com.mpower.util.ReportSegmentationDatasourceSettings;

public interface ReportSegmentationResultsDao {
	public List<ReportSegmentationResult> readReportSegmentationResultsByReportId(Long reportId, ReportSegmentationDatasourceSettings reportSegmentationDatasourceDestination) throws SQLException;
	public int deleteReportSegmentationResultsByReportId(Long reportId, ReportSegmentationDatasourceSettings reportSegmentationDatasourceDestination) throws SQLException;
	public int executeSegmentationQuery(String query, ReportSegmentationDatasourceSettings reportSegmentationDatasourceSource, ReportSegmentationDatasourceSettings reportSegmentationDatasourceDestination) throws SQLException;
}
